In [2]:
import pandas as pd

In [3]:
people = {
    "first":["corey","sophie", "cristian"],
    "last":["schafer","muthoni","rodriguez"],
    "email":["corey@gmail.com","muthoni@gmail.com","rodriguez@gmail.com"]
}

In [4]:
df = pd.DataFrame(people)

In [5]:
df

      first       last                email
0     corey    schafer      corey@gmail.com
1    sophie    muthoni    muthoni@gmail.com
2  cristian  rodriguez  rodriguez@gmail.com

In [6]:
df.columns

Index(['first', 'last', 'email'], dtype='str')

In [9]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [10]:
df.shape

(3, 3)

In [11]:
df.size

9

In [12]:
df.values

array([['corey', 'schafer', 'corey@gmail.com'],
       ['sophie', 'muthoni', 'muthoni@gmail.com'],
       ['cristian', 'rodriguez', 'rodriguez@gmail.com']], dtype=object)

## Why Convert a Pandas DataFrame to a NumPy Array?

### 1. A Library Expects NumPy Arrays
Many scientific computing, machine learning, and optimization libraries are built around NumPy arrays and may not accept pandas DataFrames directly.

```python
X = df.to_numpy()

In [13]:
df.T

                     0                  1                    2
first            corey             sophie             cristian
last           schafer            muthoni            rodriguez
email  corey@gmail.com  muthoni@gmail.com  rodriguez@gmail.com

## Why Transpose a DataFrame?

Transposing a DataFrame swaps its rows and columns.

```python
df.T
```

### 1. Change the Orientation for Analysis

Sometimes your data is easier to analyze when observations become columns and variables become rows.

Before:

| Name  | Math | Science |
| ----- | ---- | ------- |
| Alice | 85   | 90      |
| Bob   | 78   | 88      |

After
|         | Alice | Bob |
| ------- | ----- | --- |
| Math    | 85    | 78  |
| Science | 90    | 88  |