# Cleaning Data
## How to handle missing values and Casting Data types

In [2]:
import pandas as pd
import numpy as np

In [12]:

people = {
    "first": ["corey", "sophie", "cristian", "john", "jane", np.nan, None, 'NA', 'Anonymous'],
    "last": ["schafer", "muthoni", "rodriguez", "NA", "Doe", np.nan, np.nan, 'Missing', 'Unknown'],
    "email": ["corey@gmail.com", "muthoni@gmail.com", "Anonymous@email.com",
              None, "janeDoe@gmail.com", None, np.nan, 'Anonymous@email.com', 'NA'],
    "age": ['33', '55', '63', '36', '46', None, None, 'Missing', None]
}

In [22]:
df = pd.DataFrame(people)

       first       last                email  age
0      corey    schafer      corey@gmail.com   33
1     sophie    muthoni    muthoni@gmail.com   55
2   cristian  rodriguez  Anonymous@email.com   63
3       john        NaN                  NaN   36
4       jane        Doe    janeDoe@gmail.com   46
5        NaN        NaN                  NaN  NaN
6        NaN        NaN                  NaN  NaN
7        NaN        NaN  Anonymous@email.com  NaN
8  Anonymous    Unknown                  NaN  NaN

In [14]:
df

       first       last                email      age
0      corey    schafer      corey@gmail.com       33
1     sophie    muthoni    muthoni@gmail.com       55
2   cristian  rodriguez  Anonymous@email.com       63
3       john         NA                  NaN       36
4       jane        Doe    janeDoe@gmail.com       46
5        NaN        NaN                  NaN      NaN
6        NaN        NaN                  NaN      NaN
7         NA    Missing  Anonymous@email.com  Missing
8  Anonymous    Unknown                   NA      NaN

In [15]:
df.dropna()#using default arguments

      first       last                email      age
0     corey    schafer      corey@gmail.com       33
1    sophie    muthoni    muthoni@gmail.com       55
2  cristian  rodriguez  Anonymous@email.com       63
4      jane        Doe    janeDoe@gmail.com       46
7        NA    Missing  Anonymous@email.com  Missing

In [17]:
df.dropna(axis='index',how='all')#using default arguments

       first       last                email      age
0      corey    schafer      corey@gmail.com       33
1     sophie    muthoni    muthoni@gmail.com       55
2   cristian  rodriguez  Anonymous@email.com       63
3       john         NA                  NaN       36
4       jane        Doe    janeDoe@gmail.com       46
7         NA    Missing  Anonymous@email.com  Missing
8  Anonymous    Unknown                   NA      NaN

### index and columns arguments
#### Setting to index meaning drop rows with missing values
### how/criteria to drop rows or columns if set to any means drop any row with missing values can be set to all meaning only drop the row if all columns have missing data

In [18]:
df.dropna(axis='columns',how='any')

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8]

In [20]:
df.dropna(axis='index',how='any',subset=['last','email'])

       first       last                email      age
0      corey    schafer      corey@gmail.com       33
1     sophie    muthoni    muthoni@gmail.com       55
2   cristian  rodriguez  Anonymous@email.com       63
4       jane        Doe    janeDoe@gmail.com       46
7         NA    Missing  Anonymous@email.com  Missing
8  Anonymous    Unknown                   NA      NaN

In [23]:
#custom missing values
df.replace('NA',np.nan,inplace=True)
df.replace('Missing',np.nan,inplace=True)

       first       last                email  age
0      corey    schafer      corey@gmail.com   33
1     sophie    muthoni    muthoni@gmail.com   55
2   cristian  rodriguez  Anonymous@email.com   63
3       john        NaN                  NaN   36
4       jane        Doe    janeDoe@gmail.com   46
5        NaN        NaN                  NaN  NaN
6        NaN        NaN                  NaN  NaN
7        NaN        NaN  Anonymous@email.com  NaN
8  Anonymous    Unknown                  NaN  NaN

In [24]:
df.isna()

   first   last  email    age
0  False  False  False  False
1  False  False  False  False
2  False  False  False  False
3  False   True   True  False
4  False  False  False  False
5   True   True   True   True
6   True   True   True   True
7   True   True  False   True
8  False  False   True   True

In [25]:
df.fillna('MISSING')

       first       last                email      age
0      corey    schafer      corey@gmail.com       33
1     sophie    muthoni    muthoni@gmail.com       55
2   cristian  rodriguez  Anonymous@email.com       63
3       john    MISSING              MISSING       36
4       jane        Doe    janeDoe@gmail.com       46
5    MISSING    MISSING              MISSING  MISSING
6    MISSING    MISSING              MISSING  MISSING
7    MISSING    MISSING  Anonymous@email.com  MISSING
8  Anonymous    Unknown              MISSING  MISSING

In [26]:
df.dtypes

first    str
last     str
email    str
age      str
dtype: object

In [27]:
df['age'].mean()

TypeError: Cannot perform reduction 'mean' with string dtype

In [28]:
type(np.nan)

float

In [30]:
df['age'] = df['age'].astype(float)

In [31]:
df.dtypes

first        str
last         str
email        str
age      float64
dtype: object

In [32]:
df['age'].mean()

np.float64(46.6)

In [ ]:
df.astype()