In [1]:
person = {
    "first":"corey",
    "last":"schafer",
    "email":"corey@gmail.com"
}

In [2]:
person = {
    "first":["corey"],
    "last":["schafer"],
    "email":["corey@gmail.com"]
}

In [3]:
people = {
    "first":["corey","sophie", "cristian"],
    "last":["schafer","muthoni","rodriguez"],
    "email":["corey@gmail.com","muthoni@gmail.com","rodriguez@gmail.com"]
}

In [4]:
#what is a dataframe?
#A DataFrame is a 2-dimensional labeled data structure with Rows(indexed) and 
#Columns(named)

In [5]:
# creating a dataframe from the people object
import pandas as pd

In [6]:
df = pd.DataFrame(people)

In [7]:
df

      first       last                email
0     corey    schafer      corey@gmail.com
1    sophie    muthoni    muthoni@gmail.com
2  cristian  rodriguez  rodriguez@gmail.com

In [8]:
#   (named columns)
#first	last	email 
# 0	corey	schafer	corey@gmail.com   (indexed rows)
# 1	sophie	muthoni	muthoni@gmail.com
# 2	cristian	rodriguez	rodriguez@gmail.com

# 
# 
# 
# 
#

In [9]:
# accessing a specific column in dataframe
df['email']

0        corey@gmail.com
1      muthoni@gmail.com
2    rodriguez@gmail.com
Name: email, dtype: str

In [10]:
type(df['email'])

pandas.Series

In [11]:
#SERIES:
#rows of a single column
#email series:

# 0        corey@gmail.com
# 1      muthoni@gmail.com
# 2    rodriguez@gmail.com
# Name: email, dtype: str

# accessing series as a key
# df['email']

# using dot notation
# df.email
df.email

0        corey@gmail.com
1      muthoni@gmail.com
2    rodriguez@gmail.com
Name: email, dtype: str

In [12]:
#accessing multiple colums
df[['last','email']]

#this is nolonger a series but filtered down dataframe

        last                email
0    schafer      corey@gmail.com
1    muthoni    muthoni@gmail.com
2  rodriguez  rodriguez@gmail.com

In [13]:
df.columns

Index(['first', 'last', 'email'], dtype='str')

In [14]:
df.iloc[0]
df.iloc[[0,1]]
df.iloc[[0,1],2]

0      corey@gmail.com
1    muthoni@gmail.com
Name: email, dtype: str

In [15]:
#loc (labels)
#the default indexes are our labels:
# label
# 0	schafer	corey@gmail.com
# 1	muthoni	muthoni@gmail.com
# 2	rodriguez	rodriguez@gmail.com
df.loc[0]

first              corey
last             schafer
email    corey@gmail.com
Name: 0, dtype: str

In [16]:
df.loc[[0,1],'email']

0      corey@gmail.com
1    muthoni@gmail.com
Name: email, dtype: str

In [17]:
df.loc[[0,1],['email','last']]

               email     last
0    corey@gmail.com  schafer
1  muthoni@gmail.com  muthoni

In [18]:
df.apply(lambda x:x.min())

first              corey
last             muthoni
email    corey@gmail.com
dtype: str

In [20]:
df.columns

Index(['first', 'last', 'email'], dtype='str')

In [22]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [23]:
df.dtypes

first    str
last     str
email    str
dtype: object

In [24]:
df.size

9

In [25]:
df

      first       last                email
0     corey    schafer      corey@gmail.com
1    sophie    muthoni    muthoni@gmail.com
2  cristian  rodriguez  rodriguez@gmail.com

In [26]:
df.T

                     0                  1                    2
first            corey             sophie             cristian
last           schafer            muthoni            rodriguez
email  corey@gmail.com  muthoni@gmail.com  rodriguez@gmail.com

In [27]:
df

      first       last                email
0     corey    schafer      corey@gmail.com
1    sophie    muthoni    muthoni@gmail.com
2  cristian  rodriguez  rodriguez@gmail.com

In [28]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   first   3 non-null      str
 1   last    3 non-null      str
 2   email   3 non-null      str
dtypes: str(3)
memory usage: 204.0 bytes

In [29]:
df.describe()

        first     last            email
count       3        3                3
unique      3        3                3
top     corey  schafer  corey@gmail.com
freq        1        1                1

In [30]:
df

      first       last                email
0     corey    schafer      corey@gmail.com
1    sophie    muthoni    muthoni@gmail.com
2  cristian  rodriguez  rodriguez@gmail.com

In [31]:
df.sort_values(by='last')

      first       last                email
1    sophie    muthoni    muthoni@gmail.com
2  cristian  rodriguez  rodriguez@gmail.com
0     corey    schafer      corey@gmail.com

In [32]:
df['last']

0      schafer
1      muthoni
2    rodriguez
Name: last, dtype: str

In [33]:
df.loc[0,'first']

'corey'

In [34]:
df.loc[0]

first              corey
last             schafer
email    corey@gmail.com
Name: 0, dtype: str

In [35]:
df.iloc[0]

first              corey
last             schafer
email    corey@gmail.com
Name: 0, dtype: str

In [36]:
df.iloc[0,0]

'corey'

In [37]:
df.iloc[0,2]

'corey@gmail.com'

In [38]:
df.rename(columns={
    'first':'firstname'
})

  firstname       last                email
0     corey    schafer      corey@gmail.com
1    sophie    muthoni    muthoni@gmail.com
2  cristian  rodriguez  rodriguez@gmail.com

In [39]:
df.isnull()

   first   last  email
0  False  False  False
1  False  False  False
2  False  False  False

In [40]:
df.notnull()

   first  last  email
0   True  True   True
1   True  True   True
2   True  True   True

In [44]:
df['age']= [24,None,34]

In [45]:
df

      first       last                email   age
0     corey    schafer      corey@gmail.com  24.0
1    sophie    muthoni    muthoni@gmail.com   NaN
2  cristian  rodriguez  rodriguez@gmail.com  34.0

In [46]:
df.notnull()

   first  last  email    age
0   True  True   True   True
1   True  True   True  False
2   True  True   True   True

In [47]:
df.fillna(0)

      first       last                email   age
0     corey    schafer      corey@gmail.com  24.0
1    sophie    muthoni    muthoni@gmail.com   0.0
2  cristian  rodriguez  rodriguez@gmail.com  34.0

In [48]:
df.fillna(1)

      first       last                email   age
0     corey    schafer      corey@gmail.com  24.0
1    sophie    muthoni    muthoni@gmail.com   1.0
2  cristian  rodriguez  rodriguez@gmail.com  34.0

In [49]:
df.loc[[0,2]]

      first       last                email   age
0     corey    schafer      corey@gmail.com  24.0
2  cristian  rodriguez  rodriguez@gmail.com  34.0

In [50]:
df.loc[0:2]

      first       last                email   age
0     corey    schafer      corey@gmail.com  24.0
1    sophie    muthoni    muthoni@gmail.com   NaN
2  cristian  rodriguez  rodriguez@gmail.com  34.0

In [51]:
df

      first       last                email   age
0     corey    schafer      corey@gmail.com  24.0
1    sophie    muthoni    muthoni@gmail.com   NaN
2  cristian  rodriguez  rodriguez@gmail.com  34.0

In [52]:
df.dropna()

      first       last                email   age
0     corey    schafer      corey@gmail.com  24.0
2  cristian  rodriguez  rodriguez@gmail.com  34.0

In [54]:
df

      first       last                email   age
0     corey    schafer      corey@gmail.com  24.0
1    sophie    muthoni    muthoni@gmail.com   NaN
2  cristian  rodriguez  rodriguez@gmail.com  34.0

In [55]:
df.dropna(inplace=True)

In [56]:
df

      first       last                email   age
0     corey    schafer      corey@gmail.com  24.0
2  cristian  rodriguez  rodriguez@gmail.com  34.0

In [57]:
df['age'].astype(int)

0    24
2    34
Name: age, dtype: int64

In [59]:
df['age'].dropna()

0    24.0
2    34.0
Name: age, dtype: float64