In [2]:
import pandas as pd

In [3]:
people = {
    "first":["corey","sophie", "cristian"],
    "last":["schafer","muthoni","rodriguez"],
    "email":["corey@gmail.com","muthoni@gmail.com","rodriguez@gmail.com"]
}

In [4]:
df = pd.DataFrame(people)

In [5]:
df

      first       last                email
0     corey    schafer      corey@gmail.com
1    sophie    muthoni    muthoni@gmail.com
2  cristian  rodriguez  rodriguez@gmail.com

In [6]:
df.head()

      first       last                email
0     corey    schafer      corey@gmail.com
1    sophie    muthoni    muthoni@gmail.com
2  cristian  rodriguez  rodriguez@gmail.com

In [7]:
df.tail()

      first       last                email
0     corey    schafer      corey@gmail.com
1    sophie    muthoni    muthoni@gmail.com
2  cristian  rodriguez  rodriguez@gmail.com

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   first   3 non-null      str
 1   last    3 non-null      str
 2   email   3 non-null      str
dtypes: str(3)
memory usage: 204.0 bytes

In [9]:
df.describe()

        first     last            email
count       3        3                3
unique      3        3                3
top     corey  schafer  corey@gmail.com
freq        1        1                1

In [10]:
df1 = pd.DataFrame({
    'age': [25, 30, 35]
})

df1.describe()

        age
count   3.0
mean   30.0
std     5.0
min    25.0
25%    27.5
50%    30.0
75%    32.5
max    35.0

## Why `df.describe()` Shows This Output for Your Data

Your DataFrame contains **text (string) columns**, so `describe()` gives **categorical statistics instead of numeric ones**.

---

## What Your Output Means

| Statistic | Meaning |
|------------|----------|
| **count** | Number of non-missing values |
| **unique** | Number of distinct values |
| **top** | Most frequent value (mode) |
| **freq** | How many times the most common value appears |

---

## Your Result Explained

In [11]:
df.sort_values(by='last')

      first       last                email
1    sophie    muthoni    muthoni@gmail.com
2  cristian  rodriguez  rodriguez@gmail.com
0     corey    schafer      corey@gmail.com

In [12]:
#sorting by multiple columns

In [13]:
df.sort_values(['first','last'])

      first       last                email
0     corey    schafer      corey@gmail.com
2  cristian  rodriguez  rodriguez@gmail.com
1    sophie    muthoni    muthoni@gmail.com

## why would we want to sort by multiple columns:
### 1. Better grouping + ordering (Department → Salary)

### 2. Makes patterns visible eg: Students in same class ordered by performance

### 3. Essential for ranking within groups

### NB: sort_values always sort in ascending order unless you explicitly set ascending to false -> ascending=False

In [14]:
finance_df = pd.DataFrame({
    "name": ["Alice", "Bob", "Charlie", "David", "Eva", "Frank", "Grace", "Helen"],
    "department": ["HR", "IT", "IT", "HR", "Finance", "Finance", "IT", "HR"],
    "salary": [50000, 80000, 75000, 52000, 90000, 87000, 78000, 51000],
    "age": [25, 30, 28, 35, 40, 38, 27, 29]
})

In [15]:
finance_df

      name department  salary  age
0    Alice         HR   50000   25
1      Bob         IT   80000   30
2  Charlie         IT   75000   28
3    David         HR   52000   35
4      Eva    Finance   90000   40
5    Frank    Finance   87000   38
6    Grace         IT   78000   27
7    Helen         HR   51000   29

In [16]:
#sort by department in ascending order but salary descending order we look for the highest to lowest paid in all departments
finance_df.sort_values(['department','salary'],ascending=[True,False])

      name department  salary  age
4      Eva    Finance   90000   40
5    Frank    Finance   87000   38
3    David         HR   52000   35
7    Helen         HR   51000   29
0    Alice         HR   50000   25
1      Bob         IT   80000   30
6    Grace         IT   78000   27
2  Charlie         IT   75000   28

In [17]:
df['last']

0      schafer
1      muthoni
2    rodriguez
Name: last, dtype: str

In [18]:
df[['first','last']]

      first       last
0     corey    schafer
1    sophie    muthoni
2  cristian  rodriguez

In [19]:
df.loc[0,'last']

'schafer'

In [20]:
df.loc[0]

first              corey
last             schafer
email    corey@gmail.com
Name: 0, dtype: str

In [21]:
df.loc[0,'last']

'schafer'

In [22]:
df['first']

0       corey
1      sophie
2    cristian
Name: first, dtype: str

In [23]:
df.dtypes

first    str
last     str
email    str
dtype: object

In [25]:
IT = (finance_df['department'] == 'IT')

In [26]:
finance_df.loc[finance_df['department'] == 'IT']

      name department  salary  age
1      Bob         IT   80000   30
2  Charlie         IT   75000   28
6    Grace         IT   78000   27

In [31]:
finance_df.columns

Index(['name', 'department', 'salary', 'age'], dtype='str')

In [32]:
finance_df['department']

0         HR
1         IT
2         IT
3         HR
4    Finance
5    Finance
6         IT
7         HR
Name: department, dtype: str

In [33]:
finance_df.loc[1,'department']

'IT'

In [28]:
finance_df

      name department  salary  age
0    Alice         HR   50000   25
1      Bob         IT   80000   30
2  Charlie         IT   75000   28
3    David         HR   52000   35
4      Eva    Finance   90000   40
5    Frank    Finance   87000   38
6    Grace         IT   78000   27
7    Helen         HR   51000   29