In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('stack-overflow-data25/survey_results_public.csv', low_memory=False)
# df = pd.read_csv('stack-overflow-data25/survey_results_public.csv', low_memory=False, index_col='ResponseId')

In [3]:
df

,ResponseId,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,...,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
0,1,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,"Caring for dependents (children, elderly, etc.)",8.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,Vertex AI,NaN,NaN,NaN,ChatGPT,NaN,When I don’t trust AI’s answers,"Troubleshooting, profiling, debugging",61256.0,10.0
1,2,I am a developer by profession,25-34 years old,"Associate degree (A.A., A.S., etc.)",Employed,NaN,2.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,All skills. AI is a flop.,104413.0,9.0
2,3,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Independent contractor, freelancer, or self-em...",None of the above,10.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,ChatGPT;Claude Code;GitHub Copilot;Google Gemini,NaN,When I don’t trust AI’s answers;When I want to...,"Understand how things actually work, problem s...",53061.0,8.0
3,4,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,4.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,ChatGPT;Claude Code,NaN,When I don’t trust AI’s answers;When I want to...,NaN,36197.0,6.0
4,5,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...","Caring for dependents (children, elderly, etc.)",21.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers,"critical thinking, the skill to define the tas...",60000.0,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49186,49187,I code primarily as a hobby,18-24 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49187,49188,I am a developer by profession,45-54 years old,Some college/university study without earning ...,Employed,"Caring for dependents (children, elderly, etc.)",25.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools req...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49188,49189,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,None of the above,17.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0
49189,49190,I am a developer by profession,25-34 years old,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)","Independent contractor, freelancer, or self-em...",None of the above,2.0,"Yes, I am not new to coding but am learning ne...",Videos (not associated with specific online co...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49190,49191,"I am not primarily a developer, but I write co...",18-24 years old,Some college/university study without earning ...,Student,Attending school (full-time),NaN,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
df.head()

,ResponseId,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,...,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
0,1,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,"Caring for dependents (children, elderly, etc.)",8.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,Vertex AI,NaN,NaN,NaN,ChatGPT,NaN,When I don’t trust AI’s answers,"Troubleshooting, profiling, debugging",61256.0,10.0
1,2,I am a developer by profession,25-34 years old,"Associate degree (A.A., A.S., etc.)",Employed,NaN,2.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,All skills. AI is a flop.,104413.0,9.0
2,3,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Independent contractor, freelancer, or self-em...",None of the above,10.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,ChatGPT;Claude Code;GitHub Copilot;Google Gemini,NaN,When I don’t trust AI’s answers;When I want to...,"Understand how things actually work, problem s...",53061.0,8.0
3,4,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,4.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,ChatGPT;Claude Code,NaN,When I don’t trust AI’s answers;When I want to...,NaN,36197.0,6.0
4,5,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...","Caring for dependents (children, elderly, etc.)",21.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers,"critical thinking, the skill to define the tas...",60000.0,7.0

In [5]:
df.shape

(49191, 172)

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 49191 entries, 0 to 49190
Columns: 172 entries, ResponseId to JobSat
dtypes: float64(52), int64(1), str(119)
memory usage: 64.6 MB

In [7]:
pd.set_option('display.max_columns',172)
pd.set_option('display.max_rows',172)

In [8]:
schema_df = pd.read_csv('stack-overflow-data25/survey_results_schema.csv', index_col='qname')

In [9]:
schema_df

,qid,question,type,sub,sq_id
qname,,,,,
TechEndorse_1,QID18,What attracts you to a technology or causes yo...,RO,AI integration or AI Agent capabilities,1.0
TechEndorse_2,QID18,What attracts you to a technology or causes yo...,RO,Easy-to-use API,2.0
TechEndorse_3,QID18,What attracts you to a technology or causes yo...,RO,Robust and complete API,3.0
TechEndorse_4,QID18,What attracts you to a technology or causes yo...,RO,Customizable and manageable codebase,4.0
TechEndorse_5,QID18,What attracts you to a technology or causes yo...,RO,Reputation for quality,5.0
TechEndorse_6,QID18,What attracts you to a technology or causes yo...,RO,Connected to an open-source project,6.0
TechEndorse_7,QID18,What attracts you to a technology or causes yo...,RO,Good brand and public image,7.0
TechEndorse_8,QID18,What attracts you to a technology or causes yo...,RO,Reliability and low latency,8.0
TechEndorse_9,QID18,What attracts you to a technology or causes yo...,RO,Costs are manageable,9.0
TechEndorse_13,QID18,What attracts you to a technology or causes yo...,RO,Other (please specify):,10.0
TechEndorse_13_TEXT,QID18,What attracts you to a technology or causes yo...,RO,Other (please specify): - Text,13.0
TechOppose_1,QID19,What would turn you off or cause you to reject...,RO,Lack of AI or AI agents,1.0
TechOppose_2,QID19,What would turn you off or cause you to reject...,RO,Poor usability,2.0
TechOppose_3,QID19,What would turn you off or cause you to reject...,RO,Lack of or sub-par API,3.0
TechOppose_5,QID19,What would turn you off or cause you to reject...,RO,Inefficient or time-costly,4.0
TechOppose_7,QID19,What would turn you off or cause you to reject...,RO,Prohibitive pricing,5.0
TechOppose_9,QID19,What would turn you off or cause you to reject...,RO,Security or privacy concerns,6.0
TechOppose_11,QID19,What would turn you off or cause you to reject...,RO,Availability of better alternatives,7.0
TechOppose_13,QID19,What would turn you off or cause you to reject...,RO,Outdated or obsolete technology or features,8.0
TechOppose_16,QID19,What would turn you off or cause you to reject...,RO,Ethical concerns,9.0
TechOppose_15,QID19,What would turn you off or cause you to reject...,RO,Other (please specify):,10.0
TechOppose_15_TEXT,QID19,What would turn you off or cause you to reject...,RO,Other (please specify): - Text,15.0
JobSatPoints_1,QID27,Rank the following attributes of your current ...,RO,Control over the level of quality in projects,1.0
JobSatPoints_2,QID27,Rank the following attributes of your current ...,RO,Autonomy and trust to manage your own tasks,2.0
JobSatPoints_16,QID27,Rank the following attributes of your current ...,RO,You like your manager,3.0
JobSatPoints_3,QID27,Rank the following attributes of your current ...,RO,Collaboration and support from a team,4.0
JobSatPoints_4,QID27,Rank the following attributes of your current ...,RO,Expert mentors,5.0
JobSatPoints_5,QID27,Rank the following attributes of your current ...,RO,Opportunities to mentor and lead junior-level ...,6.0
JobSatPoints_6,QID27,Rank the following attributes of your current ...,RO,Developing specialized expertise,7.0
JobSatPoints_7,QID27,Rank the following attributes of your current ...,RO,Solving real-world problems,8.0
JobSatPoints_8,QID27,Rank the following attributes of your current ...,RO,Job stability and career growth with a single ...,9.0
JobSatPoints_9,QID27,Rank the following attributes of your current ...,RO,Innovation through solving challenging and com...,10.0
JobSatPoints_10,QID27,Rank the following attributes of your current ...,RO,Working with new technologies and tools,11.0
JobSatPoints_11,QID27,Rank the following attributes of your current ...,RO,Competitive pay and benefits,12.0
JobSatPoints_13,QID27,Rank the following attributes of your current ...,RO,Recognition from peers for your work,13.0
JobSatPoints_14,QID27,Rank the following attributes of your current ...,RO,Recognition from leadership for your work,14.0
JobSatPoints_15,QID27,Rank the following attributes of your current ...,RO,Other (please specify):,15.0
JobSatPoints_15_TEXT,QID27,Rank the following attributes of your current ...,RO,Other (please specify): - Text,15.0
SO_Actions_1,QID76,"When visiting Stack Overflow, which following ...",RO,Browse content related to Q&A posts I recently...,1.0
SO_Actions_16,QID76,"When visiting Stack Overflow, which following ...",RO,Read and/or vote on comments for a Question or...,2.0
SO_Actions_3,QID76,"When visiting Stack Overflow, which following ...",RO,Bookmark posts to look at later,3.0
SO_Actions_4,QID76,"When visiting Stack Overflow, which following ...",RO,"Directly open a Q&A post via search, documenta...",4.0
SO_Actions_5,QID76,"When visiting Stack Overflow, which following ...",RO,Ask a question,5.0
SO_Actions_6,QID76,"When visiting Stack Overflow, which following ...",RO,Answer a question,6.0
SO_Actions_9,QID76,"When visiting Stack Overflow, which following ...",RO,Comment on Q&A posts,7.0
SO_Actions_7,QID76,"When visiting Stack Overflow, which following ...",RO,Upvote/Downvote Q&A posts,8.0
SO_Actions_10,QID76,"When visiting Stack Overflow, which following ...",RO,Use discussion or chat feature,9.0
SO_Actions_15,QID76,"When visiting Stack Overflow, which following ...",RO,Other (write in):,10.0
SO_Actions_15_TEXT,QID76,"When visiting Stack Overflow, which following ...",RO,Other (write in): - Text,15.0
MainBranch,QID3,Are you someone who writes code? Please select...,MC,NaN,NaN
Age,QID4,What is your age?,MC,NaN,NaN
EdLevel,QID9,Which of the following best describes the high...,MC,NaN,NaN
Employment,QID7,Which of the following best describes your cur...,MC,NaN,NaN
EmploymentAddl,QID8,Which of the following <strong>additional</str...,MC,NaN,NaN
WorkExp,QID14,How many years of professional work experience...,TE,NaN,NaN
LearnCodeChoose,QID10,Did you begin learning to code or learn a new ...,MC,NaN,NaN
LearnCode,QID11,How did you learn to code in the past year? Se...,MC,NaN,NaN
LearnCodeAI,QID12,Did you spend time in the last year learning A...,MC,NaN,NaN
AILearnHow,QID32,How did you learn to code for AI in the past y...,MC,NaN,NaN
YearsCode,QID13,"Including any education, how many years have y...",TE,NaN,NaN
DevType,QID15,Which of the following describes your current ...,MC,NaN,NaN
OrgSize,QID16,Approximately how many people are employed by ...,MC,NaN,NaN
ICorPM,QID23,Are you an individual contributor or people ma...,MC,NaN,NaN
RemoteWork,QID24,Which best describes your current work situation?,MC,NaN,NaN
PurchaseInfluence,QID17,Have you <strong>influenced or endorsed</stron...,MC,NaN,NaN
TechEndorseIntro,QID33,When you&rsquo;re in a position to <strong>inf...,MC,NaN,NaN
Industry,QID25,What industry do you work for in?,MC,NaN,NaN
JobSat,QID26,How satisfied are you in your current professi...,MC,NaN,NaN
AIThreat,QID28,Do you believe AI is a threat to your current ...,MC,NaN,NaN
NewRole,QID29,Have you considered a career change or transit...,MC,NaN,NaN
ToolCountWork,QID30,"For your <b>primary work role</b> (student, de...",TE,NaN,NaN
ToolCountPersonal,QID31,<b></b>For your <b>side projects or other pers...,TE,NaN,NaN
Country,QID20,Where do you live?,MC,NaN,NaN
Currency,QID21,Which currency do you use day-to-day? If your ...,MC,NaN,NaN
CompTotal,QID22,What is your current total <b>annual</b> compe...,TE,NaN,NaN
LanguageChoice,QID44,"Did you work with programming, scripting and m...",MC,NaN,NaN
Language,QID34,"Which <b>programming, scripting, and markup la...",Matrix,NaN,NaN
LanguagesHaveEntry,QID51,Was the programming language you use not liste...,TE,NaN,NaN
LanguagesWantEntry,QID52,Was the programming language you want to use n...,TE,NaN,NaN
DatabaseChoice,QID45,Did you work with database environments in the...,MC,NaN,NaN
Database,QID35,Which <b>database environments </b>have you do...,Matrix,NaN,NaN
DatabaseHaveEntry,QID54,Was the database environment you use not liste...,TE,NaN,NaN
DatabaseWantEntry,QID55,Was the database environment you want to use n...,TE,NaN,NaN
PlatformChoice,QID46,"Did you work with cloud platforms, containeriz...",MC,NaN,NaN
Platform,QID36,"Which <b>cloud platforms, containerization/orc...",Matrix,NaN,NaN
PlatformHaveEntry,QID56,"Was the cloud platforms, containerization/orch...",TE,NaN,NaN
PlatformWantEntry,QID57,"Was the cloud platforms, containerization/orch...",TE,NaN,NaN
WebframeChoice,QID47,Did you work with web frameworks and web techn...,MC,NaN,NaN
Webframe,QID37,Which <b>web frameworks and web technologies</...,Matrix,NaN,NaN
WebframeHaveEntry,QID58,Were the web frameworks and web technologies y...,TE,NaN,NaN
WebframeWantEntry,QID59,Were the web frameworks and web technologies y...,TE,NaN,NaN
DevEnvsChoice,QID48,Did you work with development environments or ...,MC,NaN,NaN
DevEnvs,QID38,Which <strong>development environments and AI-...,Matrix,NaN,NaN
DevEnvHaveEntry,QID60,Was the developer environment or AI-enabled co...,TE,NaN,NaN
DevEnvWantEntry,QID61,Was the developer environment or AI-enabled co...,TE,NaN,NaN
SOTags,QID39,Which rising technology of the added as <b>new...,Matrix,NaN,NaN
SOTagsHaveEntry,QID62,Was the new tag on Stack Overflow (i.e. added ...,TE,NaN,NaN
SOTagsWant Entry,QID63,Was the new tag on Stack Overflow (i.e. added ...,TE,NaN,NaN
OpSys,QID40,What is the primary <b>operating system</b> in...,Matrix,NaN,NaN
OfficeStackAsync,QID41,Which <b>collaborative work management and/or ...,Matrix,NaN,NaN
OfficeStackHaveEntry,QID64,Was the collaborative work management and/or c...,TE,NaN,NaN
OfficeStackWantEntry,QID65,Was the collaborative work management and/or c...,TE,NaN,NaN
CommPlatform,QID42,Which <b>community platforms</b> have you util...,Matrix,NaN,NaN
CommPlatformHaveEntr,QID66,Was the community platform you use not listed ...,TE,NaN,NaN
CommPlatformWantEntr,QID67,Was the community platform you want to use not...,TE,NaN,NaN
AIModelsChoice,QID50,Did you utilize or integrate specific Large La...,MC,NaN,NaN
AIModels,QID43,Which <b>LLM models for AI tools</b> have you ...,Matrix,NaN,NaN
AIModelsHaveEntry,QID68,Was the LLM model for AI tools you use not lis...,TE,NaN,NaN
AIModelsWantEntry,QID69,Was the LLM model for AI tools you want to use...,TE,NaN,NaN
SOAccount,QID72,Do you have a Stack Overflow account?,MC,NaN,NaN
SOVisitFreq,QID70,How frequently would you say you visit Stack O...,MC,NaN,NaN
SODuration,QID71,How long have you used Stack Overflow?,MC,NaN,NaN
SOPartFreq,QID73,How frequently would you say you participate i...,MC,NaN,NaN
SO_Dev_Content,QID75,"Whether it be to solve a problem, for career g...",MC,NaN,NaN
SOComm,QID77,Do you consider yourself a member of the Stack...,MC,NaN,NaN
SOFriction,QID97,"When you visit Stack Overflow, how often is it...",MC,NaN,NaN
AISelect,QID78,Do you currently use AI tools in your developm...,MC,NaN,NaN
AISent,QID79,How favorable is your stance on using AI tools...,MC,NaN,NaN
AIAcc,QID80,How much do you trust the accuracy of the outp...,MC,NaN,NaN
AIComplex,QID81,How well do the AI tools you use in your devel...,MC,NaN,NaN
AITool,QID82,Which parts of your development workflow are y...,Matrix,NaN,NaN
AIFrustration,QID99,"When using AI tools, which of the following pr...",MC,NaN,NaN
AIExplain,QID84,"In your own words, is &quot;vibe coding&quot; ...",TE,NaN,NaN
AIAgents,QID85,Are you using AI agents in your work (developm...,MC,NaN,NaN
AIAgentChange,QID83,Have AI tools or AI agents changed how you com...,MC,NaN,NaN
AIAgent_Uses,QID86,What industry purposes or specific tasks are y...,MC,NaN,NaN
AgentUsesGeneral,QID106,,MC,NaN,NaN
AIAgentImpact,QID87,To what extent do you agree with the following...,Matrix,NaN,NaN
AIAgentChallenges,QID88,To what extent do you agree with the following...,Matrix,NaN,NaN
AIAgentKnowledge,QID89,You indicated you use or develop AI agents as ...,MC,NaN,NaN
AIAgentKnowWrite,QID107,Was the tool or tools for AI agent orchestrati...,TE,NaN,NaN
AIAgentOrchestration,QID90,You indicated you use or develop AI agents as ...,MC,NaN,NaN
AIAgentOrchWrite,QID102,Was the tool or tools for AI agent orchestrati...,TE,NaN,NaN
AIAgentObserveSecure,QID91,You indicated you use or develop AI agents as ...,MC,NaN,NaN
AIAgentObsWrite,QID103,Was the tool or tools for AI agent observabili...,TE,NaN,NaN
AIAgentExternal,QID92,You indicated you use or develop AI agents as ...,MC,NaN,NaN
AIAgentExtWrite,QID104,"Was the out-of-the-box agents, copilots or ass...",TE,NaN,NaN
AIHuman,QID100,"In the future, if AI can do most coding tasks,...",MC,NaN,NaN
AIOpen,QID93,"Looking ahead 3–5 years, what skills do you be...",TE,NaN,NaN

In [10]:
df.head()

,ResponseId,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,AILearnHow,YearsCode,DevType,OrgSize,ICorPM,RemoteWork,PurchaseInfluence,TechEndorseIntro,TechEndorse_1,TechEndorse_2,TechEndorse_3,TechEndorse_4,TechEndorse_5,TechEndorse_6,TechEndorse_7,TechEndorse_8,TechEndorse_9,TechEndorse_13,TechEndorse_13_TEXT,TechOppose_1,TechOppose_2,TechOppose_3,TechOppose_5,TechOppose_7,TechOppose_9,TechOppose_11,TechOppose_13,TechOppose_16,TechOppose_15,TechOppose_15_TEXT,Industry,JobSatPoints_1,JobSatPoints_2,JobSatPoints_3,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,JobSatPoints_13,JobSatPoints_14,JobSatPoints_15,JobSatPoints_16,JobSatPoints_15_TEXT,AIThreat,NewRole,ToolCountWork,ToolCountPersonal,Country,Currency,CompTotal,LanguageChoice,LanguageHaveWorkedWith,LanguageWantToWorkWith,LanguageAdmired,LanguagesHaveEntry,LanguagesWantEntry,DatabaseChoice,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,DatabaseAdmired,DatabaseHaveEntry,DatabaseWantEntry,PlatformChoice,PlatformHaveWorkedWith,PlatformWantToWorkWith,PlatformAdmired,PlatformHaveEntry,PlatformWantEntry,WebframeChoice,WebframeHaveWorkedWith,WebframeWantToWorkWith,WebframeAdmired,WebframeHaveEntry,WebframeWantEntry,DevEnvsChoice,DevEnvsHaveWorkedWith,DevEnvsWantToWorkWith,DevEnvsAdmired,DevEnvHaveEntry,DevEnvWantEntry,SOTagsHaveWorkedWith,SOTagsWantToWorkWith,SOTagsAdmired,SOTagsHaveEntry,SOTagsWant Entry,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackAsyncAdmired,OfficeStackHaveEntry,OfficeStackWantEntry,CommPlatformHaveWorkedWith,CommPlatformWantToWorkWith,CommPlatformAdmired,CommPlatformHaveEntr,CommPlatformWantEntr,AIModelsChoice,AIModelsHaveWorkedWith,AIModelsWantToWorkWith,AIModelsAdmired,AIModelsHaveEntry,AIModelsWantEntry,SOAccount,SOVisitFreq,SODuration,SOPartFreq,SO_Dev_Content,SO_Actions_1,SO_Actions_16,SO_Actions_3,SO_Actions_4,SO_Actions_5,SO_Actions_6,SO_Actions_9,SO_Actions_7,SO_Actions_10,SO_Actions_15,SO_Actions_15_TEXT,SOComm,SOFriction,AISelect,AISent,AIAcc,AIComplex,AIToolCurrently partially AI,AIToolDon't plan to use AI for this task,AIToolPlan to partially use AI,AIToolPlan to mostly use AI,AIToolCurrently mostly AI,AIFrustration,AIExplain,AIAgents,AIAgentChange,AIAgent_Uses,AgentUsesGeneral,AIAgentImpactSomewhat agree,AIAgentImpactNeutral,AIAgentImpactSomewhat disagree,AIAgentImpactStrongly agree,AIAgentImpactStrongly disagree,AIAgentChallengesNeutral,AIAgentChallengesSomewhat disagree,AIAgentChallengesStrongly agree,AIAgentChallengesSomewhat agree,AIAgentChallengesStrongly disagree,AIAgentKnowledge,AIAgentKnowWrite,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
0,1,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,"Caring for dependents (children, elderly, etc.)",8.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,14.0,"Developer, mobile",20 to 99 employees,People manager,Remote,"Yes, I influenced the purchase of a substantia...",Work,10.0,7.0,9.0,6.0,3.0,11.0,12.0,1.0,8.0,14.0,NaN,15.0,7.0,8.0,12.0,11.0,1.0,6.0,13.0,3.0,16.0,NaN,Fintech,3.0,1.0,4.0,9.0,5.0,10.0,12.0,11.0,2.0,6.0,7.0,13.0,14.0,15.0,8.0,NaN,I'm not sure,I have neither consider or transitioned into a...,7.0,3.0,Ukraine,EUR European Euro,52800.0,Yes,Bash/Shell (all shells);Dart;SQL,Dart,Dart,NaN,NaN,Yes,Cloud Firestore;PostgreSQL,NaN,NaN,NaN,NaN,Yes,Amazon Web Services (AWS);Cloudflare;Firebase;...,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,Android Studio;Notepad++;Visual Studio;Visual ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Windows;MacOS;Android,Windows;MacOS;Android;iOS;iPadOS,Confluence;GitHub;GitLab;Jira;Markdown File,Markdown File,Markdown File,NaN,NaN,"Stack Overflow;Reddit;GitHub (public projects,...",NaN,NaN,NaN,NaN,Yes,openAI GPT (chatbot models);openAI Image gener...,NaN,NaN,NaN,NaN,Yes,A few times per week,Between 5 and 10 years,I have never participated in Q&A on Stack Over...,NaN,1.0,NaN,6.0,2.0,3.0,7.0,8.0,9.0,11.0,15.0,NaN,Neutral,"Rarely, almost never","Yes, I use AI tools monthly or infrequently",Indifferent,Neither trust nor distrust,Bad at handling complex tasks,Learning about a codebase;Writing code;Search ...,Project planning;Deployment and monitoring;Lea...,Documenting code;Debugging or fixing code;Test...,NaN,NaN,"AI solutions that are almost right, but not quite",No,"Yes, I use AI agents at work monthly or infreq...",Not at all or minimally,Software engineering,NaN,AI agents have increased my productivity.;AI a...,AI agents have helped me automate repetitive t...,NaN,NaN,NaN,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,The cost of using certain AI agent platforms i...,NaN,NaN,NaN,NaN,Vertex AI,NaN,NaN,NaN,ChatGPT,NaN,When I don’t trust AI’s answers,"Troubleshooting, profiling, debugging",61256.0,10.0
1,2,I am a developer by profession,25-34 years old,"Associate degree (A.A., A.S., etc.)",Employed,NaN,2.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,10.0,"Developer, back-end",500 to 999 employees,Individual contributor,"Hybrid (some in-person, leans heavy to flexibi...",No,Personal Project,13.0,1.0,2.0,9.0,4.0,3.0,12.0,5.0,7.0,14.0,NaN,14.0,1.0,13.0,10.0,9.0,3.0,4.0,2.0,5.0,15.0,NaN,Retail and Consumer Services,10.0,8.0,3.0,9.0,12.0,1.0,6.0,2.0,11.0,4.0,7.0,13.0,14.0,15.0,5.0,NaN,I'm not sure,I have transitioned into a new career and/or i...,6.0,5.0,Netherlands,EUR European Euro,90000.0,Yes,Java,Java;Python;Swift,Java,NaN,NaN,Yes,Dynamodb;MongoDB,Dynamodb;MongoDB,Dynamodb;MongoDB,NaN,NaN,Yes,Amazon Web Services (AWS);Datadog;Docker;Homeb...,Amazon Web Services (AWS);Datadog;Docker;Homeb...,Amazon Web Services (AWS);Datadog;Docker;Homeb...,NaN,NaN,Yes,Spring Boot,Spring Boot,Spring Boot,NaN,NaN,Yes,IntelliJ IDEA;PyCharm;Visual Studio Code;Xcode,IntelliJ IDEA;PyCharm;Visual Studio Code;Xcode,IntelliJ IDEA;PyCharm;Visual Studio Code;Xcode,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Windows;MacOS;iOS;iPadOS,MacOS,Confluence;GitHub;Jira,Confluence;GitHub;Jira,Confluence;GitHub;Jira,NaN,NaN,Stack Overflow;Discord;Reddit;Dev.to;Hacker Ne...,Stack Overflow;Discord;Reddit;Dev.to;Hacker Ne...,Stack Overflow;Discord;Reddit;Dev.to;Hacker Ne...,NaN,NaN,Yes,openAI GPT (chatbot models),openAI GPT (chatbot models),openAI GPT (chatbot models),NaN,NaN,Not sure/can't remember,Multiple times per day,Between 10 and 15 years,"Infrequently, less than once per year",Chat (people);Message Boards;Long-form article...,6.0,NaN,5.0,8.0,2.0,4.0,9.0,10.0,11.0,15.0,NaN,"Yes, somewhat",About half of the time,"Yes, I use AI tools weekly",Indifferent,Neither trust nor distrust,Bad at handling complex tasks,Learning new concepts or technologies,Learning about a codebase;Project planning;Com...,Writing code;Documenting code;Debugging or fix...,NaN,NaN,"AI solutions that are almost right, but not qu...",No,"No, and I don't plan to",Not at all or minimally,NaN,NaN,NaN,NaN,NaN,NaN,NaN,It takes significant time and effort to learn ...,NaN,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,All skills. AI is a flop.,104413.0,9.0
2,3,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Independent contractor, freelancer, or self-em...",None of the above,10.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Technical ...,12.0,"Developer, front-end",NaN,NaN,NaN,No,Work,12.0,2.0,3.0,7.0,5.0,10.0,13.0,1.0,4.0,14.0,NaN,8.0,1.0,2.0,12.0,13.0,3.0,9.0,4.0,11.0,15.0,NaN,Software Development,9.0,6.0,7.0,11.0,8.0,12.0,1.0,5.0,2.0,4.0,3.0,13.0,14.0,15.0,10.0,NaN,No,I have transitioned into a new career and/or i...,3.0,3.0,Ukraine,UAH Ukrainian hryvnia,2214000.0,Yes,Dart;HTML/CSS;JavaScript;TypeScript,Dart;HTML/CSS;JavaScript;TypeScript,Dart;HTML/CSS;JavaScript;TypeScript,NaN,NaN,Yes,MongoDB;MySQL;PostgreSQL,Firebase Realtime Database;MongoDB,MongoDB,NaN,NaN,Yes,Datadog;Firebase;npm;pnpm,Amazon Web Services (AWS);Firebase;npm;pnpm;Vite,Firebase;npm;pnpm,NaN,NaN,Yes,Next.js;Node.js;React,Next.js;Node.js;React,Next.js;Node.js;React,NaN,Solid.js,Yes,Visual Studio Code,Visual Studio Code;Windsurf,Visual Studio Code,NaN,NaN,Google Gemini,Google Gemini;Shadcn/ui,Google Gemini,NaN,NaN,MacOS;Android,MacOS,GitHub;GitLab;Jira,GitHub;GitLab;Jira,GitHub;GitLab;Jira,NaN,NaN,Stack Overflow;Discord;Dev.to;X;YouTube;LinkedIn,Stack Overflow;Discord;Dev.to;X;YouTube;LinkedIn,Stack Overflow;Discord;Dev.to;X;YouTube;LinkedIn,NaN,NaN,Yes,Gemini (Flash general purpose models);openAI G...,Gemini (Flash general purpose models);Gemini (...,Gemini (Flash general purpose models);openAI G...,NaN,NaN,Not sure/can't remember,A few times per week,Between 5 and 10 years,"Infrequently, less than once per year",Chat (people);Videos;Lists of recommendations ...,3.0,NaN,4.0,5.0,1.0,2.0,7.0,9.0,11.0,15.0,NaN,Neutral,About half of the time,"Yes, I use AI tools daily",Favorable,Somewhat trust,Neither good or bad at handling complex tasks,Documenting code;Debugging or fixing code;Test...,NaN,Project planning;Committing and reviewing code...,Learning about a codebase;Writing code;Generat...,NaN,"AI solutions that are almost right, but not qu...",No,"Yes, I use AI agents at work weekly","Yes, somewhat",Software engineering,Multi-platform search enablement,AI agents have increased my productivity.;AI a...,AI agents have improved the quality of my code...,AI agents have improved collaboration within m...,NaN,NaN,It takes significant time and effort to learn ...,My company's IT and/or InfoSec teams have stri...,NaN,I am concerned about the accuracy of the infor...,NaN,Redis,NaN,NaN,NaN,NaN,NaN,ChatGPT;Claude Code;GitHub Copilot;Google Gemini,NaN,When I don’t trust AI’s answers;When I want to...,"Understand how things actually work, problem s...",53061.0,8.0
3,4,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,4.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Videos (no...,5.0,"Developer, back-end","10,000 or more employees",Individual contributor,Remote,No,Personal Project,2.0,12.0,6.0,5.0,13.0,3.0,8.0,11.0,7.0,14.0,NaN,10.0,5.0,8.0,4.0,13.0,12.0,2.0,7.0,1.0,15.0,NaN,Retail and Consumer Services,1.0,2.0,4.0,5.0,6.0,7.0,8.0,9.0,10.0,11.0,12.0,13.0,14.0,15.0,3.0,NaN,No,I have neither consider or transitioned into a...,NaN,NaN,Ukraine,EUR European Euro,31200.0,Yes,Java;Kotlin;SQL,Java;Kotlin,Java;Kotlin,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,Amazon Web Services (AWS);Google Cloud,Amazon Web Services (AWS);Google Cloud,Amazon Web Services (AWS);Google Cloud,NaN,NaN,Yes,Spring Boot,Spring Boot,Spring Boot,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Amazon Bedrock,NaN,NaN,NaN,NaN,Windows,Windows;Ubuntu,GitLab;Jira;Miro,GitLab;Jira,GitLab;Jira,NaN,NaN,Stack Overflow;Reddit;YouTube;LinkedIn,"Stack Overflow;Reddit;GitHub (public projects,...",Stack Overflow;Reddit;YouTube;LinkedIn,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,A few times per month or weekly,Between 3 and 5 years,I have never participated in Q&A on Stack Over...,Videos;Chat (bot/AI),1.0,NaN,4.0,5.0,6.0,7.0,8.0,9.0,11.0,15.0,NaN,Neutral,"Rarely, almost never","Yes, I use AI tools weekly",Favorable,Somewhat trust,Bad at handling complex tasks,NaN,Project planning;Documenting code;Testing code...,Learning about a codebase;Writing code;Debuggi...,Search for answers;Generating content or synth...,NaN,"AI solutions that are almost right, but not qu...",NO,"Yes, I use AI agents at work monthly or infreq...",Not at all or minimally,Software engineering,Language processing,AI agents have accelerated my learning about n...,AI agents have increased my productivity.;AI a...,AI agents have helped me automate repetitive t...,NaN,NaN,It takes significant time and effort to learn ...,NaN,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ChatGPT;Claude Code,NaN,When I don’t trust AI’s answers;When I want to...,NaN,36197.0,6.0
4,5,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...","Caring for dependents (children, elderly, etc.)",21.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools for...",Technical documentation (is generated for/by t...,22.0,Engineering manager,NaN,NaN,NaN,"Yes, I endorsed a tool that was open-source an...",Work,6.0,3.0,1.0,9.0,10.0,8.0,7.0,4.0,2.0,14.0,NaN,7.0,13.0,3.0,9.0,12.0,6.0,1.0,8.0,14.0,15.0,NaN,Software Development,9.0,4.0,11.0,13.0,14.0,8.0,6.0,5.0,7.0,2.0,1.0,12.0,10.0,15.0,3.0,NaN,No,I have neither consider or transitioned into a...,4.0,3.0,Ukraine,USD United States dollar,60000.0,Yes,C;C#;C++;Delphi;HTML/CSS;Java;JavaScript;Lua;P...,C#;Java;JavaScript;Python;SQL;TypeScript,C#;Java;JavaScript;Python;SQL;TypeScript,NaN,NaN,Yes,Elasticsearch;Microsoft SQL Server;MySQL;Oracl...,Elasticsearch;Oracle;PostgreSQL,Elasticsearch;Oracle;PostgreSQL,NaN,NaN,Yes,Amazon Web Services (AWS);APT;Docker;Make;Mave...,Amazon Web Services (AWS);APT;Docker;Maven (bu...,Amazon Web Services (AWS);APT;Docker;Maven (bu...,NaN,NaN,Yes,Angular;ASP.NET;ASP.NET Core;Flask;jQuery,Angular;ASP.NET Core;Flask,Angular;ASP.NET Core;Flask,NaN,NaN,Yes,Eclipse;IntelliJ IDEA;Jupyter Notebook/Jupyter...,IntelliJ IDEA;Jupyter Notebook/JupyterLab;Note...,IntelliJ IDEA;Jupyter Notebook/JupyterLab;Note...,NaN,NaN,Large Language Model;Google Gemini,Large Language Model,Large Language Model,NaN,NaN,Windows;iOS,Windows;Ubuntu;Debian,Azure Devops;GitHub;Jira,Azure Devops;GitHub;Jira,Azure Devops;GitHub;Jira,NaN,NaN,Stack Overflow;Stack Exchange;GitHub (public p...,Stack Overflow;Stack Exchange;GitHub (public p...,Stack Overflow;Stack Exchange;GitHub (public p...,NaN,NaN,Yes,openAI GPT (chatbot models),openAI GPT (chatbot models),openAI GPT (chatbot models),NaN,NaN,No,A few times per month or weekly,Between 5 and 10 years,"Infrequently, less than once per year",Long-form articles,1.0,NaN,7.0,4.0,2.0,5.0,10.0,6.0,12.0,15.0,NaN,"No, not really","Rarely, almost never","Yes, I use AI tools weekly",Favorable,Neither trust nor distrust,"Good, but not great at handling complex tasks",Learning about a codebase;Writing code;Debuggi...,Project planning;Documenting code;Testing code...,Generating content or synthetic data,NaN,NaN,"AI solutions that are almost right, but not quite",partly,"No, and I don't plan to","Yes, to a great extent",NaN,NaN,NaN,NaN,NaN,NaN,NaN,Integrating AI agents with my existing tools a...,NaN,I am concerned about the accuracy of the infor...,It takes significant time and effort to learn ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers,"critical thinking, the skill to define the tas...",60000.0,7.0

In [11]:
df.head(10)

,ResponseId,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,AILearnHow,YearsCode,DevType,OrgSize,ICorPM,RemoteWork,PurchaseInfluence,TechEndorseIntro,TechEndorse_1,TechEndorse_2,TechEndorse_3,TechEndorse_4,TechEndorse_5,TechEndorse_6,TechEndorse_7,TechEndorse_8,TechEndorse_9,TechEndorse_13,TechEndorse_13_TEXT,TechOppose_1,TechOppose_2,TechOppose_3,TechOppose_5,TechOppose_7,TechOppose_9,TechOppose_11,TechOppose_13,TechOppose_16,TechOppose_15,TechOppose_15_TEXT,Industry,JobSatPoints_1,JobSatPoints_2,JobSatPoints_3,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,JobSatPoints_13,JobSatPoints_14,JobSatPoints_15,JobSatPoints_16,JobSatPoints_15_TEXT,AIThreat,NewRole,ToolCountWork,ToolCountPersonal,Country,Currency,CompTotal,LanguageChoice,LanguageHaveWorkedWith,LanguageWantToWorkWith,LanguageAdmired,LanguagesHaveEntry,LanguagesWantEntry,DatabaseChoice,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,DatabaseAdmired,DatabaseHaveEntry,DatabaseWantEntry,PlatformChoice,PlatformHaveWorkedWith,PlatformWantToWorkWith,PlatformAdmired,PlatformHaveEntry,PlatformWantEntry,WebframeChoice,WebframeHaveWorkedWith,WebframeWantToWorkWith,WebframeAdmired,WebframeHaveEntry,WebframeWantEntry,DevEnvsChoice,DevEnvsHaveWorkedWith,DevEnvsWantToWorkWith,DevEnvsAdmired,DevEnvHaveEntry,DevEnvWantEntry,SOTagsHaveWorkedWith,SOTagsWantToWorkWith,SOTagsAdmired,SOTagsHaveEntry,SOTagsWant Entry,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackAsyncAdmired,OfficeStackHaveEntry,OfficeStackWantEntry,CommPlatformHaveWorkedWith,CommPlatformWantToWorkWith,CommPlatformAdmired,CommPlatformHaveEntr,CommPlatformWantEntr,AIModelsChoice,AIModelsHaveWorkedWith,AIModelsWantToWorkWith,AIModelsAdmired,AIModelsHaveEntry,AIModelsWantEntry,SOAccount,SOVisitFreq,SODuration,SOPartFreq,SO_Dev_Content,SO_Actions_1,SO_Actions_16,SO_Actions_3,SO_Actions_4,SO_Actions_5,SO_Actions_6,SO_Actions_9,SO_Actions_7,SO_Actions_10,SO_Actions_15,SO_Actions_15_TEXT,SOComm,SOFriction,AISelect,AISent,AIAcc,AIComplex,AIToolCurrently partially AI,AIToolDon't plan to use AI for this task,AIToolPlan to partially use AI,AIToolPlan to mostly use AI,AIToolCurrently mostly AI,AIFrustration,AIExplain,AIAgents,AIAgentChange,AIAgent_Uses,AgentUsesGeneral,AIAgentImpactSomewhat agree,AIAgentImpactNeutral,AIAgentImpactSomewhat disagree,AIAgentImpactStrongly agree,AIAgentImpactStrongly disagree,AIAgentChallengesNeutral,AIAgentChallengesSomewhat disagree,AIAgentChallengesStrongly agree,AIAgentChallengesSomewhat agree,AIAgentChallengesStrongly disagree,AIAgentKnowledge,AIAgentKnowWrite,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
0,1,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,"Caring for dependents (children, elderly, etc.)",8.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,14.0,"Developer, mobile",20 to 99 employees,People manager,Remote,"Yes, I influenced the purchase of a substantia...",Work,10.0,7.0,9.0,6.0,3.0,11.0,12.0,1.0,8.0,14.0,NaN,15.0,7.0,8.0,12.0,11.0,1.0,6.0,13.0,3.0,16.0,NaN,Fintech,3.0,1.0,4.0,9.0,5.0,10.0,12.0,11.0,2.0,6.0,7.0,13.0,14.0,15.0,8.0,NaN,I'm not sure,I have neither consider or transitioned into a...,7.0,3.0,Ukraine,EUR European Euro,52800.0,Yes,Bash/Shell (all shells);Dart;SQL,Dart,Dart,NaN,NaN,Yes,Cloud Firestore;PostgreSQL,NaN,NaN,NaN,NaN,Yes,Amazon Web Services (AWS);Cloudflare;Firebase;...,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,Android Studio;Notepad++;Visual Studio;Visual ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Windows;MacOS;Android,Windows;MacOS;Android;iOS;iPadOS,Confluence;GitHub;GitLab;Jira;Markdown File,Markdown File,Markdown File,NaN,NaN,"Stack Overflow;Reddit;GitHub (public projects,...",NaN,NaN,NaN,NaN,Yes,openAI GPT (chatbot models);openAI Image gener...,NaN,NaN,NaN,NaN,Yes,A few times per week,Between 5 and 10 years,I have never participated in Q&A on Stack Over...,NaN,1.0,NaN,6.0,2.0,3.0,7.0,8.0,9.0,11.0,15.0,NaN,Neutral,"Rarely, almost never","Yes, I use AI tools monthly or infrequently",Indifferent,Neither trust nor distrust,Bad at handling complex tasks,Learning about a codebase;Writing code;Search ...,Project planning;Deployment and monitoring;Lea...,Documenting code;Debugging or fixing code;Test...,NaN,NaN,"AI solutions that are almost right, but not quite",No,"Yes, I use AI agents at work monthly or infreq...",Not at all or minimally,Software engineering,NaN,AI agents have increased my productivity.;AI a...,AI agents have helped me automate repetitive t...,NaN,NaN,NaN,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,The cost of using certain AI agent platforms i...,NaN,NaN,NaN,NaN,Vertex AI,NaN,NaN,NaN,ChatGPT,NaN,When I don’t trust AI’s answers,"Troubleshooting, profiling, debugging",61256.0,10.0
1,2,I am a developer by profession,25-34 years old,"Associate degree (A.A., A.S., etc.)",Employed,NaN,2.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,10.0,"Developer, back-end",500 to 999 employees,Individual contributor,"Hybrid (some in-person, leans heavy to flexibi...",No,Personal Project,13.0,1.0,2.0,9.0,4.0,3.0,12.0,5.0,7.0,14.0,NaN,14.0,1.0,13.0,10.0,9.0,3.0,4.0,2.0,5.0,15.0,NaN,Retail and Consumer Services,10.0,8.0,3.0,9.0,12.0,1.0,6.0,2.0,11.0,4.0,7.0,13.0,14.0,15.0,5.0,NaN,I'm not sure,I have transitioned into a new career and/or i...,6.0,5.0,Netherlands,EUR European Euro,90000.0,Yes,Java,Java;Python;Swift,Java,NaN,NaN,Yes,Dynamodb;MongoDB,Dynamodb;MongoDB,Dynamodb;MongoDB,NaN,NaN,Yes,Amazon Web Services (AWS);Datadog;Docker;Homeb...,Amazon Web Services (AWS);Datadog;Docker;Homeb...,Amazon Web Services (AWS);Datadog;Docker;Homeb...,NaN,NaN,Yes,Spring Boot,Spring Boot,Spring Boot,NaN,NaN,Yes,IntelliJ IDEA;PyCharm;Visual Studio Code;Xcode,IntelliJ IDEA;PyCharm;Visual Studio Code;Xcode,IntelliJ IDEA;PyCharm;Visual Studio Code;Xcode,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Windows;MacOS;iOS;iPadOS,MacOS,Confluence;GitHub;Jira,Confluence;GitHub;Jira,Confluence;GitHub;Jira,NaN,NaN,Stack Overflow;Discord;Reddit;Dev.to;Hacker Ne...,Stack Overflow;Discord;Reddit;Dev.to;Hacker Ne...,Stack Overflow;Discord;Reddit;Dev.to;Hacker Ne...,NaN,NaN,Yes,openAI GPT (chatbot models),openAI GPT (chatbot models),openAI GPT (chatbot models),NaN,NaN,Not sure/can't remember,Multiple times per day,Between 10 and 15 years,"Infrequently, less than once per year",Chat (people);Message Boards;Long-form article...,6.0,NaN,5.0,8.0,2.0,4.0,9.0,10.0,11.0,15.0,NaN,"Yes, somewhat",About half of the time,"Yes, I use AI tools weekly",Indifferent,Neither trust nor distrust,Bad at handling complex tasks,Learning new concepts or technologies,Learning about a codebase;Project planning;Com...,Writing code;Documenting code;Debugging or fix...,NaN,NaN,"AI solutions that are almost right, but not qu...",No,"No, and I don't plan to",Not at all or minimally,NaN,NaN,NaN,NaN,NaN,NaN,NaN,It takes significant time and effort to learn ...,NaN,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,All skills. AI is a flop.,104413.0,9.0
2,3,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Independent contractor, freelancer, or self-em...",None of the above,10.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Technical ...,12.0,"Developer, front-end",NaN,NaN,NaN,No,Work,12.0,2.0,3.0,7.0,5.0,10.0,13.0,1.0,4.0,14.0,NaN,8.0,1.0,2.0,12.0,13.0,3.0,9.0,4.0,11.0,15.0,NaN,Software Development,9.0,6.0,7.0,11.0,8.0,12.0,1.0,5.0,2.0,4.0,3.0,13.0,14.0,15.0,10.0,NaN,No,I have transitioned into a new career and/or i...,3.0,3.0,Ukraine,UAH Ukrainian hryvnia,2214000.0,Yes,Dart;HTML/CSS;JavaScript;TypeScript,Dart;HTML/CSS;JavaScript;TypeScript,Dart;HTML/CSS;JavaScript;TypeScript,NaN,NaN,Yes,MongoDB;MySQL;PostgreSQL,Firebase Realtime Database;MongoDB,MongoDB,NaN,NaN,Yes,Datadog;Firebase;npm;pnpm,Amazon Web Services (AWS);Firebase;npm;pnpm;Vite,Firebase;npm;pnpm,NaN,NaN,Yes,Next.js;Node.js;React,Next.js;Node.js;React,Next.js;Node.js;React,NaN,Solid.js,Yes,Visual Studio Code,Visual Studio Code;Windsurf,Visual Studio Code,NaN,NaN,Google Gemini,Google Gemini;Shadcn/ui,Google Gemini,NaN,NaN,MacOS;Android,MacOS,GitHub;GitLab;Jira,GitHub;GitLab;Jira,GitHub;GitLab;Jira,NaN,NaN,Stack Overflow;Discord;Dev.to;X;YouTube;LinkedIn,Stack Overflow;Discord;Dev.to;X;YouTube;LinkedIn,Stack Overflow;Discord;Dev.to;X;YouTube;LinkedIn,NaN,NaN,Yes,Gemini (Flash general purpose models);openAI G...,Gemini (Flash general purpose models);Gemini (...,Gemini (Flash general purpose models);openAI G...,NaN,NaN,Not sure/can't remember,A few times per week,Between 5 and 10 years,"Infrequently, less than once per year",Chat (people);Videos;Lists of recommendations ...,3.0,NaN,4.0,5.0,1.0,2.0,7.0,9.0,11.0,15.0,NaN,Neutral,About half of the time,"Yes, I use AI tools daily",Favorable,Somewhat trust,Neither good or bad at handling complex tasks,Documenting code;Debugging or fixing code;Test...,NaN,Project planning;Committing and reviewing code...,Learning about a codebase;Writing code;Generat...,NaN,"AI solutions that are almost right, but not qu...",No,"Yes, I use AI agents at work weekly","Yes, somewhat",Software engineering,Multi-platform search enablement,AI agents have increased my productivity.;AI a...,AI agents have improved the quality of my code...,AI agents have improved collaboration within m...,NaN,NaN,It takes significant time and effort to learn ...,My company's IT and/or InfoSec teams have stri...,NaN,I am concerned about the accuracy of the infor...,NaN,Redis,NaN,NaN,NaN,NaN,NaN,ChatGPT;Claude Code;GitHub Copilot;Google Gemini,NaN,When I don’t trust AI’s answers;When I want to...,"Understand how things actually work, problem s...",53061.0,8.0
3,4,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,4.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Videos (no...,5.0,"Developer, back-end","10,000 or more employees",Individual contributor,Remote,No,Personal Project,2.0,12.0,6.0,5.0,13.0,3.0,8.0,11.0,7.0,14.0,NaN,10.0,5.0,8.0,4.0,13.0,12.0,2.0,7.0,1.0,15.0,NaN,Retail and Consumer Services,1.0,2.0,4.0,5.0,6.0,7.0,8.0,9.0,10.0,11.0,12.0,13.0,14.0,15.0,3.0,NaN,No,I have neither consider or transitioned into a...,NaN,NaN,Ukraine,EUR European Euro,31200.0,Yes,Java;Kotlin;SQL,Java;Kotlin,Java;Kotlin,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,Amazon Web Services (AWS);Google Cloud,Amazon Web Services (AWS);Google Cloud,Amazon Web Services (AWS);Google Cloud,NaN,NaN,Yes,Spring Boot,Spring Boot,Spring Boot,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Amazon Bedrock,NaN,NaN,NaN,NaN,Windows,Windows;Ubuntu,GitLab;Jira;Miro,GitLab;Jira,GitLab;Jira,NaN,NaN,Stack Overflow;Reddit;YouTube;LinkedIn,"Stack Overflow;Reddit;GitHub (public projects,...",Stack Overflow;Reddit;YouTube;LinkedIn,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,A few times per month or weekly,Between 3 and 5 years,I have never participated in Q&A on Stack Over...,Videos;Chat (bot/AI),1.0,NaN,4.0,5.0,6.0,7.0,8.0,9.0,11.0,15.0,NaN,Neutral,"Rarely, almost never","Yes, I use AI tools weekly",Favorable,Somewhat trust,Bad at handling complex tasks,NaN,Project planning;Documenting code;Testing code...,Learning about a codebase;Writing code;Debuggi...,Search for answers;Generating content or synth...,NaN,"AI solutions that are almost right, but not qu...",NO,"Yes, I use AI agents at work monthly or infreq...",Not at all or minimally,Software engineering,Language processing,AI agents have accelerated my learning about n...,AI agents have increased my productivity.;AI a...,AI agents have helped me automate repetitive t...,NaN,NaN,It takes significant time and effort to learn ...,NaN,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ChatGPT;Claude Code,NaN,When I don’t trust AI’s answers;When I want to...,NaN,36197.0,6.0
4,5,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...","Caring for dependents (children, elderly, etc.)",21.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools for...",Technical documentation (is generated for/by t...,22.0,Engineering manager,NaN,NaN,NaN,"Yes, I endorsed a tool that was open-source an...",Work,6.0,3.0,1.0,9.0,10.0,8.0,7.0,4.0,2.0,14.0,NaN,7.0,13.0,3.0,9.0,12.0,6.0,1.0,8.0,14.0,15.0,NaN,Software Development,9.0,4.0,11.0,13.0,14.0,8.0,6.0,5.0,7.0,2.0,1.0,12.0,10.0,15.0,3.0,NaN,No,I have neither consider or transitioned into a...,4.0,3.0,Ukraine,USD United States dollar,60000.0,Yes,C;C#;C++;Delphi;HTML/CSS;Java;JavaScript;Lua;P...,C#;Java;JavaScript;Python;SQL;TypeScript,C#;Java;JavaScript;Python;SQL;TypeScript,NaN,NaN,Yes,Elasticsearch;Microsoft SQL Server;MySQL;Oracl...,Elasticsearch;Oracle;PostgreSQL,Elasticsearch;Oracle;PostgreSQL,NaN,NaN,Yes,Amazon Web Services (AWS);APT;Docker;Make;Mave...,Amazon Web Services (AWS);APT;Docker;Maven (bu...,Amazon Web Services (AWS);APT;Docker;Maven (bu...,NaN,NaN,Yes,Angular;ASP.NET;ASP.NET Core;Flask;jQuery,Angular;ASP.NET Core;Flask,Angular;ASP.NET Core;Flask,NaN,NaN,Yes,Eclipse;IntelliJ IDEA;Jupyter Notebook/Jupyter...,IntelliJ IDEA;Jupyter Notebook/JupyterLab;Note...,IntelliJ IDEA;Jupyter Notebook/JupyterLab;Note...,NaN,NaN,Large Language Model;Google Gemini,Large Language Model,Large Language Model,NaN,NaN,Windows;iOS,Windows;Ubuntu;Debian,Azure Devops;GitHub;Jira,Azure Devops;GitHub;Jira,Azure Devops;GitHub;Jira,NaN,NaN,Stack Overflow;Stack Exchange;GitHub (public p...,Stack Overflow;Stack Exchange;GitHub (public p...,Stack Overflow;Stack Exchange;GitHub (public p...,NaN,NaN,Yes,openAI GPT (chatbot models),openAI GPT (chatbot models),openAI GPT (chatbot models),NaN,NaN,No,A few times per month or weekly,Between 5 and 10 years,"Infrequently, less than once per year",Long-form articles,1.0,NaN,7.0,4.0,2.0,5.0,10.0,6.0,12.0,15.0,NaN,"No, not really","Rarely, almost never","Yes, I use AI tools weekly",Favorable,Neither trust nor distrust,"Good, but not great at handling complex tasks",Learning about a codebase;Writing code;Debuggi...,Project planning;Documenting code;Testing code...,Generating content or synthetic data,NaN,NaN,"AI solutions that are almost right, but not quite",partly,"No, and I don't plan to","Yes, to a great extent",NaN,NaN,NaN,NaN,NaN,NaN,NaN,Integrating AI agents with my existing tools a...,NaN,I am concerned about the accuracy of the infor...,It takes significant time and effort to learn ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers,"critical thinking, the skill to define the tas...",60000.0,7.0
5,6,I am a developer by profession,45-54 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...","Caring for dependents (children, elderly, etc....",15.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools req...",Technical documentation (is generated for/by t...,20.0,"Developer, back-end",NaN,NaN,NaN,"Yes, I influenced the purchase of a substantia...",Work,12.0,5.0,4.0,6.0,2.0,10.0,3.0,7.0,8.0,14.0,NaN,12.0,5.0,13.0,10.0,9.0,1.0,4.0,6.0,2.0,15.0,NaN,Fintech,4.0,3.0,5.0,8.0,9.0,2.0,1.0,10.0,11.0,12.0,6.0,13.0,14.0,15.0,7.0,NaN,I'm not sure,I have somewhat considered changing my career ...,5.0,5.0,Ukraine,USD United States dollar,120000.0,Yes,Java;Scala,Java;Kotlin;Scala,Java;Scala,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,Amazon Web Services (AWS);Google Cloud;Microso...,Amazon Web Services (AWS),Amazon Web Services (AWS),NaN,NaN,Yes,Spring Boot,Spring Boot,Spring Boot,akka,akka,Yes,IntelliJ IDEA;Visual Studio Code,IntelliJ IDEA;Visual Studio Code,IntelliJ IDEA;Visual Studio Code,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MacOS,MacOS,Azure Devops;GitHub;GitLab;Jira,GitHub;Jira,GitHub;Jira,NaN,NaN,Stack Overflow;Stack Exchange;X;YouTube;Linked...,Stack Overflow;Stack Exchange;X;YouTube;Linked...,Stack Overflow;Stack Exchange;X;YouTube;Linked...,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,A few times per month or weekly,Between 10 and 15 years,"Infrequently, less than once per year","Lists of recommendations (tools, frameworks, t...",6.0,NaN,9.0,3.0,4.0,5.0,10.0,1.0,11.0,15.0,NaN,"Yes, somewhat","Rarely, almost never","Yes, I use AI tools daily",Indifferent,Somewhat distrust,"Good, but not great at handling complex tasks",Learning about a codebase;Writing code;Documen...,Predictive analytics,Deployment and monitoring,Project planning;Debugging or fixing code;Comm...,Testing code;Learning new concepts or technolo...,"AI solutions that are almost right, but not quite",No it isnt,"Yes, I use AI agents at work monthly or infreq...",Not at all or minimally,Software engineering;Business process automati...,NaN,AI agents have increased my productivity.;AI a...,NaN,AI agents have improved the quality of my code...,AI agents have helped me automate repetitive t...,NaN,The cost of using certain AI agent platforms i...,NaN,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,My company's IT and/or InfoSec teams have stri...,NaN,NaN,NaN,NaN,NaN,NaN,GitHub Copilot,NaN,When I have ethical or security concerns about...,designing the architecture in the new domain,120000.0,7.0

In [12]:
df.shape

(49191, 172)

In [13]:
df.columns

Index(['ResponseId', 'MainBranch', 'Age', 'EdLevel', 'Employment',
       'EmploymentAddl', 'WorkExp', 'LearnCodeChoose', 'LearnCode',
       'LearnCodeAI',
       ...
       'AIAgentOrchestration', 'AIAgentOrchWrite', 'AIAgentObserveSecure',
       'AIAgentObsWrite', 'AIAgentExternal', 'AIAgentExtWrite', 'AIHuman',
       'AIOpen', 'ConvertedCompYearly', 'JobSat'],
      dtype='str', length=172)

In [14]:
df['MainBranch']

0                           I am a developer by profession
1                           I am a developer by profession
2                           I am a developer by profession
3                           I am a developer by profession
4                           I am a developer by profession
                               ...
49186                          I code primarily as a hobby
49187                       I am a developer by profession
49188                       I am a developer by profession
49189                       I am a developer by profession
49190    I am not primarily a developer, but I write co...
Name: MainBranch, Length: 49191, dtype: str

In [15]:
df['MainBranch'].value_counts()

MainBranch
I am a developer by profession                                                                37467
I am not primarily a developer, but I write code sometimes as part of my work/studies          4894
I am learning to code                                                                          2585
I code primarily as a hobby                                                                    1924
I used to be a developer by profession, but no longer am                                       1325
I work with developers or my work supports developers but am not a developer by profession      996
Name: count, dtype: int64

In [16]:
# df.loc['ResponseId']

In [17]:
# df.loc[0, 'EdLevel']

In [18]:
# df.loc[[0,1,2], 'EdLevel']

In [19]:
#slicing dont wrap inner brackets
#slicing using default indexes
df.loc[0:2]

,ResponseId,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,AILearnHow,YearsCode,DevType,OrgSize,ICorPM,RemoteWork,PurchaseInfluence,TechEndorseIntro,TechEndorse_1,TechEndorse_2,TechEndorse_3,TechEndorse_4,TechEndorse_5,TechEndorse_6,TechEndorse_7,TechEndorse_8,TechEndorse_9,TechEndorse_13,TechEndorse_13_TEXT,TechOppose_1,TechOppose_2,TechOppose_3,TechOppose_5,TechOppose_7,TechOppose_9,TechOppose_11,TechOppose_13,TechOppose_16,TechOppose_15,TechOppose_15_TEXT,Industry,JobSatPoints_1,JobSatPoints_2,JobSatPoints_3,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,JobSatPoints_13,JobSatPoints_14,JobSatPoints_15,JobSatPoints_16,JobSatPoints_15_TEXT,AIThreat,NewRole,ToolCountWork,ToolCountPersonal,Country,Currency,CompTotal,LanguageChoice,LanguageHaveWorkedWith,LanguageWantToWorkWith,LanguageAdmired,LanguagesHaveEntry,LanguagesWantEntry,DatabaseChoice,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,DatabaseAdmired,DatabaseHaveEntry,DatabaseWantEntry,PlatformChoice,PlatformHaveWorkedWith,PlatformWantToWorkWith,PlatformAdmired,PlatformHaveEntry,PlatformWantEntry,WebframeChoice,WebframeHaveWorkedWith,WebframeWantToWorkWith,WebframeAdmired,WebframeHaveEntry,WebframeWantEntry,DevEnvsChoice,DevEnvsHaveWorkedWith,DevEnvsWantToWorkWith,DevEnvsAdmired,DevEnvHaveEntry,DevEnvWantEntry,SOTagsHaveWorkedWith,SOTagsWantToWorkWith,SOTagsAdmired,SOTagsHaveEntry,SOTagsWant Entry,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackAsyncAdmired,OfficeStackHaveEntry,OfficeStackWantEntry,CommPlatformHaveWorkedWith,CommPlatformWantToWorkWith,CommPlatformAdmired,CommPlatformHaveEntr,CommPlatformWantEntr,AIModelsChoice,AIModelsHaveWorkedWith,AIModelsWantToWorkWith,AIModelsAdmired,AIModelsHaveEntry,AIModelsWantEntry,SOAccount,SOVisitFreq,SODuration,SOPartFreq,SO_Dev_Content,SO_Actions_1,SO_Actions_16,SO_Actions_3,SO_Actions_4,SO_Actions_5,SO_Actions_6,SO_Actions_9,SO_Actions_7,SO_Actions_10,SO_Actions_15,SO_Actions_15_TEXT,SOComm,SOFriction,AISelect,AISent,AIAcc,AIComplex,AIToolCurrently partially AI,AIToolDon't plan to use AI for this task,AIToolPlan to partially use AI,AIToolPlan to mostly use AI,AIToolCurrently mostly AI,AIFrustration,AIExplain,AIAgents,AIAgentChange,AIAgent_Uses,AgentUsesGeneral,AIAgentImpactSomewhat agree,AIAgentImpactNeutral,AIAgentImpactSomewhat disagree,AIAgentImpactStrongly agree,AIAgentImpactStrongly disagree,AIAgentChallengesNeutral,AIAgentChallengesSomewhat disagree,AIAgentChallengesStrongly agree,AIAgentChallengesSomewhat agree,AIAgentChallengesStrongly disagree,AIAgentKnowledge,AIAgentKnowWrite,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
0,1,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,"Caring for dependents (children, elderly, etc.)",8.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,14.0,"Developer, mobile",20 to 99 employees,People manager,Remote,"Yes, I influenced the purchase of a substantia...",Work,10.0,7.0,9.0,6.0,3.0,11.0,12.0,1.0,8.0,14.0,NaN,15.0,7.0,8.0,12.0,11.0,1.0,6.0,13.0,3.0,16.0,NaN,Fintech,3.0,1.0,4.0,9.0,5.0,10.0,12.0,11.0,2.0,6.0,7.0,13.0,14.0,15.0,8.0,NaN,I'm not sure,I have neither consider or transitioned into a...,7.0,3.0,Ukraine,EUR European Euro,52800.0,Yes,Bash/Shell (all shells);Dart;SQL,Dart,Dart,NaN,NaN,Yes,Cloud Firestore;PostgreSQL,NaN,NaN,NaN,NaN,Yes,Amazon Web Services (AWS);Cloudflare;Firebase;...,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,Android Studio;Notepad++;Visual Studio;Visual ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Windows;MacOS;Android,Windows;MacOS;Android;iOS;iPadOS,Confluence;GitHub;GitLab;Jira;Markdown File,Markdown File,Markdown File,NaN,NaN,"Stack Overflow;Reddit;GitHub (public projects,...",NaN,NaN,NaN,NaN,Yes,openAI GPT (chatbot models);openAI Image gener...,NaN,NaN,NaN,NaN,Yes,A few times per week,Between 5 and 10 years,I have never participated in Q&A on Stack Over...,NaN,1.0,NaN,6.0,2.0,3.0,7.0,8.0,9.0,11.0,15.0,NaN,Neutral,"Rarely, almost never","Yes, I use AI tools monthly or infrequently",Indifferent,Neither trust nor distrust,Bad at handling complex tasks,Learning about a codebase;Writing code;Search ...,Project planning;Deployment and monitoring;Lea...,Documenting code;Debugging or fixing code;Test...,NaN,NaN,"AI solutions that are almost right, but not quite",No,"Yes, I use AI agents at work monthly or infreq...",Not at all or minimally,Software engineering,NaN,AI agents have increased my productivity.;AI a...,AI agents have helped me automate repetitive t...,NaN,NaN,NaN,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,The cost of using certain AI agent platforms i...,NaN,NaN,NaN,NaN,Vertex AI,NaN,NaN,NaN,ChatGPT,NaN,When I don’t trust AI’s answers,"Troubleshooting, profiling, debugging",61256.0,10.0
1,2,I am a developer by profession,25-34 years old,"Associate degree (A.A., A.S., etc.)",Employed,NaN,2.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,10.0,"Developer, back-end",500 to 999 employees,Individual contributor,"Hybrid (some in-person, leans heavy to flexibi...",No,Personal Project,13.0,1.0,2.0,9.0,4.0,3.0,12.0,5.0,7.0,14.0,NaN,14.0,1.0,13.0,10.0,9.0,3.0,4.0,2.0,5.0,15.0,NaN,Retail and Consumer Services,10.0,8.0,3.0,9.0,12.0,1.0,6.0,2.0,11.0,4.0,7.0,13.0,14.0,15.0,5.0,NaN,I'm not sure,I have transitioned into a new career and/or i...,6.0,5.0,Netherlands,EUR European Euro,90000.0,Yes,Java,Java;Python;Swift,Java,NaN,NaN,Yes,Dynamodb;MongoDB,Dynamodb;MongoDB,Dynamodb;MongoDB,NaN,NaN,Yes,Amazon Web Services (AWS);Datadog;Docker;Homeb...,Amazon Web Services (AWS);Datadog;Docker;Homeb...,Amazon Web Services (AWS);Datadog;Docker;Homeb...,NaN,NaN,Yes,Spring Boot,Spring Boot,Spring Boot,NaN,NaN,Yes,IntelliJ IDEA;PyCharm;Visual Studio Code;Xcode,IntelliJ IDEA;PyCharm;Visual Studio Code;Xcode,IntelliJ IDEA;PyCharm;Visual Studio Code;Xcode,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Windows;MacOS;iOS;iPadOS,MacOS,Confluence;GitHub;Jira,Confluence;GitHub;Jira,Confluence;GitHub;Jira,NaN,NaN,Stack Overflow;Discord;Reddit;Dev.to;Hacker Ne...,Stack Overflow;Discord;Reddit;Dev.to;Hacker Ne...,Stack Overflow;Discord;Reddit;Dev.to;Hacker Ne...,NaN,NaN,Yes,openAI GPT (chatbot models),openAI GPT (chatbot models),openAI GPT (chatbot models),NaN,NaN,Not sure/can't remember,Multiple times per day,Between 10 and 15 years,"Infrequently, less than once per year",Chat (people);Message Boards;Long-form article...,6.0,NaN,5.0,8.0,2.0,4.0,9.0,10.0,11.0,15.0,NaN,"Yes, somewhat",About half of the time,"Yes, I use AI tools weekly",Indifferent,Neither trust nor distrust,Bad at handling complex tasks,Learning new concepts or technologies,Learning about a codebase;Project planning;Com...,Writing code;Documenting code;Debugging or fix...,NaN,NaN,"AI solutions that are almost right, but not qu...",No,"No, and I don't plan to",Not at all or minimally,NaN,NaN,NaN,NaN,NaN,NaN,NaN,It takes significant time and effort to learn ...,NaN,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,All skills. AI is a flop.,104413.0,9.0
2,3,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Independent contractor, freelancer, or self-em...",None of the above,10.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Technical ...,12.0,"Developer, front-end",NaN,NaN,NaN,No,Work,12.0,2.0,3.0,7.0,5.0,10.0,13.0,1.0,4.0,14.0,NaN,8.0,1.0,2.0,12.0,13.0,3.0,9.0,4.0,11.0,15.0,NaN,Software Development,9.0,6.0,7.0,11.0,8.0,12.0,1.0,5.0,2.0,4.0,3.0,13.0,14.0,15.0,10.0,NaN,No,I have transitioned into a new career and/or i...,3.0,3.0,Ukraine,UAH Ukrainian hryvnia,2214000.0,Yes,Dart;HTML/CSS;JavaScript;TypeScript,Dart;HTML/CSS;JavaScript;TypeScript,Dart;HTML/CSS;JavaScript;TypeScript,NaN,NaN,Yes,MongoDB;MySQL;PostgreSQL,Firebase Realtime Database;MongoDB,MongoDB,NaN,NaN,Yes,Datadog;Firebase;npm;pnpm,Amazon Web Services (AWS);Firebase;npm;pnpm;Vite,Firebase;npm;pnpm,NaN,NaN,Yes,Next.js;Node.js;React,Next.js;Node.js;React,Next.js;Node.js;React,NaN,Solid.js,Yes,Visual Studio Code,Visual Studio Code;Windsurf,Visual Studio Code,NaN,NaN,Google Gemini,Google Gemini;Shadcn/ui,Google Gemini,NaN,NaN,MacOS;Android,MacOS,GitHub;GitLab;Jira,GitHub;GitLab;Jira,GitHub;GitLab;Jira,NaN,NaN,Stack Overflow;Discord;Dev.to;X;YouTube;LinkedIn,Stack Overflow;Discord;Dev.to;X;YouTube;LinkedIn,Stack Overflow;Discord;Dev.to;X;YouTube;LinkedIn,NaN,NaN,Yes,Gemini (Flash general purpose models);openAI G...,Gemini (Flash general purpose models);Gemini (...,Gemini (Flash general purpose models);openAI G...,NaN,NaN,Not sure/can't remember,A few times per week,Between 5 and 10 years,"Infrequently, less than once per year",Chat (people);Videos;Lists of recommendations ...,3.0,NaN,4.0,5.0,1.0,2.0,7.0,9.0,11.0,15.0,NaN,Neutral,About half of the time,"Yes, I use AI tools daily",Favorable,Somewhat trust,Neither good or bad at handling complex tasks,Documenting code;Debugging or fixing code;Test...,NaN,Project planning;Committing and reviewing code...,Learning about a codebase;Writing code;Generat...,NaN,"AI solutions that are almost right, but not qu...",No,"Yes, I use AI agents at work weekly","Yes, somewhat",Software engineering,Multi-platform search enablement,AI agents have increased my productivity.;AI a...,AI agents have improved the quality of my code...,AI agents have improved collaboration within m...,NaN,NaN,It takes significant time and effort to learn ...,My company's IT and/or InfoSec teams have stri...,NaN,I am concerned about the accuracy of the infor...,NaN,Redis,NaN,NaN,NaN,NaN,NaN,ChatGPT;Claude Code;GitHub Copilot;Google Gemini,NaN,When I don’t trust AI’s answers;When I want to...,"Understand how things actually work, problem s...",53061.0,8.0

In [20]:
#slicing using column names
df.loc[0:2, 'MainBranch':'EdLevel']

,MainBranch,Age,EdLevel
0,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)"
1,I am a developer by profession,25-34 years old,"Associate degree (A.A., A.S., etc.)"
2,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)"

In [21]:
#slicing is inclusive of the end value unlike normal
#python slicing

In [22]:
schema_df

,qid,question,type,sub,sq_id
qname,,,,,
TechEndorse_1,QID18,What attracts you to a technology or causes yo...,RO,AI integration or AI Agent capabilities,1.0
TechEndorse_2,QID18,What attracts you to a technology or causes yo...,RO,Easy-to-use API,2.0
TechEndorse_3,QID18,What attracts you to a technology or causes yo...,RO,Robust and complete API,3.0
TechEndorse_4,QID18,What attracts you to a technology or causes yo...,RO,Customizable and manageable codebase,4.0
TechEndorse_5,QID18,What attracts you to a technology or causes yo...,RO,Reputation for quality,5.0
TechEndorse_6,QID18,What attracts you to a technology or causes yo...,RO,Connected to an open-source project,6.0
TechEndorse_7,QID18,What attracts you to a technology or causes yo...,RO,Good brand and public image,7.0
TechEndorse_8,QID18,What attracts you to a technology or causes yo...,RO,Reliability and low latency,8.0
TechEndorse_9,QID18,What attracts you to a technology or causes yo...,RO,Costs are manageable,9.0
TechEndorse_13,QID18,What attracts you to a technology or causes yo...,RO,Other (please specify):,10.0
TechEndorse_13_TEXT,QID18,What attracts you to a technology or causes yo...,RO,Other (please specify): - Text,13.0
TechOppose_1,QID19,What would turn you off or cause you to reject...,RO,Lack of AI or AI agents,1.0
TechOppose_2,QID19,What would turn you off or cause you to reject...,RO,Poor usability,2.0
TechOppose_3,QID19,What would turn you off or cause you to reject...,RO,Lack of or sub-par API,3.0
TechOppose_5,QID19,What would turn you off or cause you to reject...,RO,Inefficient or time-costly,4.0
TechOppose_7,QID19,What would turn you off or cause you to reject...,RO,Prohibitive pricing,5.0
TechOppose_9,QID19,What would turn you off or cause you to reject...,RO,Security or privacy concerns,6.0
TechOppose_11,QID19,What would turn you off or cause you to reject...,RO,Availability of better alternatives,7.0
TechOppose_13,QID19,What would turn you off or cause you to reject...,RO,Outdated or obsolete technology or features,8.0
TechOppose_16,QID19,What would turn you off or cause you to reject...,RO,Ethical concerns,9.0
TechOppose_15,QID19,What would turn you off or cause you to reject...,RO,Other (please specify):,10.0
TechOppose_15_TEXT,QID19,What would turn you off or cause you to reject...,RO,Other (please specify): - Text,15.0
JobSatPoints_1,QID27,Rank the following attributes of your current ...,RO,Control over the level of quality in projects,1.0
JobSatPoints_2,QID27,Rank the following attributes of your current ...,RO,Autonomy and trust to manage your own tasks,2.0
JobSatPoints_16,QID27,Rank the following attributes of your current ...,RO,You like your manager,3.0
JobSatPoints_3,QID27,Rank the following attributes of your current ...,RO,Collaboration and support from a team,4.0
JobSatPoints_4,QID27,Rank the following attributes of your current ...,RO,Expert mentors,5.0
JobSatPoints_5,QID27,Rank the following attributes of your current ...,RO,Opportunities to mentor and lead junior-level ...,6.0
JobSatPoints_6,QID27,Rank the following attributes of your current ...,RO,Developing specialized expertise,7.0
JobSatPoints_7,QID27,Rank the following attributes of your current ...,RO,Solving real-world problems,8.0
JobSatPoints_8,QID27,Rank the following attributes of your current ...,RO,Job stability and career growth with a single ...,9.0
JobSatPoints_9,QID27,Rank the following attributes of your current ...,RO,Innovation through solving challenging and com...,10.0
JobSatPoints_10,QID27,Rank the following attributes of your current ...,RO,Working with new technologies and tools,11.0
JobSatPoints_11,QID27,Rank the following attributes of your current ...,RO,Competitive pay and benefits,12.0
JobSatPoints_13,QID27,Rank the following attributes of your current ...,RO,Recognition from peers for your work,13.0
JobSatPoints_14,QID27,Rank the following attributes of your current ...,RO,Recognition from leadership for your work,14.0
JobSatPoints_15,QID27,Rank the following attributes of your current ...,RO,Other (please specify):,15.0
JobSatPoints_15_TEXT,QID27,Rank the following attributes of your current ...,RO,Other (please specify): - Text,15.0
SO_Actions_1,QID76,"When visiting Stack Overflow, which following ...",RO,Browse content related to Q&A posts I recently...,1.0
SO_Actions_16,QID76,"When visiting Stack Overflow, which following ...",RO,Read and/or vote on comments for a Question or...,2.0
SO_Actions_3,QID76,"When visiting Stack Overflow, which following ...",RO,Bookmark posts to look at later,3.0
SO_Actions_4,QID76,"When visiting Stack Overflow, which following ...",RO,"Directly open a Q&A post via search, documenta...",4.0
SO_Actions_5,QID76,"When visiting Stack Overflow, which following ...",RO,Ask a question,5.0
SO_Actions_6,QID76,"When visiting Stack Overflow, which following ...",RO,Answer a question,6.0
SO_Actions_9,QID76,"When visiting Stack Overflow, which following ...",RO,Comment on Q&A posts,7.0
SO_Actions_7,QID76,"When visiting Stack Overflow, which following ...",RO,Upvote/Downvote Q&A posts,8.0
SO_Actions_10,QID76,"When visiting Stack Overflow, which following ...",RO,Use discussion or chat feature,9.0
SO_Actions_15,QID76,"When visiting Stack Overflow, which following ...",RO,Other (write in):,10.0
SO_Actions_15_TEXT,QID76,"When visiting Stack Overflow, which following ...",RO,Other (write in): - Text,15.0
MainBranch,QID3,Are you someone who writes code? Please select...,MC,NaN,NaN
Age,QID4,What is your age?,MC,NaN,NaN
EdLevel,QID9,Which of the following best describes the high...,MC,NaN,NaN
Employment,QID7,Which of the following best describes your cur...,MC,NaN,NaN
EmploymentAddl,QID8,Which of the following <strong>additional</str...,MC,NaN,NaN
WorkExp,QID14,How many years of professional work experience...,TE,NaN,NaN
LearnCodeChoose,QID10,Did you begin learning to code or learn a new ...,MC,NaN,NaN
LearnCode,QID11,How did you learn to code in the past year? Se...,MC,NaN,NaN
LearnCodeAI,QID12,Did you spend time in the last year learning A...,MC,NaN,NaN
AILearnHow,QID32,How did you learn to code for AI in the past y...,MC,NaN,NaN
YearsCode,QID13,"Including any education, how many years have y...",TE,NaN,NaN
DevType,QID15,Which of the following describes your current ...,MC,NaN,NaN
OrgSize,QID16,Approximately how many people are employed by ...,MC,NaN,NaN
ICorPM,QID23,Are you an individual contributor or people ma...,MC,NaN,NaN
RemoteWork,QID24,Which best describes your current work situation?,MC,NaN,NaN
PurchaseInfluence,QID17,Have you <strong>influenced or endorsed</stron...,MC,NaN,NaN
TechEndorseIntro,QID33,When you&rsquo;re in a position to <strong>inf...,MC,NaN,NaN
Industry,QID25,What industry do you work for in?,MC,NaN,NaN
JobSat,QID26,How satisfied are you in your current professi...,MC,NaN,NaN
AIThreat,QID28,Do you believe AI is a threat to your current ...,MC,NaN,NaN
NewRole,QID29,Have you considered a career change or transit...,MC,NaN,NaN
ToolCountWork,QID30,"For your <b>primary work role</b> (student, de...",TE,NaN,NaN
ToolCountPersonal,QID31,<b></b>For your <b>side projects or other pers...,TE,NaN,NaN
Country,QID20,Where do you live?,MC,NaN,NaN
Currency,QID21,Which currency do you use day-to-day? If your ...,MC,NaN,NaN
CompTotal,QID22,What is your current total <b>annual</b> compe...,TE,NaN,NaN
LanguageChoice,QID44,"Did you work with programming, scripting and m...",MC,NaN,NaN
Language,QID34,"Which <b>programming, scripting, and markup la...",Matrix,NaN,NaN
LanguagesHaveEntry,QID51,Was the programming language you use not liste...,TE,NaN,NaN
LanguagesWantEntry,QID52,Was the programming language you want to use n...,TE,NaN,NaN
DatabaseChoice,QID45,Did you work with database environments in the...,MC,NaN,NaN
Database,QID35,Which <b>database environments </b>have you do...,Matrix,NaN,NaN
DatabaseHaveEntry,QID54,Was the database environment you use not liste...,TE,NaN,NaN
DatabaseWantEntry,QID55,Was the database environment you want to use n...,TE,NaN,NaN
PlatformChoice,QID46,"Did you work with cloud platforms, containeriz...",MC,NaN,NaN
Platform,QID36,"Which <b>cloud platforms, containerization/orc...",Matrix,NaN,NaN
PlatformHaveEntry,QID56,"Was the cloud platforms, containerization/orch...",TE,NaN,NaN
PlatformWantEntry,QID57,"Was the cloud platforms, containerization/orch...",TE,NaN,NaN
WebframeChoice,QID47,Did you work with web frameworks and web techn...,MC,NaN,NaN
Webframe,QID37,Which <b>web frameworks and web technologies</...,Matrix,NaN,NaN
WebframeHaveEntry,QID58,Were the web frameworks and web technologies y...,TE,NaN,NaN
WebframeWantEntry,QID59,Were the web frameworks and web technologies y...,TE,NaN,NaN
DevEnvsChoice,QID48,Did you work with development environments or ...,MC,NaN,NaN
DevEnvs,QID38,Which <strong>development environments and AI-...,Matrix,NaN,NaN
DevEnvHaveEntry,QID60,Was the developer environment or AI-enabled co...,TE,NaN,NaN
DevEnvWantEntry,QID61,Was the developer environment or AI-enabled co...,TE,NaN,NaN
SOTags,QID39,Which rising technology of the added as <b>new...,Matrix,NaN,NaN
SOTagsHaveEntry,QID62,Was the new tag on Stack Overflow (i.e. added ...,TE,NaN,NaN
SOTagsWant Entry,QID63,Was the new tag on Stack Overflow (i.e. added ...,TE,NaN,NaN
OpSys,QID40,What is the primary <b>operating system</b> in...,Matrix,NaN,NaN
OfficeStackAsync,QID41,Which <b>collaborative work management and/or ...,Matrix,NaN,NaN
OfficeStackHaveEntry,QID64,Was the collaborative work management and/or c...,TE,NaN,NaN
OfficeStackWantEntry,QID65,Was the collaborative work management and/or c...,TE,NaN,NaN
CommPlatform,QID42,Which <b>community platforms</b> have you util...,Matrix,NaN,NaN
CommPlatformHaveEntr,QID66,Was the community platform you use not listed ...,TE,NaN,NaN
CommPlatformWantEntr,QID67,Was the community platform you want to use not...,TE,NaN,NaN
AIModelsChoice,QID50,Did you utilize or integrate specific Large La...,MC,NaN,NaN
AIModels,QID43,Which <b>LLM models for AI tools</b> have you ...,Matrix,NaN,NaN
AIModelsHaveEntry,QID68,Was the LLM model for AI tools you use not lis...,TE,NaN,NaN
AIModelsWantEntry,QID69,Was the LLM model for AI tools you want to use...,TE,NaN,NaN
SOAccount,QID72,Do you have a Stack Overflow account?,MC,NaN,NaN
SOVisitFreq,QID70,How frequently would you say you visit Stack O...,MC,NaN,NaN
SODuration,QID71,How long have you used Stack Overflow?,MC,NaN,NaN
SOPartFreq,QID73,How frequently would you say you participate i...,MC,NaN,NaN
SO_Dev_Content,QID75,"Whether it be to solve a problem, for career g...",MC,NaN,NaN
SOComm,QID77,Do you consider yourself a member of the Stack...,MC,NaN,NaN
SOFriction,QID97,"When you visit Stack Overflow, how often is it...",MC,NaN,NaN
AISelect,QID78,Do you currently use AI tools in your developm...,MC,NaN,NaN
AISent,QID79,How favorable is your stance on using AI tools...,MC,NaN,NaN
AIAcc,QID80,How much do you trust the accuracy of the outp...,MC,NaN,NaN
AIComplex,QID81,How well do the AI tools you use in your devel...,MC,NaN,NaN
AITool,QID82,Which parts of your development workflow are y...,Matrix,NaN,NaN
AIFrustration,QID99,"When using AI tools, which of the following pr...",MC,NaN,NaN
AIExplain,QID84,"In your own words, is &quot;vibe coding&quot; ...",TE,NaN,NaN
AIAgents,QID85,Are you using AI agents in your work (developm...,MC,NaN,NaN
AIAgentChange,QID83,Have AI tools or AI agents changed how you com...,MC,NaN,NaN
AIAgent_Uses,QID86,What industry purposes or specific tasks are y...,MC,NaN,NaN
AgentUsesGeneral,QID106,,MC,NaN,NaN
AIAgentImpact,QID87,To what extent do you agree with the following...,Matrix,NaN,NaN
AIAgentChallenges,QID88,To what extent do you agree with the following...,Matrix,NaN,NaN
AIAgentKnowledge,QID89,You indicated you use or develop AI agents as ...,MC,NaN,NaN
AIAgentKnowWrite,QID107,Was the tool or tools for AI agent orchestrati...,TE,NaN,NaN
AIAgentOrchestration,QID90,You indicated you use or develop AI agents as ...,MC,NaN,NaN
AIAgentOrchWrite,QID102,Was the tool or tools for AI agent orchestrati...,TE,NaN,NaN
AIAgentObserveSecure,QID91,You indicated you use or develop AI agents as ...,MC,NaN,NaN
AIAgentObsWrite,QID103,Was the tool or tools for AI agent observabili...,TE,NaN,NaN
AIAgentExternal,QID92,You indicated you use or develop AI agents as ...,MC,NaN,NaN
AIAgentExtWrite,QID104,"Was the out-of-the-box agents, copilots or ass...",TE,NaN,NaN
AIHuman,QID100,"In the future, if AI can do most coding tasks,...",MC,NaN,NaN
AIOpen,QID93,"Looking ahead 3–5 years, what skills do you be...",TE,NaN,NaN

In [23]:
schema_df.loc['AIAgentExtWrite']

qid                                                    QID104
question    Was the out-of-the-box agents, copilots or ass...
type                                                       TE
sub                                                       NaN
sq_id                                                     NaN
Name: AIAgentExtWrite, dtype: object

In [24]:
schema_df.loc['AIAgentExtWrite','question'] #to see the full question pass the column name

'Was the out-of-the-box agents, copilots or assistants you used in the past year not listed above?  Please write them below separated by a comma and space if there are more than one.'

In [25]:
#sorting alphabetically
schema_df.sort_index()

,qid,question,type,sub,sq_id
qname,,,,,
AIAcc,QID80,How much do you trust the accuracy of the outp...,MC,NaN,NaN
AIAgentChallenges,QID88,To what extent do you agree with the following...,Matrix,NaN,NaN
AIAgentChange,QID83,Have AI tools or AI agents changed how you com...,MC,NaN,NaN
AIAgentExtWrite,QID104,"Was the out-of-the-box agents, copilots or ass...",TE,NaN,NaN
AIAgentExternal,QID92,You indicated you use or develop AI agents as ...,MC,NaN,NaN
AIAgentImpact,QID87,To what extent do you agree with the following...,Matrix,NaN,NaN
AIAgentKnowWrite,QID107,Was the tool or tools for AI agent orchestrati...,TE,NaN,NaN
AIAgentKnowledge,QID89,You indicated you use or develop AI agents as ...,MC,NaN,NaN
AIAgentObsWrite,QID103,Was the tool or tools for AI agent observabili...,TE,NaN,NaN
AIAgentObserveSecure,QID91,You indicated you use or develop AI agents as ...,MC,NaN,NaN
AIAgentOrchWrite,QID102,Was the tool or tools for AI agent orchestrati...,TE,NaN,NaN
AIAgentOrchestration,QID90,You indicated you use or develop AI agents as ...,MC,NaN,NaN
AIAgent_Uses,QID86,What industry purposes or specific tasks are y...,MC,NaN,NaN
AIAgents,QID85,Are you using AI agents in your work (developm...,MC,NaN,NaN
AIComplex,QID81,How well do the AI tools you use in your devel...,MC,NaN,NaN
AIExplain,QID84,"In your own words, is &quot;vibe coding&quot; ...",TE,NaN,NaN
AIFrustration,QID99,"When using AI tools, which of the following pr...",MC,NaN,NaN
AIHuman,QID100,"In the future, if AI can do most coding tasks,...",MC,NaN,NaN
AILearnHow,QID32,How did you learn to code for AI in the past y...,MC,NaN,NaN
AIModels,QID43,Which <b>LLM models for AI tools</b> have you ...,Matrix,NaN,NaN
AIModelsChoice,QID50,Did you utilize or integrate specific Large La...,MC,NaN,NaN
AIModelsHaveEntry,QID68,Was the LLM model for AI tools you use not lis...,TE,NaN,NaN
AIModelsWantEntry,QID69,Was the LLM model for AI tools you want to use...,TE,NaN,NaN
AIOpen,QID93,"Looking ahead 3–5 years, what skills do you be...",TE,NaN,NaN
AISelect,QID78,Do you currently use AI tools in your developm...,MC,NaN,NaN
AISent,QID79,How favorable is your stance on using AI tools...,MC,NaN,NaN
AIThreat,QID28,Do you believe AI is a threat to your current ...,MC,NaN,NaN
AITool,QID82,Which parts of your development workflow are y...,Matrix,NaN,NaN
Age,QID4,What is your age?,MC,NaN,NaN
AgentUsesGeneral,QID106,,MC,NaN,NaN
CommPlatform,QID42,Which <b>community platforms</b> have you util...,Matrix,NaN,NaN
CommPlatformHaveEntr,QID66,Was the community platform you use not listed ...,TE,NaN,NaN
CommPlatformWantEntr,QID67,Was the community platform you want to use not...,TE,NaN,NaN
CompTotal,QID22,What is your current total <b>annual</b> compe...,TE,NaN,NaN
Country,QID20,Where do you live?,MC,NaN,NaN
Currency,QID21,Which currency do you use day-to-day? If your ...,MC,NaN,NaN
Database,QID35,Which <b>database environments </b>have you do...,Matrix,NaN,NaN
DatabaseChoice,QID45,Did you work with database environments in the...,MC,NaN,NaN
DatabaseHaveEntry,QID54,Was the database environment you use not liste...,TE,NaN,NaN
DatabaseWantEntry,QID55,Was the database environment you want to use n...,TE,NaN,NaN
DevEnvHaveEntry,QID60,Was the developer environment or AI-enabled co...,TE,NaN,NaN
DevEnvWantEntry,QID61,Was the developer environment or AI-enabled co...,TE,NaN,NaN
DevEnvs,QID38,Which <strong>development environments and AI-...,Matrix,NaN,NaN
DevEnvsChoice,QID48,Did you work with development environments or ...,MC,NaN,NaN
DevType,QID15,Which of the following describes your current ...,MC,NaN,NaN
EdLevel,QID9,Which of the following best describes the high...,MC,NaN,NaN
Employment,QID7,Which of the following best describes your cur...,MC,NaN,NaN
EmploymentAddl,QID8,Which of the following <strong>additional</str...,MC,NaN,NaN
ICorPM,QID23,Are you an individual contributor or people ma...,MC,NaN,NaN
Industry,QID25,What industry do you work for in?,MC,NaN,NaN
JobSat,QID26,How satisfied are you in your current professi...,MC,NaN,NaN
JobSatPoints_1,QID27,Rank the following attributes of your current ...,RO,Control over the level of quality in projects,1.0
JobSatPoints_10,QID27,Rank the following attributes of your current ...,RO,Working with new technologies and tools,11.0
JobSatPoints_11,QID27,Rank the following attributes of your current ...,RO,Competitive pay and benefits,12.0
JobSatPoints_13,QID27,Rank the following attributes of your current ...,RO,Recognition from peers for your work,13.0
JobSatPoints_14,QID27,Rank the following attributes of your current ...,RO,Recognition from leadership for your work,14.0
JobSatPoints_15,QID27,Rank the following attributes of your current ...,RO,Other (please specify):,15.0
JobSatPoints_15_TEXT,QID27,Rank the following attributes of your current ...,RO,Other (please specify): - Text,15.0
JobSatPoints_16,QID27,Rank the following attributes of your current ...,RO,You like your manager,3.0
JobSatPoints_2,QID27,Rank the following attributes of your current ...,RO,Autonomy and trust to manage your own tasks,2.0
JobSatPoints_3,QID27,Rank the following attributes of your current ...,RO,Collaboration and support from a team,4.0
JobSatPoints_4,QID27,Rank the following attributes of your current ...,RO,Expert mentors,5.0
JobSatPoints_5,QID27,Rank the following attributes of your current ...,RO,Opportunities to mentor and lead junior-level ...,6.0
JobSatPoints_6,QID27,Rank the following attributes of your current ...,RO,Developing specialized expertise,7.0
JobSatPoints_7,QID27,Rank the following attributes of your current ...,RO,Solving real-world problems,8.0
JobSatPoints_8,QID27,Rank the following attributes of your current ...,RO,Job stability and career growth with a single ...,9.0
JobSatPoints_9,QID27,Rank the following attributes of your current ...,RO,Innovation through solving challenging and com...,10.0
Language,QID34,"Which <b>programming, scripting, and markup la...",Matrix,NaN,NaN
LanguageChoice,QID44,"Did you work with programming, scripting and m...",MC,NaN,NaN
LanguagesHaveEntry,QID51,Was the programming language you use not liste...,TE,NaN,NaN
LanguagesWantEntry,QID52,Was the programming language you want to use n...,TE,NaN,NaN
LearnCode,QID11,How did you learn to code in the past year? Se...,MC,NaN,NaN
LearnCodeAI,QID12,Did you spend time in the last year learning A...,MC,NaN,NaN
LearnCodeChoose,QID10,Did you begin learning to code or learn a new ...,MC,NaN,NaN
MainBranch,QID3,Are you someone who writes code? Please select...,MC,NaN,NaN
NewRole,QID29,Have you considered a career change or transit...,MC,NaN,NaN
OfficeStackAsync,QID41,Which <b>collaborative work management and/or ...,Matrix,NaN,NaN
OfficeStackHaveEntry,QID64,Was the collaborative work management and/or c...,TE,NaN,NaN
OfficeStackWantEntry,QID65,Was the collaborative work management and/or c...,TE,NaN,NaN
OpSys,QID40,What is the primary <b>operating system</b> in...,Matrix,NaN,NaN
OrgSize,QID16,Approximately how many people are employed by ...,MC,NaN,NaN
Platform,QID36,"Which <b>cloud platforms, containerization/orc...",Matrix,NaN,NaN
PlatformChoice,QID46,"Did you work with cloud platforms, containeriz...",MC,NaN,NaN
PlatformHaveEntry,QID56,"Was the cloud platforms, containerization/orch...",TE,NaN,NaN
PlatformWantEntry,QID57,"Was the cloud platforms, containerization/orch...",TE,NaN,NaN
PurchaseInfluence,QID17,Have you <strong>influenced or endorsed</stron...,MC,NaN,NaN
RemoteWork,QID24,Which best describes your current work situation?,MC,NaN,NaN
SOAccount,QID72,Do you have a Stack Overflow account?,MC,NaN,NaN
SOComm,QID77,Do you consider yourself a member of the Stack...,MC,NaN,NaN
SODuration,QID71,How long have you used Stack Overflow?,MC,NaN,NaN
SOFriction,QID97,"When you visit Stack Overflow, how often is it...",MC,NaN,NaN
SOPartFreq,QID73,How frequently would you say you participate i...,MC,NaN,NaN
SOTags,QID39,Which rising technology of the added as <b>new...,Matrix,NaN,NaN
SOTagsHaveEntry,QID62,Was the new tag on Stack Overflow (i.e. added ...,TE,NaN,NaN
SOTagsWant Entry,QID63,Was the new tag on Stack Overflow (i.e. added ...,TE,NaN,NaN
SOVisitFreq,QID70,How frequently would you say you visit Stack O...,MC,NaN,NaN
SO_Actions_1,QID76,"When visiting Stack Overflow, which following ...",RO,Browse content related to Q&A posts I recently...,1.0
SO_Actions_10,QID76,"When visiting Stack Overflow, which following ...",RO,Use discussion or chat feature,9.0
SO_Actions_15,QID76,"When visiting Stack Overflow, which following ...",RO,Other (write in):,10.0
SO_Actions_15_TEXT,QID76,"When visiting Stack Overflow, which following ...",RO,Other (write in): - Text,15.0
SO_Actions_16,QID76,"When visiting Stack Overflow, which following ...",RO,Read and/or vote on comments for a Question or...,2.0
SO_Actions_3,QID76,"When visiting Stack Overflow, which following ...",RO,Bookmark posts to look at later,3.0
SO_Actions_4,QID76,"When visiting Stack Overflow, which following ...",RO,"Directly open a Q&A post via search, documenta...",4.0
SO_Actions_5,QID76,"When visiting Stack Overflow, which following ...",RO,Ask a question,5.0
SO_Actions_6,QID76,"When visiting Stack Overflow, which following ...",RO,Answer a question,6.0
SO_Actions_7,QID76,"When visiting Stack Overflow, which following ...",RO,Upvote/Downvote Q&A posts,8.0
SO_Actions_9,QID76,"When visiting Stack Overflow, which following ...",RO,Comment on Q&A posts,7.0
SO_Dev_Content,QID75,"Whether it be to solve a problem, for career g...",MC,NaN,NaN
TechEndorseIntro,QID33,When you&rsquo;re in a position to <strong>inf...,MC,NaN,NaN
TechEndorse_1,QID18,What attracts you to a technology or causes yo...,RO,AI integration or AI Agent capabilities,1.0
TechEndorse_13,QID18,What attracts you to a technology or causes yo...,RO,Other (please specify):,10.0
TechEndorse_13_TEXT,QID18,What attracts you to a technology or causes yo...,RO,Other (please specify): - Text,13.0
TechEndorse_2,QID18,What attracts you to a technology or causes yo...,RO,Easy-to-use API,2.0
TechEndorse_3,QID18,What attracts you to a technology or causes yo...,RO,Robust and complete API,3.0
TechEndorse_4,QID18,What attracts you to a technology or causes yo...,RO,Customizable and manageable codebase,4.0
TechEndorse_5,QID18,What attracts you to a technology or causes yo...,RO,Reputation for quality,5.0
TechEndorse_6,QID18,What attracts you to a technology or causes yo...,RO,Connected to an open-source project,6.0
TechEndorse_7,QID18,What attracts you to a technology or causes yo...,RO,Good brand and public image,7.0
TechEndorse_8,QID18,What attracts you to a technology or causes yo...,RO,Reliability and low latency,8.0
TechEndorse_9,QID18,What attracts you to a technology or causes yo...,RO,Costs are manageable,9.0
TechOppose_1,QID19,What would turn you off or cause you to reject...,RO,Lack of AI or AI agents,1.0
TechOppose_11,QID19,What would turn you off or cause you to reject...,RO,Availability of better alternatives,7.0
TechOppose_13,QID19,What would turn you off or cause you to reject...,RO,Outdated or obsolete technology or features,8.0
TechOppose_15,QID19,What would turn you off or cause you to reject...,RO,Other (please specify):,10.0
TechOppose_15_TEXT,QID19,What would turn you off or cause you to reject...,RO,Other (please specify): - Text,15.0
TechOppose_16,QID19,What would turn you off or cause you to reject...,RO,Ethical concerns,9.0
TechOppose_2,QID19,What would turn you off or cause you to reject...,RO,Poor usability,2.0
TechOppose_3,QID19,What would turn you off or cause you to reject...,RO,Lack of or sub-par API,3.0
TechOppose_5,QID19,What would turn you off or cause you to reject...,RO,Inefficient or time-costly,4.0
TechOppose_7,QID19,What would turn you off or cause you to reject...,RO,Prohibitive pricing,5.0
TechOppose_9,QID19,What would turn you off or cause you to reject...,RO,Security or privacy concerns,6.0
ToolCountPersonal,QID31,<b></b>For your <b>side projects or other pers...,TE,NaN,NaN
ToolCountWork,QID30,"For your <b>primary work role</b> (student, de...",TE,NaN,NaN
Webframe,QID37,Which <b>web frameworks and web technologies</...,Matrix,NaN,NaN
WebframeChoice,QID47,Did you work with web frameworks and web techn...,MC,NaN,NaN
WebframeHaveEntry,QID58,Were the web frameworks and web technologies y...,TE,NaN,NaN
WebframeWantEntry,QID59,Were the web frameworks and web technologies y...,TE,NaN,NaN
WorkExp,QID14,How many years of professional work experience...,TE,NaN,NaN
YearsCode,QID13,"Including any education, how many years have y...",TE,NaN,NaN

In [26]:
#permanently sorting or sorting by default
schema_df.sort_index(inplace=True)

In [27]:
df.columns

Index(['ResponseId', 'MainBranch', 'Age', 'EdLevel', 'Employment',
       'EmploymentAddl', 'WorkExp', 'LearnCodeChoose', 'LearnCode',
       'LearnCodeAI',
       ...
       'AIAgentOrchestration', 'AIAgentOrchWrite', 'AIAgentObserveSecure',
       'AIAgentObsWrite', 'AIAgentExternal', 'AIAgentExtWrite', 'AIHuman',
       'AIOpen', 'ConvertedCompYearly', 'JobSat'],
      dtype='str', length=172)

In [28]:
pd.set_option('display.max_columns', None)

In [29]:
df.columns

Index(['ResponseId', 'MainBranch', 'Age', 'EdLevel', 'Employment',
       'EmploymentAddl', 'WorkExp', 'LearnCodeChoose', 'LearnCode',
       'LearnCodeAI',
       ...
       'AIAgentOrchestration', 'AIAgentOrchWrite', 'AIAgentObserveSecure',
       'AIAgentObsWrite', 'AIAgentExternal', 'AIAgentExtWrite', 'AIHuman',
       'AIOpen', 'ConvertedCompYearly', 'JobSat'],
      dtype='str', length=172)

In [30]:
df.loc[:,'ConvertedCompYearly']

0         61256.0
1        104413.0
2         53061.0
3         36197.0
4         60000.0
           ...
49186         NaN
49187         NaN
49188         NaN
49189         NaN
49190         NaN
Name: ConvertedCompYearly, Length: 49191, dtype: float64

In [31]:
high_salary = (df['ConvertedCompYearly'] > 50000)

In [32]:
high_salary

0         True
1         True
2         True
3        False
4         True
         ...
49186    False
49187    False
49188    False
49189    False
49190    False
Name: ConvertedCompYearly, Length: 49191, dtype: bool

In [33]:
df.loc[high_salary]

,ResponseId,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,AILearnHow,YearsCode,DevType,OrgSize,ICorPM,RemoteWork,PurchaseInfluence,TechEndorseIntro,TechEndorse_1,TechEndorse_2,TechEndorse_3,TechEndorse_4,TechEndorse_5,TechEndorse_6,TechEndorse_7,TechEndorse_8,TechEndorse_9,TechEndorse_13,TechEndorse_13_TEXT,TechOppose_1,TechOppose_2,TechOppose_3,TechOppose_5,TechOppose_7,TechOppose_9,TechOppose_11,TechOppose_13,TechOppose_16,TechOppose_15,TechOppose_15_TEXT,Industry,JobSatPoints_1,JobSatPoints_2,JobSatPoints_3,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,JobSatPoints_13,JobSatPoints_14,JobSatPoints_15,JobSatPoints_16,JobSatPoints_15_TEXT,AIThreat,NewRole,ToolCountWork,ToolCountPersonal,Country,Currency,CompTotal,LanguageChoice,LanguageHaveWorkedWith,LanguageWantToWorkWith,LanguageAdmired,LanguagesHaveEntry,LanguagesWantEntry,DatabaseChoice,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,DatabaseAdmired,DatabaseHaveEntry,DatabaseWantEntry,PlatformChoice,PlatformHaveWorkedWith,PlatformWantToWorkWith,PlatformAdmired,PlatformHaveEntry,PlatformWantEntry,WebframeChoice,WebframeHaveWorkedWith,WebframeWantToWorkWith,WebframeAdmired,WebframeHaveEntry,WebframeWantEntry,DevEnvsChoice,DevEnvsHaveWorkedWith,DevEnvsWantToWorkWith,DevEnvsAdmired,DevEnvHaveEntry,DevEnvWantEntry,SOTagsHaveWorkedWith,SOTagsWantToWorkWith,SOTagsAdmired,SOTagsHaveEntry,SOTagsWant Entry,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackAsyncAdmired,OfficeStackHaveEntry,OfficeStackWantEntry,CommPlatformHaveWorkedWith,CommPlatformWantToWorkWith,CommPlatformAdmired,CommPlatformHaveEntr,CommPlatformWantEntr,AIModelsChoice,AIModelsHaveWorkedWith,AIModelsWantToWorkWith,AIModelsAdmired,AIModelsHaveEntry,AIModelsWantEntry,SOAccount,SOVisitFreq,SODuration,SOPartFreq,SO_Dev_Content,SO_Actions_1,SO_Actions_16,SO_Actions_3,SO_Actions_4,SO_Actions_5,SO_Actions_6,SO_Actions_9,SO_Actions_7,SO_Actions_10,SO_Actions_15,SO_Actions_15_TEXT,SOComm,SOFriction,AISelect,AISent,AIAcc,AIComplex,AIToolCurrently partially AI,AIToolDon't plan to use AI for this task,AIToolPlan to partially use AI,AIToolPlan to mostly use AI,AIToolCurrently mostly AI,AIFrustration,AIExplain,AIAgents,AIAgentChange,AIAgent_Uses,AgentUsesGeneral,AIAgentImpactSomewhat agree,AIAgentImpactNeutral,AIAgentImpactSomewhat disagree,AIAgentImpactStrongly agree,AIAgentImpactStrongly disagree,AIAgentChallengesNeutral,AIAgentChallengesSomewhat disagree,AIAgentChallengesStrongly agree,AIAgentChallengesSomewhat agree,AIAgentChallengesStrongly disagree,AIAgentKnowledge,AIAgentKnowWrite,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
0,1,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,"Caring for dependents (children, elderly, etc.)",8.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,14.0,"Developer, mobile",20 to 99 employees,People manager,Remote,"Yes, I influenced the purchase of a substantia...",Work,10.0,7.0,9.0,6.0,3.0,11.0,12.0,1.0,8.0,14.0,NaN,15.0,7.0,8.0,12.0,11.0,1.0,6.0,13.0,3.0,16.0,NaN,Fintech,3.0,1.0,4.0,9.0,5.0,10.0,12.0,11.0,2.0,6.0,7.0,13.0,14.0,15.0,8.0,NaN,I'm not sure,I have neither consider or transitioned into a...,7.0,3.0,Ukraine,EUR European Euro,52800.0,Yes,Bash/Shell (all shells);Dart;SQL,Dart,Dart,NaN,NaN,Yes,Cloud Firestore;PostgreSQL,NaN,NaN,NaN,NaN,Yes,Amazon Web Services (AWS);Cloudflare;Firebase;...,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,Android Studio;Notepad++;Visual Studio;Visual ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Windows;MacOS;Android,Windows;MacOS;Android;iOS;iPadOS,Confluence;GitHub;GitLab;Jira;Markdown File,Markdown File,Markdown File,NaN,NaN,"Stack Overflow;Reddit;GitHub (public projects,...",NaN,NaN,NaN,NaN,Yes,openAI GPT (chatbot models);openAI Image gener...,NaN,NaN,NaN,NaN,Yes,A few times per week,Between 5 and 10 years,I have never participated in Q&A on Stack Over...,NaN,1.0,NaN,6.0,2.0,3.0,7.0,8.0,9.0,11.0,15.0,NaN,Neutral,"Rarely, almost never","Yes, I use AI tools monthly or infrequently",Indifferent,Neither trust nor distrust,Bad at handling complex tasks,Learning about a codebase;Writing code;Search ...,Project planning;Deployment and monitoring;Lea...,Documenting code;Debugging or fixing code;Test...,NaN,NaN,"AI solutions that are almost right, but not quite",No,"Yes, I use AI agents at work monthly or infreq...",Not at all or minimally,Software engineering,NaN,AI agents have increased my productivity.;AI a...,AI agents have helped me automate repetitive t...,NaN,NaN,NaN,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,The cost of using certain AI agent platforms i...,NaN,NaN,NaN,NaN,Vertex AI,NaN,NaN,NaN,ChatGPT,NaN,When I don’t trust AI’s answers,"Troubleshooting, profiling, debugging",61256.0,10.0
1,2,I am a developer by profession,25-34 years old,"Associate degree (A.A., A.S., etc.)",Employed,NaN,2.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,10.0,"Developer, back-end",500 to 999 employees,Individual contributor,"Hybrid (some in-person, leans heavy to flexibi...",No,Personal Project,13.0,1.0,2.0,9.0,4.0,3.0,12.0,5.0,7.0,14.0,NaN,14.0,1.0,13.0,10.0,9.0,3.0,4.0,2.0,5.0,15.0,NaN,Retail and Consumer Services,10.0,8.0,3.0,9.0,12.0,1.0,6.0,2.0,11.0,4.0,7.0,13.0,14.0,15.0,5.0,NaN,I'm not sure,I have transitioned into a new career and/or i...,6.0,5.0,Netherlands,EUR European Euro,90000.0,Yes,Java,Java;Python;Swift,Java,NaN,NaN,Yes,Dynamodb;MongoDB,Dynamodb;MongoDB,Dynamodb;MongoDB,NaN,NaN,Yes,Amazon Web Services (AWS);Datadog;Docker;Homeb...,Amazon Web Services (AWS);Datadog;Docker;Homeb...,Amazon Web Services (AWS);Datadog;Docker;Homeb...,NaN,NaN,Yes,Spring Boot,Spring Boot,Spring Boot,NaN,NaN,Yes,IntelliJ IDEA;PyCharm;Visual Studio Code;Xcode,IntelliJ IDEA;PyCharm;Visual Studio Code;Xcode,IntelliJ IDEA;PyCharm;Visual Studio Code;Xcode,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Windows;MacOS;iOS;iPadOS,MacOS,Confluence;GitHub;Jira,Confluence;GitHub;Jira,Confluence;GitHub;Jira,NaN,NaN,Stack Overflow;Discord;Reddit;Dev.to;Hacker Ne...,Stack Overflow;Discord;Reddit;Dev.to;Hacker Ne...,Stack Overflow;Discord;Reddit;Dev.to;Hacker Ne...,NaN,NaN,Yes,openAI GPT (chatbot models),openAI GPT (chatbot models),openAI GPT (chatbot models),NaN,NaN,Not sure/can't remember,Multiple times per day,Between 10 and 15 years,"Infrequently, less than once per year",Chat (people);Message Boards;Long-form article...,6.0,NaN,5.0,8.0,2.0,4.0,9.0,10.0,11.0,15.0,NaN,"Yes, somewhat",About half of the time,"Yes, I use AI tools weekly",Indifferent,Neither trust nor distrust,Bad at handling complex tasks,Learning new concepts or technologies,Learning about a codebase;Project planning;Com...,Writing code;Documenting code;Debugging or fix...,NaN,NaN,"AI solutions that are almost right, but not qu...",No,"No, and I don't plan to",Not at all or minimally,NaN,NaN,NaN,NaN,NaN,NaN,NaN,It takes significant time and effort to learn ...,NaN,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,All skills. AI is a flop.,104413.0,9.0
2,3,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Independent contractor, freelancer, or self-em...",None of the above,10.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Technical ...,12.0,"Developer, front-end",NaN,NaN,NaN,No,Work,12.0,2.0,3.0,7.0,5.0,10.0,13.0,1.0,4.0,14.0,NaN,8.0,1.0,2.0,12.0,13.0,3.0,9.0,4.0,11.0,15.0,NaN,Software Development,9.0,6.0,7.0,11.0,8.0,12.0,1.0,5.0,2.0,4.0,3.0,13.0,14.0,15.0,10.0,NaN,No,I have transitioned into a new career and/or i...,3.0,3.0,Ukraine,UAH Ukrainian hryvnia,2214000.0,Yes,Dart;HTML/CSS;JavaScript;TypeScript,Dart;HTML/CSS;JavaScript;TypeScript,Dart;HTML/CSS;JavaScript;TypeScript,NaN,NaN,Yes,MongoDB;MySQL;PostgreSQL,Firebase Realtime Database;MongoDB,MongoDB,NaN,NaN,Yes,Datadog;Firebase;npm;pnpm,Amazon Web Services (AWS);Firebase;npm;pnpm;Vite,Firebase;npm;pnpm,NaN,NaN,Yes,Next.js;Node.js;React,Next.js;Node.js;React,Next.js;Node.js;React,NaN,Solid.js,Yes,Visual Studio Code,Visual Studio Code;Windsurf,Visual Studio Code,NaN,NaN,Google Gemini,Google Gemini;Shadcn/ui,Google Gemini,NaN,NaN,MacOS;Android,MacOS,GitHub;GitLab;Jira,GitHub;GitLab;Jira,GitHub;GitLab;Jira,NaN,NaN,Stack Overflow;Discord;Dev.to;X;YouTube;LinkedIn,Stack Overflow;Discord;Dev.to;X;YouTube;LinkedIn,Stack Overflow;Discord;Dev.to;X;YouTube;LinkedIn,NaN,NaN,Yes,Gemini (Flash general purpose models);openAI G...,Gemini (Flash general purpose models);Gemini (...,Gemini (Flash general purpose models);openAI G...,NaN,NaN,Not sure/can't remember,A few times per week,Between 5 and 10 years,"Infrequently, less than once per year",Chat (people);Videos;Lists of recommendations ...,3.0,NaN,4.0,5.0,1.0,2.0,7.0,9.0,11.0,15.0,NaN,Neutral,About half of the time,"Yes, I use AI tools daily",Favorable,Somewhat trust,Neither good or bad at handling complex tasks,Documenting code;Debugging or fixing code;Test...,NaN,Project planning;Committing and reviewing code...,Learning about a codebase;Writing code;Generat...,NaN,"AI solutions that are almost right, but not qu...",No,"Yes, I use AI agents at work weekly","Yes, somewhat",Software engineering,Multi-platform search enablement,AI agents have increased my productivity.;AI a...,AI agents have improved the quality of my code...,AI agents have improved collaboration within m...,NaN,NaN,It takes significant time and effort to learn ...,My company's IT and/or InfoSec teams have stri...,NaN,I am concerned about the accuracy of the infor...,NaN,Redis,NaN,NaN,NaN,NaN,NaN,ChatGPT;Claude Code;GitHub Copilot;Google Gemini,NaN,When I don’t trust AI’s answers;When I want to...,"Understand how things actually work, problem s...",53061.0,8.0
4,5,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...","Caring for dependents (children, elderly, etc.)",21.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools for...",Technical documentation (is generated for/by t...,22.0,Engineering manager,NaN,NaN,NaN,"Yes, I endorsed a tool that was open-source an...",Work,6.0,3.0,1.0,9.0,10.0,8.0,7.0,4.0,2.0,14.0,NaN,7.0,13.0,3.0,9.0,12.0,6.0,1.0,8.0,14.0,15.0,NaN,Software Development,9.0,4.0,11.0,13.0,14.0,8.0,6.0,5.0,7.0,2.0,1.0,12.0,10.0,15.0,3.0,NaN,No,I have neither consider or transitioned into a...,4.0,3.0,Ukraine,USD United States dollar,60000.0,Yes,C;C#;C++;Delphi;HTML/CSS;Java;JavaScript;Lua;P...,C#;Java;JavaScript;Python;SQL;TypeScript,C#;Java;JavaScript;Python;SQL;TypeScript,NaN,NaN,Yes,Elasticsearch;Microsoft SQL Server;MySQL;Oracl...,Elasticsearch;Oracle;PostgreSQL,Elasticsearch;Oracle;PostgreSQL,NaN,NaN,Yes,Amazon Web Services (AWS);APT;Docker;Make;Mave...,Amazon Web Services (AWS);APT;Docker;Maven (bu...,Amazon Web Services (AWS);APT;Docker;Maven (bu...,NaN,NaN,Yes,Angular;ASP.NET;ASP.NET Core;Flask;jQuery,Angular;ASP.NET Core;Flask,Angular;ASP.NET Core;Flask,NaN,NaN,Yes,Eclipse;IntelliJ IDEA;Jupyter Notebook/Jupyter...,IntelliJ IDEA;Jupyter Notebook/JupyterLab;Note...,IntelliJ IDEA;Jupyter Notebook/JupyterLab;Note...,NaN,NaN,Large Language Model;Google Gemini,Large Language Model,Large Language Model,NaN,NaN,Windows;iOS,Windows;Ubuntu;Debian,Azure Devops;GitHub;Jira,Azure Devops;GitHub;Jira,Azure Devops;GitHub;Jira,NaN,NaN,Stack Overflow;Stack Exchange;GitHub (public p...,Stack Overflow;Stack Exchange;GitHub (public p...,Stack Overflow;Stack Exchange;GitHub (public p...,NaN,NaN,Yes,openAI GPT (chatbot models),openAI GPT (chatbot models),openAI GPT (chatbot models),NaN,NaN,No,A few times per month or weekly,Between 5 and 10 years,"Infrequently, less than once per year",Long-form articles,1.0,NaN,7.0,4.0,2.0,5.0,10.0,6.0,12.0,15.0,NaN,"No, not really","Rarely, almost never","Yes, I use AI tools weekly",Favorable,Neither trust nor distrust,"Good, but not great at handling complex tasks",Learning about a codebase;Writing code;Debuggi...,Project planning;Documenting code;Testing code...,Generating content or synthetic data,NaN,NaN,"AI solutions that are almost right, but not quite",partly,"No, and I don't plan to","Yes, to a great extent",NaN,NaN,NaN,NaN,NaN,NaN,NaN,Integrating AI agents with my existing tools a...,NaN,I am concerned about the accuracy of the infor...,It takes significant time and effort to learn ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers,"critical thinking, the skill to define the tas...",60000.0,7.0
5,6,I am a developer by profession,45-54 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...","Caring for dependents (children, elderly, etc....",15.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools req...",Technical documentation (is generated for/by t...,20.0,"Developer, back-end",NaN,NaN,NaN,"Yes, I influenced the purchase of a substantia...",Work,12.0,5.0,4.0,6.0,2.0,10.0,3.0,7.0,8.0,14.0,NaN,12.0,5.0,13.0,10.0,9.0,1.0,4.0,6.0,2.0,15.0,NaN,Fintech,4.0,3.0,5.0,8.0,9.0,2.0,1.0,10.0,11.0,12.0,6.0,13.0,14.0,15.0,7.0,NaN,I'm not sure,I have somewhat considered changing my career ...,5.0,5.0,Ukraine,USD United States dollar,120000.0,Yes,Java;Scala,Java;Kotlin;Scala,Java;Scala,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,Amazon Web Services (AWS);Google Cloud;Microso...,Amazon Web Services (AWS),Amazon Web Services (AWS),NaN,NaN,Yes,Spring Boot,Spring Boot,Spring Boot,akka,akka,Yes,IntelliJ IDEA;Visual Studio Code,IntelliJ IDEA;Visual Studio Code,IntelliJ IDEA;Visual Studio Code,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MacOS,MacOS,Azure Devops;GitHub;GitLab;Jira,GitHub;Jira,GitHub;Jira,NaN,NaN,Stack Overflow;Stack Exchange;X;YouTube;Linked...,Stack Overflow;Stack Exchange;X;YouTube;Linked...,Stack Overflow;Stack Exchange;X;YouTube;Linked...,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,A few times per month or weekly,Between 10 and 15 years,"Infrequently, less than once per year","Lists of recommendations (tools, frameworks, t...",6.0,NaN,9.0,3.0,4.0,5.0,10.0,1.0,11.0,15.0,NaN,"Yes, somewhat","Rarely, almost never","Yes, I use AI tools daily",Indifferent,Somewhat distrust,"Good, but not great at handling complex tasks",Learning about a codebase;Writing code;Documen...,Predictive analytics,Deployment and monitoring,Project planning;Debugging or fixing code;Comm...,Testing code;Learning new concepts or technolo...,"AI solutions that are almost right, but not quite",No it isnt,"Yes, I use AI agents at work monthly or infreq...",Not at all or minimally,Software engineering;Business process automati...,NaN,AI agents have increased my productivity.;AI a...,NaN,AI agents have improved the quality of my code...,AI agents have helped me automate repetitive t...,NaN,The cost of using certain AI agent platforms i...,NaN,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,My company's IT and/or InfoSec teams have stri...,NaN,NaN,NaN,NaN,NaN,NaN,GitHub Copilot,NaN,When I have ethical or security concerns about...,designing the architecture in the new domain,120000.0,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49083,49084,"I am not primarily a developer, but I write co...",35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,22.0,"No, I am not new to coding and did not learn n...",NaN,"No, I didn't spend time learning in the past year",NaN,5.0,DevOps engineer or professional,"10,000 or more employees",Individual contributor,Remote,No,Work,8.0,4.0,7.0,9.0,1.0,6.0,2.0,5.0,3.0,10.0,NaN,6.0,8.0,5.0,9.0,1.0,3.0,2.0,7.0,4.0,10.0,NaN,Retail and Consumer Services,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,I'm not sure,I have neither consider or transitioned into a...,NaN,NaN,United States of America,USD United States dollar,188000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Yes, I use AI tools daily",Favorable,Highly trust,Bad at handling complex tasks,NaN,NaN,NaN,NaN,NaN,Debugging AI-generated code is more time-consu...,NaN,"No, but I plan to",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,188000.0,NaN
49084,49085,"I am not primarily a developer, but I write co...",55-64 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Not employed,None of the above,46.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"No, I didn't spend time learning in the past year",NaN,8.0,"Developer, QA or test",NaN,NaN,NaN,NaN,Personal Project,9.0,3.0,6.0,4.0,5.0,2.0,8.0,7.0,1.0,10.0,NaN,7.0,5.0,9.0,8.0,3.0,1.0,6.0,2.0,4.0,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,I'm not sure,I have somewhat considered changing my career ...,NaN,4.0,United States of America,USD United States dollar,119000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,A few times per week,Between 3 and 5 years,I have never participated in Q&A on Stack Over...,NaN,3.0,1.0,2.0,6.0,4.0,5.0,7.0,9.0,8.0,10.0,NaN,"No, not really","Rarely, almost never","No, but I plan to soon",Favorable,Somewhat trust,Neither good or bad at handling complex tasks,Search for answers;Generating content or synth...,Project planning;Deployment and monitoring;Pre...,Learning about a codebase;Writing code;Documen...,NaN,NaN,I haven’t encountered any problems,It is not.,"No, but I plan to",Not at all or minimally,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,119000.0,NaN

In [34]:
df.loc[high_salary, ['Country','Employment','CompTotal']]

,Country,Employment,CompTotal
0,Ukraine,Employed,52800.0
1,Netherlands,Employed,90000.0
2,Ukraine,"Independent contractor, freelancer, or self-em...",2214000.0
4,Ukraine,"Independent contractor, freelancer, or self-em...",60000.0
5,Ukraine,"Independent contractor, freelancer, or self-em...",120000.0
...,...,...,...
49083,United States of America,Employed,188000.0
49084,United States of America,Not employed,119000.0
49088,United States of America,Employed,280000.0
49106,South Africa,Employed,1224000.0
49121,France,Employed,50000.0

In [35]:
#filtering with multiple values
countries = ['United states', 'India', 'United Kingdom', 'Germany','Canada']
filt_country = df['Country'].isin(countries)

In [36]:
df.loc[filt_country, 'Country']

13         India
15         India
18       Germany
35       Germany
46         India
          ...
49154      India
49155      India
49175    Germany
49178    Germany
49180     Canada
Name: Country, Length: 6877, dtype: str

In [37]:
df['LanguageHaveWorkedWith']

0                         Bash/Shell (all shells);Dart;SQL
1                                                     Java
2                      Dart;HTML/CSS;JavaScript;TypeScript
3                                          Java;Kotlin;SQL
4        C;C#;C++;Delphi;HTML/CSS;Java;JavaScript;Lua;P...
                               ...
49186                                                  NaN
49187                                                  NaN
49188                                                  NaN
49189                                                  NaN
49190                                                  NaN
Name: LanguageHaveWorkedWith, Length: 49191, dtype: str

In [38]:
#using string method
filt_lang = df['LanguageHaveWorkedWith'].str.contains('Python',na=False)

In [39]:
df.loc[filt_lang,'LanguageHaveWorkedWith']

4        C;C#;C++;Delphi;HTML/CSS;Java;JavaScript;Lua;P...
7        Bash/Shell (all shells);HTML/CSS;JavaScript;Py...
8                                        Java;Python;Scala
15       Ada;Assembly;C;C#;C++;COBOL;Dart;Delphi;Elixir...
17                          HTML/CSS;JavaScript;Python;SQL
                               ...
49143            HTML/CSS;JavaScript;Python;SQL;TypeScript
49145    Assembly;Bash/Shell (all shells);C;C++;Python;...
49175    Bash/Shell (all shells);C#;C++;GDScript;HTML/C...
49176    Bash/Shell (all shells);HTML/CSS;JavaScript;Py...
49177    Bash/Shell (all shells);HTML/CSS;Lisp;PowerShe...
Name: LanguageHaveWorkedWith, Length: 18466, dtype: str

In [40]:
#true and false value provides a mask of the data returned

In [41]:
#renaming comptotal to salary
df.rename(columns={
    'CompTotal':'SalaryUSD'
},inplace=True)

In [42]:
df['SalaryUSD']

0          52800.0
1          90000.0
2        2214000.0
3          31200.0
4          60000.0
           ...
49186          NaN
49187          NaN
49188      80000.0
49189          NaN
49190          NaN
Name: SalaryUSD, Length: 49191, dtype: float64

In [43]:
df

,ResponseId,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,AILearnHow,YearsCode,DevType,OrgSize,ICorPM,RemoteWork,PurchaseInfluence,TechEndorseIntro,TechEndorse_1,TechEndorse_2,TechEndorse_3,TechEndorse_4,TechEndorse_5,TechEndorse_6,TechEndorse_7,TechEndorse_8,TechEndorse_9,TechEndorse_13,TechEndorse_13_TEXT,TechOppose_1,TechOppose_2,TechOppose_3,TechOppose_5,TechOppose_7,TechOppose_9,TechOppose_11,TechOppose_13,TechOppose_16,TechOppose_15,TechOppose_15_TEXT,Industry,JobSatPoints_1,JobSatPoints_2,JobSatPoints_3,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,JobSatPoints_13,JobSatPoints_14,JobSatPoints_15,JobSatPoints_16,JobSatPoints_15_TEXT,AIThreat,NewRole,ToolCountWork,ToolCountPersonal,Country,Currency,SalaryUSD,LanguageChoice,LanguageHaveWorkedWith,LanguageWantToWorkWith,LanguageAdmired,LanguagesHaveEntry,LanguagesWantEntry,DatabaseChoice,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,DatabaseAdmired,DatabaseHaveEntry,DatabaseWantEntry,PlatformChoice,PlatformHaveWorkedWith,PlatformWantToWorkWith,PlatformAdmired,PlatformHaveEntry,PlatformWantEntry,WebframeChoice,WebframeHaveWorkedWith,WebframeWantToWorkWith,WebframeAdmired,WebframeHaveEntry,WebframeWantEntry,DevEnvsChoice,DevEnvsHaveWorkedWith,DevEnvsWantToWorkWith,DevEnvsAdmired,DevEnvHaveEntry,DevEnvWantEntry,SOTagsHaveWorkedWith,SOTagsWantToWorkWith,SOTagsAdmired,SOTagsHaveEntry,SOTagsWant Entry,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackAsyncAdmired,OfficeStackHaveEntry,OfficeStackWantEntry,CommPlatformHaveWorkedWith,CommPlatformWantToWorkWith,CommPlatformAdmired,CommPlatformHaveEntr,CommPlatformWantEntr,AIModelsChoice,AIModelsHaveWorkedWith,AIModelsWantToWorkWith,AIModelsAdmired,AIModelsHaveEntry,AIModelsWantEntry,SOAccount,SOVisitFreq,SODuration,SOPartFreq,SO_Dev_Content,SO_Actions_1,SO_Actions_16,SO_Actions_3,SO_Actions_4,SO_Actions_5,SO_Actions_6,SO_Actions_9,SO_Actions_7,SO_Actions_10,SO_Actions_15,SO_Actions_15_TEXT,SOComm,SOFriction,AISelect,AISent,AIAcc,AIComplex,AIToolCurrently partially AI,AIToolDon't plan to use AI for this task,AIToolPlan to partially use AI,AIToolPlan to mostly use AI,AIToolCurrently mostly AI,AIFrustration,AIExplain,AIAgents,AIAgentChange,AIAgent_Uses,AgentUsesGeneral,AIAgentImpactSomewhat agree,AIAgentImpactNeutral,AIAgentImpactSomewhat disagree,AIAgentImpactStrongly agree,AIAgentImpactStrongly disagree,AIAgentChallengesNeutral,AIAgentChallengesSomewhat disagree,AIAgentChallengesStrongly agree,AIAgentChallengesSomewhat agree,AIAgentChallengesStrongly disagree,AIAgentKnowledge,AIAgentKnowWrite,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
0,1,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,"Caring for dependents (children, elderly, etc.)",8.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,14.0,"Developer, mobile",20 to 99 employees,People manager,Remote,"Yes, I influenced the purchase of a substantia...",Work,10.0,7.0,9.0,6.0,3.0,11.0,12.0,1.0,8.0,14.0,NaN,15.0,7.0,8.0,12.0,11.0,1.0,6.0,13.0,3.0,16.0,NaN,Fintech,3.0,1.0,4.0,9.0,5.0,10.0,12.0,11.0,2.0,6.0,7.0,13.0,14.0,15.0,8.0,NaN,I'm not sure,I have neither consider or transitioned into a...,7.0,3.0,Ukraine,EUR European Euro,52800.0,Yes,Bash/Shell (all shells);Dart;SQL,Dart,Dart,NaN,NaN,Yes,Cloud Firestore;PostgreSQL,NaN,NaN,NaN,NaN,Yes,Amazon Web Services (AWS);Cloudflare;Firebase;...,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,Android Studio;Notepad++;Visual Studio;Visual ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Windows;MacOS;Android,Windows;MacOS;Android;iOS;iPadOS,Confluence;GitHub;GitLab;Jira;Markdown File,Markdown File,Markdown File,NaN,NaN,"Stack Overflow;Reddit;GitHub (public projects,...",NaN,NaN,NaN,NaN,Yes,openAI GPT (chatbot models);openAI Image gener...,NaN,NaN,NaN,NaN,Yes,A few times per week,Between 5 and 10 years,I have never participated in Q&A on Stack Over...,NaN,1.0,NaN,6.0,2.0,3.0,7.0,8.0,9.0,11.0,15.0,NaN,Neutral,"Rarely, almost never","Yes, I use AI tools monthly or infrequently",Indifferent,Neither trust nor distrust,Bad at handling complex tasks,Learning about a codebase;Writing code;Search ...,Project planning;Deployment and monitoring;Lea...,Documenting code;Debugging or fixing code;Test...,NaN,NaN,"AI solutions that are almost right, but not quite",No,"Yes, I use AI agents at work monthly or infreq...",Not at all or minimally,Software engineering,NaN,AI agents have increased my productivity.;AI a...,AI agents have helped me automate repetitive t...,NaN,NaN,NaN,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,The cost of using certain AI agent platforms i...,NaN,NaN,NaN,NaN,Vertex AI,NaN,NaN,NaN,ChatGPT,NaN,When I don’t trust AI’s answers,"Troubleshooting, profiling, debugging",61256.0,10.0
1,2,I am a developer by profession,25-34 years old,"Associate degree (A.A., A.S., etc.)",Employed,NaN,2.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,10.0,"Developer, back-end",500 to 999 employees,Individual contributor,"Hybrid (some in-person, leans heavy to flexibi...",No,Personal Project,13.0,1.0,2.0,9.0,4.0,3.0,12.0,5.0,7.0,14.0,NaN,14.0,1.0,13.0,10.0,9.0,3.0,4.0,2.0,5.0,15.0,NaN,Retail and Consumer Services,10.0,8.0,3.0,9.0,12.0,1.0,6.0,2.0,11.0,4.0,7.0,13.0,14.0,15.0,5.0,NaN,I'm not sure,I have transitioned into a new career and/or i...,6.0,5.0,Netherlands,EUR European Euro,90000.0,Yes,Java,Java;Python;Swift,Java,NaN,NaN,Yes,Dynamodb;MongoDB,Dynamodb;MongoDB,Dynamodb;MongoDB,NaN,NaN,Yes,Amazon Web Services (AWS);Datadog;Docker;Homeb...,Amazon Web Services (AWS);Datadog;Docker;Homeb...,Amazon Web Services (AWS);Datadog;Docker;Homeb...,NaN,NaN,Yes,Spring Boot,Spring Boot,Spring Boot,NaN,NaN,Yes,IntelliJ IDEA;PyCharm;Visual Studio Code;Xcode,IntelliJ IDEA;PyCharm;Visual Studio Code;Xcode,IntelliJ IDEA;PyCharm;Visual Studio Code;Xcode,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Windows;MacOS;iOS;iPadOS,MacOS,Confluence;GitHub;Jira,Confluence;GitHub;Jira,Confluence;GitHub;Jira,NaN,NaN,Stack Overflow;Discord;Reddit;Dev.to;Hacker Ne...,Stack Overflow;Discord;Reddit;Dev.to;Hacker Ne...,Stack Overflow;Discord;Reddit;Dev.to;Hacker Ne...,NaN,NaN,Yes,openAI GPT (chatbot models),openAI GPT (chatbot models),openAI GPT (chatbot models),NaN,NaN,Not sure/can't remember,Multiple times per day,Between 10 and 15 years,"Infrequently, less than once per year",Chat (people);Message Boards;Long-form article...,6.0,NaN,5.0,8.0,2.0,4.0,9.0,10.0,11.0,15.0,NaN,"Yes, somewhat",About half of the time,"Yes, I use AI tools weekly",Indifferent,Neither trust nor distrust,Bad at handling complex tasks,Learning new concepts or technologies,Learning about a codebase;Project planning;Com...,Writing code;Documenting code;Debugging or fix...,NaN,NaN,"AI solutions that are almost right, but not qu...",No,"No, and I don't plan to",Not at all or minimally,NaN,NaN,NaN,NaN,NaN,NaN,NaN,It takes significant time and effort to learn ...,NaN,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,All skills. AI is a flop.,104413.0,9.0
2,3,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Independent contractor, freelancer, or self-em...",None of the above,10.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Technical ...,12.0,"Developer, front-end",NaN,NaN,NaN,No,Work,12.0,2.0,3.0,7.0,5.0,10.0,13.0,1.0,4.0,14.0,NaN,8.0,1.0,2.0,12.0,13.0,3.0,9.0,4.0,11.0,15.0,NaN,Software Development,9.0,6.0,7.0,11.0,8.0,12.0,1.0,5.0,2.0,4.0,3.0,13.0,14.0,15.0,10.0,NaN,No,I have transitioned into a new career and/or i...,3.0,3.0,Ukraine,UAH Ukrainian hryvnia,2214000.0,Yes,Dart;HTML/CSS;JavaScript;TypeScript,Dart;HTML/CSS;JavaScript;TypeScript,Dart;HTML/CSS;JavaScript;TypeScript,NaN,NaN,Yes,MongoDB;MySQL;PostgreSQL,Firebase Realtime Database;MongoDB,MongoDB,NaN,NaN,Yes,Datadog;Firebase;npm;pnpm,Amazon Web Services (AWS);Firebase;npm;pnpm;Vite,Firebase;npm;pnpm,NaN,NaN,Yes,Next.js;Node.js;React,Next.js;Node.js;React,Next.js;Node.js;React,NaN,Solid.js,Yes,Visual Studio Code,Visual Studio Code;Windsurf,Visual Studio Code,NaN,NaN,Google Gemini,Google Gemini;Shadcn/ui,Google Gemini,NaN,NaN,MacOS;Android,MacOS,GitHub;GitLab;Jira,GitHub;GitLab;Jira,GitHub;GitLab;Jira,NaN,NaN,Stack Overflow;Discord;Dev.to;X;YouTube;LinkedIn,Stack Overflow;Discord;Dev.to;X;YouTube;LinkedIn,Stack Overflow;Discord;Dev.to;X;YouTube;LinkedIn,NaN,NaN,Yes,Gemini (Flash general purpose models);openAI G...,Gemini (Flash general purpose models);Gemini (...,Gemini (Flash general purpose models);openAI G...,NaN,NaN,Not sure/can't remember,A few times per week,Between 5 and 10 years,"Infrequently, less than once per year",Chat (people);Videos;Lists of recommendations ...,3.0,NaN,4.0,5.0,1.0,2.0,7.0,9.0,11.0,15.0,NaN,Neutral,About half of the time,"Yes, I use AI tools daily",Favorable,Somewhat trust,Neither good or bad at handling complex tasks,Documenting code;Debugging or fixing code;Test...,NaN,Project planning;Committing and reviewing code...,Learning about a codebase;Writing code;Generat...,NaN,"AI solutions that are almost right, but not qu...",No,"Yes, I use AI agents at work weekly","Yes, somewhat",Software engineering,Multi-platform search enablement,AI agents have increased my productivity.;AI a...,AI agents have improved the quality of my code...,AI agents have improved collaboration within m...,NaN,NaN,It takes significant time and effort to learn ...,My company's IT and/or InfoSec teams have stri...,NaN,I am concerned about the accuracy of the infor...,NaN,Redis,NaN,NaN,NaN,NaN,NaN,ChatGPT;Claude Code;GitHub Copilot;Google Gemini,NaN,When I don’t trust AI’s answers;When I want to...,"Understand how things actually work, problem s...",53061.0,8.0
3,4,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,4.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Videos (no...,5.0,"Developer, back-end","10,000 or more employees",Individual contributor,Remote,No,Personal Project,2.0,12.0,6.0,5.0,13.0,3.0,8.0,11.0,7.0,14.0,NaN,10.0,5.0,8.0,4.0,13.0,12.0,2.0,7.0,1.0,15.0,NaN,Retail and Consumer Services,1.0,2.0,4.0,5.0,6.0,7.0,8.0,9.0,10.0,11.0,12.0,13.0,14.0,15.0,3.0,NaN,No,I have neither consider or transitioned into a...,NaN,NaN,Ukraine,EUR European Euro,31200.0,Yes,Java;Kotlin;SQL,Java;Kotlin,Java;Kotlin,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,Amazon Web Services (AWS);Google Cloud,Amazon Web Services (AWS);Google Cloud,Amazon Web Services (AWS);Google Cloud,NaN,NaN,Yes,Spring Boot,Spring Boot,Spring Boot,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Amazon Bedrock,NaN,NaN,NaN,NaN,Windows,Windows;Ubuntu,GitLab;Jira;Miro,GitLab;Jira,GitLab;Jira,NaN,NaN,Stack Overflow;Reddit;YouTube;LinkedIn,"Stack Overflow;Reddit;GitHub (public projects,...",Stack Overflow;Reddit;YouTube;LinkedIn,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,A few times per month or weekly,Between 3 and 5 years,I have never participated in Q&A on Stack Over...,Videos;Chat (bot/AI),1.0,NaN,4.0,5.0,6.0,7.0,8.0,9.0,11.0,15.0,NaN,Neutral,"Rarely, almost never","Yes, I use AI tools weekly",Favorable,Somewhat trust,Bad at handling complex tasks,NaN,Project planning;Documenting code;Testing code...,Learning about a codebase;Writing code;Debuggi...,Search for answers;Generating content or synth...,NaN,"AI solutions that are almost right, but not qu...",NO,"Yes, I use AI agents at work monthly or infreq...",Not at all or minimally,Software engineering,Language processing,AI agents have accelerated my learning about n...,AI agents have increased my productivity.;AI a...,AI agents have helped me automate repetitive t...,NaN,NaN,It takes significant time and effort to learn ...,NaN,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ChatGPT;Claude Code,NaN,When I don’t trust AI’s answers;When I want to...,NaN,36197.0,6.0
4,5,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...","Caring for dependents (children, elderly, etc.)",21.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools for...",Technical documentation (is generated for/by t...,22.0,Engineering manager,NaN,NaN,NaN,"Yes, I endorsed a tool that was open-source an...",Work,6.0,3.0,1.0,9.0,10.0,8.0,7.0,4.0,2.0,14.0,NaN,7.0,13.0,3.0,9.0,12.0,6.0,1.0,8.0,14.0,15.0,NaN,Software Development,9.0,4.0,11.0,13.0,14.0,8.0,6.0,5.0,7.0,2.0,1.0,12.0,10.0,15.0,3.0,NaN,No,I have neither consider or transitioned into a...,4.0,3.0,Ukraine,USD United States dollar,60000.0,Yes,C;C#;C++;Delphi;HTML/CSS;Java;JavaScript;Lua;P...,C#;Java;JavaScript;Python;SQL;TypeScript,C#;Java;JavaScript;Python;SQL;TypeScript,NaN,NaN,Yes,Elasticsearch;Microsoft SQL Server;MySQL;Oracl...,Elasticsearch;Oracle;PostgreSQL,Elasticsearch;Oracle;PostgreSQL,NaN,NaN,Yes,Amazon Web Services (AWS);APT;Docker;Make;Mave...,Amazon Web Services (AWS);APT;Docker;Maven (bu...,Amazon Web Services (AWS);APT;Docker;Maven (bu...,NaN,NaN,Yes,Angular;ASP.NET;ASP.NET Core;Flask;jQuery,Angular;ASP.NET Core;Flask,Angular;ASP.NET Core;Flask,NaN,NaN,Yes,Eclipse;IntelliJ IDEA;Jupyter Notebook/Jupyter...,IntelliJ IDEA;Jupyter Notebook/JupyterLab;Note...,IntelliJ IDEA;Jupyter Notebook/JupyterLab;Note...,NaN,NaN,Large Language Model;Google Gemini,Large Language Model,Large Language Model,NaN,NaN,Windows;iOS,Windows;Ubuntu;Debian,Azure Devops;GitHub;Jira,Azure Devops;GitHub;Jira,Azure Devops;GitHub;Jira,NaN,NaN,Stack Overflow;Stack Exchange;GitHub (public p...,Stack Overflow;Stack Exchange;GitHub (public p...,Stack Overflow;Stack Exchange;GitHub (public p...,NaN,NaN,Yes,openAI GPT (chatbot models),openAI GPT (chatbot models),openAI GPT (chatbot models),NaN,NaN,No,A few times per month or weekly,Between 5 and 10 years,"Infrequently, less than once per year",Long-form articles,1.0,NaN,7.0,4.0,2.0,5.0,10.0,6.0,12.0,15.0,NaN,"No, not really","Rarely, almost never","Yes, I use AI tools weekly",Favorable,Neither trust nor distrust,"Good, but not great at handling complex tasks",Learning about a codebase;Writing code;Debuggi...,Project planning;Documenting code;Testing code...,Generating content or synthetic data,NaN,NaN,"AI solutions that are almost right, but not quite",partly,"No, and I don't plan to","Yes, to a great extent",NaN,NaN,NaN,NaN,NaN,NaN,NaN,Integrating AI agents with my existing tools a...,NaN,I am concerned about the accuracy of the infor...,It takes significant time and effort to learn ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers,"critical thinking, the skill to define the tas...",60000.0,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49186,49187,I code primarily as a hobby,18-24 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49187,49188,I am a developer by profession,45-54 years old,Some college/university study without earning ...,Employed,"Caring for dependents (children, elderly, etc.)",25.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools req...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49188,49189,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,None of the above,17.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Videos (no...,31.0,"Architect, software or solutions","10,000 or more employees",People manager,"Hybrid (some in-person, leans heavy to flexibi...","Yes, I endorsed a tool that was open-source an...",Personal Project,9.0,2.0,1.0,5.0,3.0,7.0,8.0,4.0,6.0,10.0,NaN,9.0,6.0,2.0,7.0,5.0,4.0,1.0,3.0,8.0,10.0,NaN,Banking/Financial Services,3.0,6.0,7.0,13.0,4.0,9.0,1.0,10.0,2.0,5.0,8.0,11.0,12.0,15.0,14.0,NaN,No,I have somewhat considered changing my career ...,25.0,35.0,Italy,EUR European Euro,80000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Yes, I use AI tools monthly or infrequently",Favorable,Neither trust nor distrust,"Good, but not great at handling complex tasks",Learning about a codebase;Writing code;Documen...,Debugging or fixing code,Project planning;Deployment and monitoring;Pre...,NaN,Search for answers,"AI solutions that are almost right, but not qu...","Yes, partially.","No, I use AI exclusively in copilot/autocomple...",Not at all or minimally,NaN,NaN,NaN,NaN,NaN,NaN,AI agents have increased my productivity.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0

In [44]:
df['PurchaseInfluence'].map({
    'Yes': True,
    'No' : False,
})

0          NaN
1        False
2        False
3        False
4          NaN
         ...
49186      NaN
49187      NaN
49188      NaN
49189      NaN
49190      NaN
Name: PurchaseInfluence, Length: 49191, dtype: object

In [45]:
df['PurchaseInfluence'] = df['PurchaseInfluence'].map({
    'Yes': True,
    'No' : False,
})

In [46]:
df

,ResponseId,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,AILearnHow,YearsCode,DevType,OrgSize,ICorPM,RemoteWork,PurchaseInfluence,TechEndorseIntro,TechEndorse_1,TechEndorse_2,TechEndorse_3,TechEndorse_4,TechEndorse_5,TechEndorse_6,TechEndorse_7,TechEndorse_8,TechEndorse_9,TechEndorse_13,TechEndorse_13_TEXT,TechOppose_1,TechOppose_2,TechOppose_3,TechOppose_5,TechOppose_7,TechOppose_9,TechOppose_11,TechOppose_13,TechOppose_16,TechOppose_15,TechOppose_15_TEXT,Industry,JobSatPoints_1,JobSatPoints_2,JobSatPoints_3,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,JobSatPoints_13,JobSatPoints_14,JobSatPoints_15,JobSatPoints_16,JobSatPoints_15_TEXT,AIThreat,NewRole,ToolCountWork,ToolCountPersonal,Country,Currency,SalaryUSD,LanguageChoice,LanguageHaveWorkedWith,LanguageWantToWorkWith,LanguageAdmired,LanguagesHaveEntry,LanguagesWantEntry,DatabaseChoice,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,DatabaseAdmired,DatabaseHaveEntry,DatabaseWantEntry,PlatformChoice,PlatformHaveWorkedWith,PlatformWantToWorkWith,PlatformAdmired,PlatformHaveEntry,PlatformWantEntry,WebframeChoice,WebframeHaveWorkedWith,WebframeWantToWorkWith,WebframeAdmired,WebframeHaveEntry,WebframeWantEntry,DevEnvsChoice,DevEnvsHaveWorkedWith,DevEnvsWantToWorkWith,DevEnvsAdmired,DevEnvHaveEntry,DevEnvWantEntry,SOTagsHaveWorkedWith,SOTagsWantToWorkWith,SOTagsAdmired,SOTagsHaveEntry,SOTagsWant Entry,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackAsyncAdmired,OfficeStackHaveEntry,OfficeStackWantEntry,CommPlatformHaveWorkedWith,CommPlatformWantToWorkWith,CommPlatformAdmired,CommPlatformHaveEntr,CommPlatformWantEntr,AIModelsChoice,AIModelsHaveWorkedWith,AIModelsWantToWorkWith,AIModelsAdmired,AIModelsHaveEntry,AIModelsWantEntry,SOAccount,SOVisitFreq,SODuration,SOPartFreq,SO_Dev_Content,SO_Actions_1,SO_Actions_16,SO_Actions_3,SO_Actions_4,SO_Actions_5,SO_Actions_6,SO_Actions_9,SO_Actions_7,SO_Actions_10,SO_Actions_15,SO_Actions_15_TEXT,SOComm,SOFriction,AISelect,AISent,AIAcc,AIComplex,AIToolCurrently partially AI,AIToolDon't plan to use AI for this task,AIToolPlan to partially use AI,AIToolPlan to mostly use AI,AIToolCurrently mostly AI,AIFrustration,AIExplain,AIAgents,AIAgentChange,AIAgent_Uses,AgentUsesGeneral,AIAgentImpactSomewhat agree,AIAgentImpactNeutral,AIAgentImpactSomewhat disagree,AIAgentImpactStrongly agree,AIAgentImpactStrongly disagree,AIAgentChallengesNeutral,AIAgentChallengesSomewhat disagree,AIAgentChallengesStrongly agree,AIAgentChallengesSomewhat agree,AIAgentChallengesStrongly disagree,AIAgentKnowledge,AIAgentKnowWrite,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
0,1,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,"Caring for dependents (children, elderly, etc.)",8.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,14.0,"Developer, mobile",20 to 99 employees,People manager,Remote,NaN,Work,10.0,7.0,9.0,6.0,3.0,11.0,12.0,1.0,8.0,14.0,NaN,15.0,7.0,8.0,12.0,11.0,1.0,6.0,13.0,3.0,16.0,NaN,Fintech,3.0,1.0,4.0,9.0,5.0,10.0,12.0,11.0,2.0,6.0,7.0,13.0,14.0,15.0,8.0,NaN,I'm not sure,I have neither consider or transitioned into a...,7.0,3.0,Ukraine,EUR European Euro,52800.0,Yes,Bash/Shell (all shells);Dart;SQL,Dart,Dart,NaN,NaN,Yes,Cloud Firestore;PostgreSQL,NaN,NaN,NaN,NaN,Yes,Amazon Web Services (AWS);Cloudflare;Firebase;...,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,Android Studio;Notepad++;Visual Studio;Visual ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Windows;MacOS;Android,Windows;MacOS;Android;iOS;iPadOS,Confluence;GitHub;GitLab;Jira;Markdown File,Markdown File,Markdown File,NaN,NaN,"Stack Overflow;Reddit;GitHub (public projects,...",NaN,NaN,NaN,NaN,Yes,openAI GPT (chatbot models);openAI Image gener...,NaN,NaN,NaN,NaN,Yes,A few times per week,Between 5 and 10 years,I have never participated in Q&A on Stack Over...,NaN,1.0,NaN,6.0,2.0,3.0,7.0,8.0,9.0,11.0,15.0,NaN,Neutral,"Rarely, almost never","Yes, I use AI tools monthly or infrequently",Indifferent,Neither trust nor distrust,Bad at handling complex tasks,Learning about a codebase;Writing code;Search ...,Project planning;Deployment and monitoring;Lea...,Documenting code;Debugging or fixing code;Test...,NaN,NaN,"AI solutions that are almost right, but not quite",No,"Yes, I use AI agents at work monthly or infreq...",Not at all or minimally,Software engineering,NaN,AI agents have increased my productivity.;AI a...,AI agents have helped me automate repetitive t...,NaN,NaN,NaN,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,The cost of using certain AI agent platforms i...,NaN,NaN,NaN,NaN,Vertex AI,NaN,NaN,NaN,ChatGPT,NaN,When I don’t trust AI’s answers,"Troubleshooting, profiling, debugging",61256.0,10.0
1,2,I am a developer by profession,25-34 years old,"Associate degree (A.A., A.S., etc.)",Employed,NaN,2.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,10.0,"Developer, back-end",500 to 999 employees,Individual contributor,"Hybrid (some in-person, leans heavy to flexibi...",False,Personal Project,13.0,1.0,2.0,9.0,4.0,3.0,12.0,5.0,7.0,14.0,NaN,14.0,1.0,13.0,10.0,9.0,3.0,4.0,2.0,5.0,15.0,NaN,Retail and Consumer Services,10.0,8.0,3.0,9.0,12.0,1.0,6.0,2.0,11.0,4.0,7.0,13.0,14.0,15.0,5.0,NaN,I'm not sure,I have transitioned into a new career and/or i...,6.0,5.0,Netherlands,EUR European Euro,90000.0,Yes,Java,Java;Python;Swift,Java,NaN,NaN,Yes,Dynamodb;MongoDB,Dynamodb;MongoDB,Dynamodb;MongoDB,NaN,NaN,Yes,Amazon Web Services (AWS);Datadog;Docker;Homeb...,Amazon Web Services (AWS);Datadog;Docker;Homeb...,Amazon Web Services (AWS);Datadog;Docker;Homeb...,NaN,NaN,Yes,Spring Boot,Spring Boot,Spring Boot,NaN,NaN,Yes,IntelliJ IDEA;PyCharm;Visual Studio Code;Xcode,IntelliJ IDEA;PyCharm;Visual Studio Code;Xcode,IntelliJ IDEA;PyCharm;Visual Studio Code;Xcode,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Windows;MacOS;iOS;iPadOS,MacOS,Confluence;GitHub;Jira,Confluence;GitHub;Jira,Confluence;GitHub;Jira,NaN,NaN,Stack Overflow;Discord;Reddit;Dev.to;Hacker Ne...,Stack Overflow;Discord;Reddit;Dev.to;Hacker Ne...,Stack Overflow;Discord;Reddit;Dev.to;Hacker Ne...,NaN,NaN,Yes,openAI GPT (chatbot models),openAI GPT (chatbot models),openAI GPT (chatbot models),NaN,NaN,Not sure/can't remember,Multiple times per day,Between 10 and 15 years,"Infrequently, less than once per year",Chat (people);Message Boards;Long-form article...,6.0,NaN,5.0,8.0,2.0,4.0,9.0,10.0,11.0,15.0,NaN,"Yes, somewhat",About half of the time,"Yes, I use AI tools weekly",Indifferent,Neither trust nor distrust,Bad at handling complex tasks,Learning new concepts or technologies,Learning about a codebase;Project planning;Com...,Writing code;Documenting code;Debugging or fix...,NaN,NaN,"AI solutions that are almost right, but not qu...",No,"No, and I don't plan to",Not at all or minimally,NaN,NaN,NaN,NaN,NaN,NaN,NaN,It takes significant time and effort to learn ...,NaN,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,All skills. AI is a flop.,104413.0,9.0
2,3,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Independent contractor, freelancer, or self-em...",None of the above,10.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Technical ...,12.0,"Developer, front-end",NaN,NaN,NaN,False,Work,12.0,2.0,3.0,7.0,5.0,10.0,13.0,1.0,4.0,14.0,NaN,8.0,1.0,2.0,12.0,13.0,3.0,9.0,4.0,11.0,15.0,NaN,Software Development,9.0,6.0,7.0,11.0,8.0,12.0,1.0,5.0,2.0,4.0,3.0,13.0,14.0,15.0,10.0,NaN,No,I have transitioned into a new career and/or i...,3.0,3.0,Ukraine,UAH Ukrainian hryvnia,2214000.0,Yes,Dart;HTML/CSS;JavaScript;TypeScript,Dart;HTML/CSS;JavaScript;TypeScript,Dart;HTML/CSS;JavaScript;TypeScript,NaN,NaN,Yes,MongoDB;MySQL;PostgreSQL,Firebase Realtime Database;MongoDB,MongoDB,NaN,NaN,Yes,Datadog;Firebase;npm;pnpm,Amazon Web Services (AWS);Firebase;npm;pnpm;Vite,Firebase;npm;pnpm,NaN,NaN,Yes,Next.js;Node.js;React,Next.js;Node.js;React,Next.js;Node.js;React,NaN,Solid.js,Yes,Visual Studio Code,Visual Studio Code;Windsurf,Visual Studio Code,NaN,NaN,Google Gemini,Google Gemini;Shadcn/ui,Google Gemini,NaN,NaN,MacOS;Android,MacOS,GitHub;GitLab;Jira,GitHub;GitLab;Jira,GitHub;GitLab;Jira,NaN,NaN,Stack Overflow;Discord;Dev.to;X;YouTube;LinkedIn,Stack Overflow;Discord;Dev.to;X;YouTube;LinkedIn,Stack Overflow;Discord;Dev.to;X;YouTube;LinkedIn,NaN,NaN,Yes,Gemini (Flash general purpose models);openAI G...,Gemini (Flash general purpose models);Gemini (...,Gemini (Flash general purpose models);openAI G...,NaN,NaN,Not sure/can't remember,A few times per week,Between 5 and 10 years,"Infrequently, less than once per year",Chat (people);Videos;Lists of recommendations ...,3.0,NaN,4.0,5.0,1.0,2.0,7.0,9.0,11.0,15.0,NaN,Neutral,About half of the time,"Yes, I use AI tools daily",Favorable,Somewhat trust,Neither good or bad at handling complex tasks,Documenting code;Debugging or fixing code;Test...,NaN,Project planning;Committing and reviewing code...,Learning about a codebase;Writing code;Generat...,NaN,"AI solutions that are almost right, but not qu...",No,"Yes, I use AI agents at work weekly","Yes, somewhat",Software engineering,Multi-platform search enablement,AI agents have increased my productivity.;AI a...,AI agents have improved the quality of my code...,AI agents have improved collaboration within m...,NaN,NaN,It takes significant time and effort to learn ...,My company's IT and/or InfoSec teams have stri...,NaN,I am concerned about the accuracy of the infor...,NaN,Redis,NaN,NaN,NaN,NaN,NaN,ChatGPT;Claude Code;GitHub Copilot;Google Gemini,NaN,When I don’t trust AI’s answers;When I want to...,"Understand how things actually work, problem s...",53061.0,8.0
3,4,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,4.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Videos (no...,5.0,"Developer, back-end","10,000 or more employees",Individual contributor,Remote,False,Personal Project,2.0,12.0,6.0,5.0,13.0,3.0,8.0,11.0,7.0,14.0,NaN,10.0,5.0,8.0,4.0,13.0,12.0,2.0,7.0,1.0,15.0,NaN,Retail and Consumer Services,1.0,2.0,4.0,5.0,6.0,7.0,8.0,9.0,10.0,11.0,12.0,13.0,14.0,15.0,3.0,NaN,No,I have neither consider or transitioned into a...,NaN,NaN,Ukraine,EUR European Euro,31200.0,Yes,Java;Kotlin;SQL,Java;Kotlin,Java;Kotlin,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,Amazon Web Services (AWS);Google Cloud,Amazon Web Services (AWS);Google Cloud,Amazon Web Services (AWS);Google Cloud,NaN,NaN,Yes,Spring Boot,Spring Boot,Spring Boot,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Amazon Bedrock,NaN,NaN,NaN,NaN,Windows,Windows;Ubuntu,GitLab;Jira;Miro,GitLab;Jira,GitLab;Jira,NaN,NaN,Stack Overflow;Reddit;YouTube;LinkedIn,"Stack Overflow;Reddit;GitHub (public projects,...",Stack Overflow;Reddit;YouTube;LinkedIn,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,A few times per month or weekly,Between 3 and 5 years,I have never participated in Q&A on Stack Over...,Videos;Chat (bot/AI),1.0,NaN,4.0,5.0,6.0,7.0,8.0,9.0,11.0,15.0,NaN,Neutral,"Rarely, almost never","Yes, I use AI tools weekly",Favorable,Somewhat trust,Bad at handling complex tasks,NaN,Project planning;Documenting code;Testing code...,Learning about a codebase;Writing code;Debuggi...,Search for answers;Generating content or synth...,NaN,"AI solutions that are almost right, but not qu...",NO,"Yes, I use AI agents at work monthly or infreq...",Not at all or minimally,Software engineering,Language processing,AI agents have accelerated my learning about n...,AI agents have increased my productivity.;AI a...,AI agents have helped me automate repetitive t...,NaN,NaN,It takes significant time and effort to learn ...,NaN,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ChatGPT;Claude Code,NaN,When I don’t trust AI’s answers;When I want to...,NaN,36197.0,6.0
4,5,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...","Caring for dependents (children, elderly, etc.)",21.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools for...",Technical documentation (is generated for/by t...,22.0,Engineering manager,NaN,NaN,NaN,NaN,Work,6.0,3.0,1.0,9.0,10.0,8.0,7.0,4.0,2.0,14.0,NaN,7.0,13.0,3.0,9.0,12.0,6.0,1.0,8.0,14.0,15.0,NaN,Software Development,9.0,4.0,11.0,13.0,14.0,8.0,6.0,5.0,7.0,2.0,1.0,12.0,10.0,15.0,3.0,NaN,No,I have neither consider or transitioned into a...,4.0,3.0,Ukraine,USD United States dollar,60000.0,Yes,C;C#;C++;Delphi;HTML/CSS;Java;JavaScript;Lua;P...,C#;Java;JavaScript;Python;SQL;TypeScript,C#;Java;JavaScript;Python;SQL;TypeScript,NaN,NaN,Yes,Elasticsearch;Microsoft SQL Server;MySQL;Oracl...,Elasticsearch;Oracle;PostgreSQL,Elasticsearch;Oracle;PostgreSQL,NaN,NaN,Yes,Amazon Web Services (AWS);APT;Docker;Make;Mave...,Amazon Web Services (AWS);APT;Docker;Maven (bu...,Amazon Web Services (AWS);APT;Docker;Maven (bu...,NaN,NaN,Yes,Angular;ASP.NET;ASP.NET Core;Flask;jQuery,Angular;ASP.NET Core;Flask,Angular;ASP.NET Core;Flask,NaN,NaN,Yes,Eclipse;IntelliJ IDEA;Jupyter Notebook/Jupyter...,IntelliJ IDEA;Jupyter Notebook/JupyterLab;Note...,IntelliJ IDEA;Jupyter Notebook/JupyterLab;Note...,NaN,NaN,Large Language Model;Google Gemini,Large Language Model,Large Language Model,NaN,NaN,Windows;iOS,Windows;Ubuntu;Debian,Azure Devops;GitHub;Jira,Azure Devops;GitHub;Jira,Azure Devops;GitHub;Jira,NaN,NaN,Stack Overflow;Stack Exchange;GitHub (public p...,Stack Overflow;Stack Exchange;GitHub (public p...,Stack Overflow;Stack Exchange;GitHub (public p...,NaN,NaN,Yes,openAI GPT (chatbot models),openAI GPT (chatbot models),openAI GPT (chatbot models),NaN,NaN,No,A few times per month or weekly,Between 5 and 10 years,"Infrequently, less than once per year",Long-form articles,1.0,NaN,7.0,4.0,2.0,5.0,10.0,6.0,12.0,15.0,NaN,"No, not really","Rarely, almost never","Yes, I use AI tools weekly",Favorable,Neither trust nor distrust,"Good, but not great at handling complex tasks",Learning about a codebase;Writing code;Debuggi...,Project planning;Documenting code;Testing code...,Generating content or synthetic data,NaN,NaN,"AI solutions that are almost right, but not quite",partly,"No, and I don't plan to","Yes, to a great extent",NaN,NaN,NaN,NaN,NaN,NaN,NaN,Integrating AI agents with my existing tools a...,NaN,I am concerned about the accuracy of the infor...,It takes significant time and effort to learn ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers,"critical thinking, the skill to define the tas...",60000.0,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49186,49187,I code primarily as a hobby,18-24 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49187,49188,I am a developer by profession,45-54 years old,Some college/university study without earning ...,Employed,"Caring for dependents (children, elderly, etc.)",25.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools req...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49188,49189,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,None of the above,17.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Videos (no...,31.0,"Architect, software or solutions","10,000 or more employees",People manager,"Hybrid (some in-person, leans heavy to flexibi...",NaN,Personal Project,9.0,2.0,1.0,5.0,3.0,7.0,8.0,4.0,6.0,10.0,NaN,9.0,6.0,2.0,7.0,5.0,4.0,1.0,3.0,8.0,10.0,NaN,Banking/Financial Services,3.0,6.0,7.0,13.0,4.0,9.0,1.0,10.0,2.0,5.0,8.0,11.0,12.0,15.0,14.0,NaN,No,I have somewhat considered changing my career ...,25.0,35.0,Italy,EUR European Euro,80000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Yes, I use AI tools monthly or infrequently",Favorable,Neither trust nor distrust,"Good, but not great at handling complex tasks",Learning about a codebase;Writing code;Documen...,Debugging or fixing code,Project planning;Deployment and monitoring;Pre...,NaN,Search for answers,"AI solutions that are almost right, but not qu...","Yes, partially.","No, I use AI exclusively in copilot/autocomple...",Not at all or minimally,NaN,NaN,NaN,NaN,NaN,NaN,AI agents have increased my productivity.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0

In [47]:
df['Country']

0            Ukraine
1        Netherlands
2            Ukraine
3            Ukraine
4            Ukraine
            ...
49186            NaN
49187            NaN
49188          Italy
49189            NaN
49190            NaN
Name: Country, Length: 49191, dtype: str

In [48]:
df.sort_values(by='Country', inplace=True)

In [49]:
df['Country'].head(100)

6835             Afghanistan
6009             Afghanistan
15707            Afghanistan
7076             Afghanistan
19815            Afghanistan
44796            Afghanistan
45924            Afghanistan
27098            Afghanistan
40306            Afghanistan
40966            Afghanistan
38608            Afghanistan
7924             Afghanistan
7166             Afghanistan
37730                Albania
14757                Albania
36996                Albania
48949                Albania
28587                Albania
2022                 Albania
35183                Albania
16238                Albania
33939                Albania
45420                Albania
3887                 Albania
44878                Albania
44945                Albania
35933                Albania
22399                Albania
8775                 Albania
11873                Albania
41906                Albania
27801                Albania
16849                Albania
25303                Albania
3184                 Albania
44462                Algeria
35358                Algeria
33029                Algeria
1840                 Algeria
47922                Algeria
14679                Algeria
7105                 Algeria
41295                Algeria
46635                Algeria
25844                Algeria
28487                Algeria
34028                Algeria
2540                 Algeria
41257                Algeria
14529                Algeria
26445                Algeria
7233                 Algeria
35297                Algeria
14547                Algeria
1540                 Algeria
24874                Algeria
5707                 Algeria
31300                Algeria
28572                Algeria
31351                Algeria
29464                Algeria
33295                Algeria
36567                Algeria
6986                 Algeria
41846                Algeria
23090                Algeria
16685                Algeria
4526                 Algeria
27411                Algeria
30106                Algeria
35517                Algeria
11321                Algeria
8916                 Algeria
37618                Algeria
22280                Algeria
49027                Algeria
32743                Algeria
36709                Algeria
36660                Algeria
35173                Algeria
7063                 Algeria
39759                Algeria
23949                Algeria
5706                 Algeria
11237                Andorra
39807                Andorra
13745                Andorra
30215                Andorra
24621                Andorra
24200                Andorra
30180                 Angola
37659                 Angola
35524                 Angola
17795                 Angola
4843                  Angola
41392                 Angola
34545                 Angola
34865    Antigua and Barbuda
26979    Antigua and Barbuda
17436              Argentina
Name: Country, dtype: str

In [53]:
df.columns = df.columns.str.strip()

In [59]:
df[['Country','ConvertedCompYearly']].head(100)

                   Country  ConvertedCompYearly
6835           Afghanistan                  NaN
6009           Afghanistan                986.0
15707          Afghanistan                  NaN
7076           Afghanistan               8450.0
19815          Afghanistan                  NaN
44796          Afghanistan                  NaN
45924          Afghanistan               7042.0
27098          Afghanistan                  NaN
40306          Afghanistan               9858.0
40966          Afghanistan              65000.0
38608          Afghanistan               1000.0
7924           Afghanistan                282.0
7166           Afghanistan               5200.0
37730              Albania              67779.0
14757              Albania              34804.0
36996              Albania                  NaN
48949              Albania              17402.0
28587              Albania             118286.0
2022               Albania             139218.0
35183              Albania                  NaN
16238              Albania                  NaN
33939              Albania              17734.0
45420              Albania                  NaN
3887               Albania              14187.0
44878              Albania                  NaN
44945              Albania                  NaN
35933              Albania              50000.0
22399              Albania                 15.0
8775               Albania                  NaN
11873              Albania                  NaN
41906              Albania                  NaN
27801              Albania                  8.0
16849              Albania                236.0
25303              Albania                  NaN
3184               Albania             116014.0
44462              Algeria                  NaN
35358              Algeria                  NaN
33029              Algeria                  NaN
1840               Algeria               4438.0
47922              Algeria                  NaN
14679              Algeria                  NaN
7105               Algeria                  NaN
41295              Algeria              98612.0
46635              Algeria               2400.0
25844              Algeria                185.0
28487              Algeria                  NaN
34028              Algeria               1109.0
2540               Algeria                  NaN
41257              Algeria                  NaN
14529              Algeria                  NaN
26445              Algeria              23114.0
7233               Algeria                  NaN
35297              Algeria                  NaN
14547              Algeria               1156.0
1540               Algeria              20883.0
24874              Algeria                  NaN
5707               Algeria                  NaN
31300              Algeria                  NaN
28572              Algeria                  NaN
31351              Algeria               3852.0
29464              Algeria               7705.0
33295              Algeria                  NaN
36567              Algeria                  NaN
6986               Algeria                  NaN
41846              Algeria                  NaN
23090              Algeria              12000.0
16685              Algeria               7088.0
4526               Algeria                  NaN
27411              Algeria                  NaN
30106              Algeria               6472.0
35517              Algeria                  NaN
11321              Algeria                 17.0
8916               Algeria                  NaN
37618              Algeria              50000.0
22280              Algeria                  NaN
49027              Algeria                  NaN
32743              Algeria                  NaN
36709              Algeria                  NaN
36660              Algeria                  NaN
35173              Algeria                  NaN
7063               Algeria                  NaN
39759              Algeria                  NaN
23949              Algeria                  NaN
5706               Algeria                  NaN
11237              Andorra              34804.0
39807              Andorra             348044.0
13745              Andorra              52207.0
30215              Andorra                  NaN
24621              Andorra                  NaN
24200              Andorra             400000.0
30180               Angola               5234.0
37659               Angola                  NaN
35524               Angola                200.0
17795               Angola                  NaN
4843                Angola              13922.0
41392               Angola             580073.0
34545               Angola                  NaN
34865  Antigua and Barbuda                  1.0
26979  Antigua and Barbuda                  NaN
17436            Argentina             120000.0

In [58]:
[col for col in df.columns if 'comp' in col.lower()]

['AIComplex', 'ConvertedCompYearly']

In [68]:
#sorting countries in ascending order then salary in descending order
df.sort_values(by=['Country','ConvertedCompYearly'], ascending=[True,False], inplace=True)

In [69]:
df[['Country','ConvertedCompYearly']].head(10)

           Country  ConvertedCompYearly
40966  Afghanistan              65000.0
40306  Afghanistan               9858.0
7076   Afghanistan               8450.0
45924  Afghanistan               7042.0
7166   Afghanistan               5200.0
38608  Afghanistan               1000.0
6009   Afghanistan                986.0
7924   Afghanistan                282.0
6835   Afghanistan                  NaN
15707  Afghanistan                  NaN

In [70]:
#largest and smallest values
df['ConvertedCompYearly'].nlargest(10) #10 largest

34267    50000000.0
28700    33552715.0
43143    18387548.0
35353    15430267.0
45971    13921760.0
48428    10000000.0
24900     9531653.0
10025     9000000.0
37352     6890299.0
30728     6371285.0
Name: ConvertedCompYearly, dtype: float64

In [71]:
df.nlargest(10,'ConvertedCompYearly')

,ResponseId,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,AILearnHow,YearsCode,DevType,OrgSize,ICorPM,RemoteWork,PurchaseInfluence,TechEndorseIntro,TechEndorse_1,TechEndorse_2,TechEndorse_3,TechEndorse_4,TechEndorse_5,TechEndorse_6,TechEndorse_7,TechEndorse_8,TechEndorse_9,TechEndorse_13,TechEndorse_13_TEXT,TechOppose_1,TechOppose_2,TechOppose_3,TechOppose_5,TechOppose_7,TechOppose_9,TechOppose_11,TechOppose_13,TechOppose_16,TechOppose_15,TechOppose_15_TEXT,Industry,JobSatPoints_1,JobSatPoints_2,JobSatPoints_3,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,JobSatPoints_13,JobSatPoints_14,JobSatPoints_15,JobSatPoints_16,JobSatPoints_15_TEXT,AIThreat,NewRole,ToolCountWork,ToolCountPersonal,Country,Currency,SalaryUSD,LanguageChoice,LanguageHaveWorkedWith,LanguageWantToWorkWith,LanguageAdmired,LanguagesHaveEntry,LanguagesWantEntry,DatabaseChoice,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,DatabaseAdmired,DatabaseHaveEntry,DatabaseWantEntry,PlatformChoice,PlatformHaveWorkedWith,PlatformWantToWorkWith,PlatformAdmired,PlatformHaveEntry,PlatformWantEntry,WebframeChoice,WebframeHaveWorkedWith,WebframeWantToWorkWith,WebframeAdmired,WebframeHaveEntry,WebframeWantEntry,DevEnvsChoice,DevEnvsHaveWorkedWith,DevEnvsWantToWorkWith,DevEnvsAdmired,DevEnvHaveEntry,DevEnvWantEntry,SOTagsHaveWorkedWith,SOTagsWantToWorkWith,SOTagsAdmired,SOTagsHaveEntry,SOTagsWant Entry,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackAsyncAdmired,OfficeStackHaveEntry,OfficeStackWantEntry,CommPlatformHaveWorkedWith,CommPlatformWantToWorkWith,CommPlatformAdmired,CommPlatformHaveEntr,CommPlatformWantEntr,AIModelsChoice,AIModelsHaveWorkedWith,AIModelsWantToWorkWith,AIModelsAdmired,AIModelsHaveEntry,AIModelsWantEntry,SOAccount,SOVisitFreq,SODuration,SOPartFreq,SO_Dev_Content,SO_Actions_1,SO_Actions_16,SO_Actions_3,SO_Actions_4,SO_Actions_5,SO_Actions_6,SO_Actions_9,SO_Actions_7,SO_Actions_10,SO_Actions_15,SO_Actions_15_TEXT,SOComm,SOFriction,AISelect,AISent,AIAcc,AIComplex,AIToolCurrently partially AI,AIToolDon't plan to use AI for this task,AIToolPlan to partially use AI,AIToolPlan to mostly use AI,AIToolCurrently mostly AI,AIFrustration,AIExplain,AIAgents,AIAgentChange,AIAgent_Uses,AgentUsesGeneral,AIAgentImpactSomewhat agree,AIAgentImpactNeutral,AIAgentImpactSomewhat disagree,AIAgentImpactStrongly agree,AIAgentImpactStrongly disagree,AIAgentChallengesNeutral,AIAgentChallengesSomewhat disagree,AIAgentChallengesStrongly agree,AIAgentChallengesSomewhat agree,AIAgentChallengesStrongly disagree,AIAgentKnowledge,AIAgentKnowWrite,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
34267,34268,I code primarily as a hobby,55-64 years old,"Associate degree (A.A., A.S., etc.)","Independent contractor, freelancer, or self-em...",None of the above,10.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools for...",Technical documentation (is generated for/by t...,10.0,"Developer, embedded applications or devices",NaN,NaN,NaN,NaN,Personal Project,5.0,7.0,8.0,4.0,3.0,9.0,6.0,1.0,2.0,10.0,NaN,4.0,8.0,2.0,7.0,1.0,3.0,5.0,6.0,9.0,10.0,NaN,Other:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,I have neither consider or transitioned into a...,NaN,10.0,United States of America,USD United States dollar,5.000000e+07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Yes, I use AI tools daily",Very favorable,Highly trust,Very well at handling complex tasks,NaN,NaN,Learning about a codebase;Project planning;Wri...,Predictive analytics,Learning new concepts or technologies,Other (write in):,N0,"No, and I don't plan to","No, but my development work has significantly ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,50000000.0,NaN
28700,28701,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,Engaged in paid work (20-29 hours per week),20.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools req...",AI CodeGen tools or AI-enabled apps,27.0,"Developer, full-stack",100 to 499 employees,People manager,Remote,NaN,Work,4.0,2.0,3.0,6.0,7.0,1.0,8.0,5.0,9.0,10.0,NaN,7.0,5.0,6.0,8.0,9.0,2.0,4.0,3.0,1.0,10.0,NaN,Software Development,10.0,11.0,7.0,13.0,4.0,12.0,2.0,8.0,9.0,3.0,1.0,5.0,6.0,15.0,14.0,NaN,No,I have somewhat considered changing my career ...,10.0,3.0,Ukraine,UAH Ukrainian hryvnia,1.400000e+09,Yes,C#;HTML/CSS;JavaScript;SQL;TypeScript,C#;HTML/CSS;SQL;TypeScript,C#;HTML/CSS;SQL;TypeScript,NaN,NaN,Yes,Cosmos DB;Dynamodb;Microsoft SQL Server;Postgr...,Cosmos DB;Dynamodb;Microsoft SQL Server,Cosmos DB;Dynamodb;Microsoft SQL Server,NaN,NaN,Yes,Amazon Web Services (AWS);Docker;Microsoft Azu...,Amazon Web Services (AWS);Docker;Microsoft Azu...,Amazon Web Services (AWS);Docker;Microsoft Azu...,NaN,NaN,Yes,ASP.NET Core;Next.js;React;WordPress,ASP.NET Core;NestJS;Next.js;React,ASP.NET Core;Next.js;React,NaN,NaN,Yes,Cursor;Visual Studio;Visual Studio Code,Cursor;Visual Studio;Visual Studio Code,Cursor;Visual Studio;Visual Studio Code,NaN,NaN,Google Gemini,Google Gemini,Google Gemini,NaN,NaN,Windows;Windows Subsystem for Linux (WSL),Windows;Windows Subsystem for Linux (WSL),Confluence;GitHub;Jira,Confluence;GitHub;Jira,Confluence;GitHub;Jira,NaN,NaN,Stack Overflow;YouTube;LinkedIn;Medium;Company...,Stack Overflow;Medium;Company-sponsored forums,Stack Overflow;Medium;Company-sponsored forums,NaN,NaN,Yes,openAI Reasoning models;Perplexity Sonar models,NaN,NaN,NaN,NaN,Yes,A few times per month or weekly,Between 5 and 10 years,I have never participated in Q&A on Stack Over...,Chat (people);Coding challenges;Chat (bot/AI),3.0,9.0,7.0,6.0,4.0,1.0,8.0,5.0,2.0,10.0,NaN,"No, not really","Rarely, almost never","Yes, I use AI tools daily",Very favorable,Somewhat trust,Neither good or bad at handling complex tasks,Learning about a codebase;Project planning;Wri...,NaN,NaN,Deployment and monitoring,NaN,"AI solutions that are almost right, but not qu...",Yes,"Yes, I use AI agents at work daily","Yes, somewhat",Software engineering;Decision intelligence;Dat...,Language processing;MCP servers,NaN,AI agents have improved collaboration within m...,NaN,AI agents have increased my productivity.;AI a...,NaN,Integrating AI agents with my existing tools a...,NaN,NaN,I am concerned about the accuracy of the infor...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ChatGPT;GitHub Copilot;Google Gemini,NaN,When I don’t trust AI’s answers;When I have et...,NaN,33552715.0,7.0
43143,43144,I code primarily as a hobby,18-24 years old,"Associate degree (A.A., A.S., etc.)",Employed,Engaged in paid work (20-29 hours per week);En...,10.0,"Yes, I am not new to coding but am learning ne...",Other (please specify):,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,10.0,Financial analyst or engineer,100 to 499 employees,NaN,"Hybrid (some remote, leans heavy to in-person)",False,Work,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Other:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,I have neither consider or transitioned into a...,5.0,1.0,Poland,BRL Brazilian real,1.010101e+08,No,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Windows;Android,Windows,NaN,NaN,NaN,NaN,NaN,Stack Overflow;Stack Exchange,NaN,NaN,NaN,NaN,NaN,openAI GPT (chatbot models),openAI GPT (chatbot models),openAI GPT (chatbot models),NaN,NaN,Yes,A few times per month or weekly,NaN,I have never participated in Q&A on Stack Over...,Logic games/puzzles,9.0,2.0,7.0,6.0,4.0,3.0,1.0,5.0,8.0,10.0,NaN,"Yes, somewhat","Rarely, almost never","No, and I don't plan to",Favorable,NaN,I don't use AI tools for complex tasks / I don...,NaN,NaN,NaN,NaN,NaN,Other (write in):,NaN,"No, and I don't plan to",Not at all or minimally,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,being laid off,18387548.0,NaN
35353,35354,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,Engaged in paid work (20-29 hours per week),15.0,"No, I am not new to coding and did not learn n...",NaN,NaN,NaN,12.0,Engineering manager,100 to 499 employees,People manager,"Hybrid (some remote, leans heavy to in-person)",False,Work,7.0,6.0,2.0,4.0,8.0,9.0,3.0,5.0,1.0,10.0,NaN,4.0,6.0,7.0,1.0,3.0,8.0,2.0,9.0,5.0,10.0,NaN,Computer Systems Design and Services,11.0,7.0,14.0,5.0,12.0,1.0,2.0,4.0,3.0,6.0,8.0,13.0,9.0,15.0,10.0,NaN,No,I have neither consider or transitioned into a...,NaN,NaN,"Iran, Islamic Republic of...",IRR\tIranian rial,6.500000e+11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,Less than once per month or monthly,Less than one year,I have never participated in Q&A on Stack Over...,Long-form articles;Lists of recommendations (t...,8.0,5.0,7.0,4.0,3.0,2.0,1.0,9.0,6.0,10.0,NaN,Neutral,"Rarely, almost never","No, and I don't plan to",Unsure,Highly distrust,Neither good or bad at handling complex tasks,Other (write in):,NaN,Committing and reviewing code;Predictive analy...,Project planning;Writing code;Debugging or fix...,Learning about a codebase;Generating content o...,"AI solutions that are almost right, but not qu...",NaN,"Yes, I use AI agents at work daily","Yes, somewhat",Software engineering;IT operations;Customer se...,Integration with external agents and APIs,AI agents have helped me automate repetitive t...,AI agents have increased my productivity.;AI a...,AI agents have improved the quality of my code...,NaN,NaN,I am concerned about the accuracy of the infor...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ChatGPT;Google Gemini,NaN,When I’m stuck and can’t explain the problem,NaN,15430267.0,8.0
45971,45972,I work with developers or my work supports dev...,55-64 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,Engaged in paid work (20-29 hours per week),30.0,"Yes, I am not new to coding but am learning ne...",Colleague or on-the-job training,"Yes, I learned how to use AI-enabled tools req...",Colleague or on-the-job training,10.0,"Senior executive (C-suite, VP, etc.)","1,000 to 4,999 employees",People manager,"Hybrid (some in-person, leans heavy to flexibi...",NaN,Work,2.0,5.0,8.0,3.0,1.0,9.0,6.0,7.0,4.0,10.0,NaN,8.0,6.0,4.0,1.0,5.0,2.0,3.0,7.0,9.0,10.0,NaN,"Internet, Telecomm or Information Services",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,I have neither consider or transitioned into a...,NaN,NaN,Netherlands,EUR European Euro,1.200000e+07,NaN,Java;Kotlin,Go;Java;Rust,Java,NaN,NaN,Yes,Supabase;Clickhouse,Supabase;Clickhouse,Supabase;Clickhouse,NaN,NaN,Yes,Cloudflare,Cloudflare,Cloudflare,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,Bolt;Lovable.dev,Lovable.dev,Lovable.dev,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,Gemini (Flash general purpose models),Gemini (Flash general purpose models),Gemini (Flash general purpose models),NaN,NaN,No,"Infrequently, less than once per year",Between 5 and 10 years,I have never participated in Q&A on Stack Over...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13921760.0,NaN
48428,48429,I code primarily as a hobby,18-24 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Student,Engaged in paid work (10-19 hours per week);En...,NaN,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools req...",Technical documentation (is generated for/by t...,2.0,Student,20 to 99 employees,People manager,"Your choice (very flexible, you can come in wh...",NaN,Work,7.0,1.0,6.0,8.0,3.0,4.0,5.0,2.0,9.0,10.0,Витрати керовані,5.0,3.0,1.0,6.0,9.0,2.0,7.0,8.0,4.0,10.0,Відсутність штучного інтелекту,Banking/Financial Services,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,I have neither consider or transitioned into a...,NaN,NaN,Ukraine,USD United States dollar,1.000000e+07,Yes,Assembly;C#;GDScript;HTML/CSS;JavaScript;Micro...,Ada;Bash/Shell (all shells);C;C#;C++;COBOL;Dar...,C#;GDScript;HTML/CSS;JavaScript;MicroPython,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,Amazon Web Services (AWS);Bun;Cargo;Cloudflare,Amazon Web Services (AWS);Ansible;APT;Bun;Carg...,Amazon Web Services (AWS);Bun;Cargo;Cloudflare,NaN,NaN,Yes,NaN,NaN,NaN,NaN,NaN,Yes,NaN,NaN,NaN,NaN,NaN,SwiftData;Microsoft Fabric;Google Gemini,SwiftData;Microsoft Fabric;Google Gemini,SwiftData;Microsoft Fabric;Google Gemini,NaN,NaN,Windows;MacOS;Ubuntu;Android;Windows Subsystem...,Windows;MacOS;Ubuntu;Android;Windows Subsystem...,Airtable;Asana;Confluence;GitHub;GitLab;Google...,Airtable;Asana;Confluence;GitHub;GitLab;Google...,Airtable;Asana;Confluence;GitHub;GitLab;Google...,NaN,NaN,Stack Overflow;Stack Exchange;Discord;Reddit;D...,Stack Overflow;Stack Exchange;Discord;Reddit;D...,Stack Overflow;Stack Exchange;Discord;Reddit;D...,NaN,NaN,Yes,NaN,NaN,NaN,NaN,NaN,Not sure/can't remember,Multiple times per day,Between 1 and 3 years,Less than once per month or monthly,Chat (people);Logic games/puzzles;Chat (bot/AI),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Yes, definitely","Rarely, almost never","Yes, I use AI tools daily",Very favorable,Highly trust,Very well at handling complex tasks,NaN,NaN,NaN,NaN,Learning about a codebase;Project planning;Wri...,"AI solutions that are almost right, but not qu...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10000000.0,NaN
24900,24901,I am a developer by profession,18-24 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,Engaged in paid work (20-29 hours per week),1.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,4.0,"Developer, full-stack",100 to 499 employees,Individual contributor,"Hybrid (some remote, leans heavy to in-person)",NaN,Personal Project,8.0,1.0,2.0,6.0,7.0,3.0,9.0,5.0,4.0,10.0,NaN,8.0,6.0,1.0,2.0,3.0,4.0,7.0,9.0,5.0,10.0,NaN,Software Development,6.0,9.0,3.0,1.0,5.0,4.0,8.0,12.0,11.0,7.0,2.0,13.0,14.0,15.0,10.0,NaN,Yes,I have strongly considered changing my career ...,3.0,3.0,India,INR Indian rupee,8.200000e+08,Yes,HTML/CSS;Java;JavaScript;SQL;TypeScript,C++;Elixir;Erlang;Go;Java;Python;R;Scala;SQL,Java;SQL,NaN,"Racket, Closure",Yes,Cloud Firestore;Elasticsearch;MySQL;PostgreSQL...,Cassandra;MongoDB;Neo4J;PostgreSQL;Redis;Cockr...,PostgreSQL,NaN,NaN,Yes,APT;Docker;Google Cloud;Maven (build tool),Amazon Web Services (AWS);Cloudflare;Docker;Go...,Docker;Google Cloud;Maven (build tool),NaN,NaN,Yes,Angular;Spring Boot,Angular;Django;Spring Boot;Svelte,Angular;Spring Boot,NaN,NaN,Yes,Eclipse;IntelliJ IDEA;Nano;Sublime Text;Visual...,Neovim,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Pop!_OS,Windows,Confluence;GitLab;Jira;Lucid (includes Lucidch...,NaN,NaN,TickTick,NaN,Stack Overflow;Stack Exchange;Reddit;Dev.to;Gi...,Reddit;Dev.to;Hashnode;GitHub (public projects...,"Reddit;Dev.to;GitHub (public projects, not pri...",NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,A few times per week,Between 1 and 3 years,"Infrequently, less than once per year",Long-form articles;Coding challenges;Logic gam...,6.0,2.0,4.0,8.0,9.0,7.0,3.0,1.0,5.0,10.0,NaN,"No, not really",More than half the time,"Yes, I use AI tools weekly",Favorable,Somewhat trust,Neither good or bad at handling complex tasks,Learning about a codebase;Writing code;Debuggi...,Project planning;Predictive analytics;Search f...,Documenting code;Testing code;Creating or main...,Deployment and monitoring,Generating content or synthetic data,"AI solutions that are almost right, but not qu...",NaN,"No, I use AI exclusively in copilot/autocomple...","Yes, somewhat",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,I am concerned about the accuracy of the infor...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I want to fully understand something;When...,NaN,9531653.0,4.0
10025,10026,I am a developer by profession,25-34 years old,Primary/elementary school,Employed,Attending school (full-time),2.0,"No, I am not new to coding and did not learn n...",NaN,"No, I learned something that was not related t...",NaN,20.0,Academic researcher,"5,000 to 9,999 employees",NaN,Remote,False,School,10.0,2.0,4.0,5.0,7.0,1.0,8.0,3.0,6.0,9.0,NaN,5.0,3.0,4.0,8.0,6.0,2.0,9.0,7.0,1.0,10.0,NaN,Government,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,I'm not sure,I have somewhat considered changing my career ...,5.0,7.0,United States of America,USD United States dollar,9.000000e+06,No,NaN,NaN,NaN,NaN,NaN,Yes,Firebase Realtime Database;PostgreSQL;Supabase,MongoDB,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,ASP.NET;ASP.NET Core;Django;Next.js;React,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Windows,Windows,GitHub,NaN,NaN,NaN,NaN,Discord,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,No,A few times per month or weekly,Between 3 and 5 years,"Infrequently, less than once per year",NaN,2.0,5.0,9.0,4.0,7.0,1.0,8.0,6.0,3.0,10.0,NaN,Neutral,Less than half of the time,"No, and I don't plan to",Unfavorable,Highly distrust,Very poor at handling complex tasks,NaN,Learning about a codebase;Project planning;Wri...,Search for answers,Predictive analytics,Documenting code;Committing and reviewing code...,I don’t use AI tools regularly,"nope, thats only for people with no skill","No, and I don't plan to","No, but my development work has significantly ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,Integrating AI agents with my existing tools a...,It takes significant time and effort to learn ...,I am concerned about the accuracy of the infor...,The cost of using certain AI agent platforms i...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,Everything,9000000.0,9.0