In [1]:
people = {
    "first":["corey","sophie", "cristian"],
    "last":["schafer","muthoni","rodriguez"],
    "email":["corey@gmail.com","muthoni@gmail.com","rodriguez@gmail.com"]
}

In [2]:
import pandas as pd

In [3]:
df = pd.DataFrame(people)

In [4]:
df

      first       last                email
0     corey    schafer      corey@gmail.com
1    sophie    muthoni    muthoni@gmail.com
2  cristian  rodriguez  rodriguez@gmail.com

In [5]:
#looking at columns

In [6]:
df.columns

Index(['first', 'last', 'email'], dtype='str')

In [7]:
# modifying column name
df.columns = ['first_name','last_name','email']

In [8]:
df

  first_name  last_name                email
0      corey    schafer      corey@gmail.com
1     sophie    muthoni    muthoni@gmail.com
2   cristian  rodriguez  rodriguez@gmail.com

In [9]:
#list comprehensions
df.columns = [x.upper() for x in df.columns]

In [10]:
df

  FIRST_NAME  LAST_NAME                EMAIL
0      corey    schafer      corey@gmail.com
1     sophie    muthoni    muthoni@gmail.com
2   cristian  rodriguez  rodriguez@gmail.com

In [11]:
df.columns = ['first name','last name','email']

In [12]:
df

  first name  last name                email
0      corey    schafer      corey@gmail.com
1     sophie    muthoni    muthoni@gmail.com
2   cristian  rodriguez  rodriguez@gmail.com

In [13]:
df.columns = df.columns.str.replace(' ','_')

In [14]:
df

  first_name  last_name                email
0      corey    schafer      corey@gmail.com
1     sophie    muthoni    muthoni@gmail.com
2   cristian  rodriguez  rodriguez@gmail.com

In [15]:
#rename method and pass a dictionary
df.rename(columns={
    'first_name':'first',
    'last_name':'last'

},inplace=True)

In [16]:
df

      first       last                email
0     corey    schafer      corey@gmail.com
1    sophie    muthoni    muthoni@gmail.com
2  cristian  rodriguez  rodriguez@gmail.com

In [17]:
#updating a single value
df.loc[2]

first               cristian
last               rodriguez
email    rodriguez@gmail.com
Name: 2, dtype: str

In [18]:
#updating a single value
df.loc[2] = ['john','smith','johnsmith@gmail.com']

In [19]:
df

    first     last                email
0   corey  schafer      corey@gmail.com
1  sophie  muthoni    muthoni@gmail.com
2    john    smith  johnsmith@gmail.com

In [20]:
#updating a multiple value for a single row
df.loc[2,['last','email']] = ['Doe','johndoe@gmail.com']

In [21]:
df

    first     last              email
0   corey  schafer    corey@gmail.com
1  sophie  muthoni  muthoni@gmail.com
2    john      Doe  johndoe@gmail.com

In [22]:
df.loc[2,'last'] = 'Smith'

In [23]:
df

    first     last              email
0   corey  schafer    corey@gmail.com
1  sophie  muthoni  muthoni@gmail.com
2    john    Smith  johndoe@gmail.com

In [24]:
df.at[2,'last']

'Smith'

In [25]:
df.at[2,'last'] = 'Doe'

In [26]:
df

    first     last              email
0   corey  schafer    corey@gmail.com
1  sophie  muthoni  muthoni@gmail.com
2    john      Doe  johndoe@gmail.com

In [27]:
#using a filter
filt = (df['email'] == 'johndoe@gmail.com')

In [28]:
df[filt]

  first last              email
2  john  Doe  johndoe@gmail.com

In [29]:
df[filt]['last']

2    Doe
Name: last, dtype: str

In [30]:
# df[filt]['last'] = 'smith' #set in a temporary object get an error

In [31]:
df.loc[filt, 'last'] = 'Smith'

In [32]:
df

    first     last              email
0   corey  schafer    corey@gmail.com
1  sophie  muthoni  muthoni@gmail.com
2    john    Smith  johndoe@gmail.com

In [33]:
#updating multiple rows of data setting the column to lower case value of itself
df['email'].str.upper() #this assigns lower case but hasnt really implemented

0      COREY@GMAIL.COM
1    MUTHONI@GMAIL.COM
2    JOHNDOE@GMAIL.COM
Name: email, dtype: str

In [34]:
df['email'] = df['email'].str.upper()

In [35]:
df

    first     last              email
0   corey  schafer    COREY@GMAIL.COM
1  sophie  muthoni  MUTHONI@GMAIL.COM
2    john    Smith  JOHNDOE@GMAIL.COM

In [36]:
#apply - calling a function on our values can work on either a dataframe or a series object

#map
#apply map

In [37]:
#apply on series: applies a function on every value on our series
df['email'].apply(len)

0    15
1    17
2    17
Name: email, dtype: int64

In [38]:
#update values using apply
def update_email(email):
    return email.upper()

In [39]:
df['email'].apply(update_email) #this doesnt really change the row values

0      COREY@GMAIL.COM
1    MUTHONI@GMAIL.COM
2    JOHNDOE@GMAIL.COM
Name: email, dtype: str

In [40]:
df['email'] = df['email'].apply(update_email) #this changes the row values

In [41]:
df

    first     last              email
0   corey  schafer    COREY@GMAIL.COM
1  sophie  muthoni  MUTHONI@GMAIL.COM
2    john    Smith  JOHNDOE@GMAIL.COM

In [42]:
#using lambda function (dont actually have a name)
df['email'] = df['email'].apply(lambda x:x.lower())

In [43]:
df

    first     last              email
0   corey  schafer    corey@gmail.com
1  sophie  muthoni  muthoni@gmail.com
2    john    Smith  johndoe@gmail.com

In [44]:
#apply on dataframes runs the function on each column/series in it
df.apply(len,axis='columns')

0    3
1    3
2    3
dtype: int64

In [45]:
len(df['email']) #manually check the length of a series

3

In [46]:
#min method
df.apply(pd.Series.min)

first              corey
last               Smith
email    corey@gmail.com
dtype: str

In [47]:
df.apply(lambda x:x.min())

first              corey
last               Smith
email    corey@gmail.com
dtype: str

In [48]:
#what about applying a function to every value to a dataframe
#applymap - being disregarded
df.map(len)

   first  last  email
0      5     7     15
1      6     7     17
2      4     5     17

In [49]:
df.map(str.lower)

    first     last              email
0   corey  schafer    corey@gmail.com
1  sophie  muthoni  muthoni@gmail.com
2    john    smith  johndoe@gmail.com

In [50]:
df['first'].map({
    'corey':'chrisss',
    'sophie':'soni'
})

0    chrisss
1       soni
2        NaN
Name: first, dtype: str

In [51]:
df['first'].replace({
    'corey':'chrisss',
    'sophie':'soni'
})

0    chrisss
1       soni
2       john
Name: first, dtype: str

In [52]:
df

    first     last              email
0   corey  schafer    corey@gmail.com
1  sophie  muthoni  muthoni@gmail.com
2    john    Smith  johndoe@gmail.com

In [53]:
#now we apply to the actual column
df['first'] = df['first'].replace({
    'corey':'chrisss',
    'sophie':'soni'
})

In [54]:
df

     first     last              email
0  chrisss  schafer    corey@gmail.com
1     soni  muthoni  muthoni@gmail.com
2     john    Smith  johndoe@gmail.com

In [55]:
df.drop(index=4)

KeyError: '[4] not found in axis'