In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
employees = pd.DataFrame({
    "emp_id": ["E001", "E002", "E003", "E004", "E005",
               "E006", "E007", "E008", "E009", "E010"],

    "name": ["Alice", "Bob", "Carol", "David", "Eva",
             "Frank", "Grace", "Henry", "Ivy", "Jack"],

    "department": ["IT", "HR", "Finance", "IT", "HR",
                   "Finance", "IT", "Marketing", "Finance", "HR"],

    "salary": [85000, 60000, 92000, 75000, np.nan,
               105000, 95000, 70000, 88000, 65000],

    "age": [28, 35, 42, 51, 29,
            55, 38, 45, 49, 60],

    "city": ["Nairobi", "Mombasa", "Nairobi", "Kisumu", "Nairobi",
             "Mombasa", "Nakuru", "Nairobi", "Kisumu", "Mombasa"],

    "performance": ["Excellent", "Good", "Excellent", "Poor", "Good",
                    "Excellent", "Excellent", "Average", "Good", "Poor"]
})

In [4]:
employees

  emp_id   name department    salary  age     city performance
0   E001  Alice         IT   85000.0   28  Nairobi   Excellent
1   E002    Bob         HR   60000.0   35  Mombasa        Good
2   E003  Carol    Finance   92000.0   42  Nairobi   Excellent
3   E004  David         IT   75000.0   51   Kisumu        Poor
4   E005    Eva         HR       NaN   29  Nairobi        Good
5   E006  Frank    Finance  105000.0   55  Mombasa   Excellent
6   E007  Grace         IT   95000.0   38   Nakuru   Excellent
7   E008  Henry  Marketing   70000.0   45  Nairobi     Average
8   E009    Ivy    Finance   88000.0   49   Kisumu        Good
9   E010   Jack         HR   65000.0   60  Mombasa        Poor

# 1. Give a 10% salary raise to all IT employees.

In [6]:
IT_employees = employees.loc[employees['department'] == 'IT']
IT_employees

  emp_id   name department   salary  age     city performance
0   E001  Alice         IT  85000.0   28  Nairobi   Excellent
3   E004  David         IT  75000.0   51   Kisumu        Poor
6   E007  Grace         IT  95000.0   38   Nakuru   Excellent

In [7]:
IT_employees['salary']

0    85000.0
3    75000.0
6    95000.0
Name: salary, dtype: float64

In [10]:
raise_salary = (IT_employees['salary'] + 0.1*IT_employees['salary'])
raise_salary

0     93500.0
3     82500.0
6    104500.0
Name: salary, dtype: float64

In [12]:
employees['department'] == 'IT' = raise_salary

SyntaxError: cannot assign to comparison (3979205840.py, line 1)

In [16]:
employees.loc[employees['department']=='IT','salary'] = employees.loc[employees['department']=='IT','salary'] * 1.10

In [17]:
employees

  emp_id   name department    salary  age     city performance
0   E001  Alice         IT   93500.0   28  Nairobi   Excellent
1   E002    Bob         HR   60000.0   35  Mombasa        Good
2   E003  Carol    Finance   92000.0   42  Nairobi   Excellent
3   E004  David         IT   82500.0   51   Kisumu        Poor
4   E005    Eva         HR       NaN   29  Nairobi        Good
5   E006  Frank    Finance  105000.0   55  Mombasa   Excellent
6   E007  Grace         IT  104500.0   38   Nakuru   Excellent
7   E008  Henry  Marketing   70000.0   45  Nairobi     Average
8   E009    Ivy    Finance   88000.0   49   Kisumu        Good
9   E010   Jack         HR   65000.0   60  Mombasa        Poor

In [18]:
raise_salary
employees['raise'] = raise_salary

In [19]:
employees

  emp_id   name department    salary  age     city performance     raise
0   E001  Alice         IT   93500.0   28  Nairobi   Excellent   93500.0
1   E002    Bob         HR   60000.0   35  Mombasa        Good       NaN
2   E003  Carol    Finance   92000.0   42  Nairobi   Excellent       NaN
3   E004  David         IT   82500.0   51   Kisumu        Poor   82500.0
4   E005    Eva         HR       NaN   29  Nairobi        Good       NaN
5   E006  Frank    Finance  105000.0   55  Mombasa   Excellent       NaN
6   E007  Grace         IT  104500.0   38   Nakuru   Excellent  104500.0
7   E008  Henry  Marketing   70000.0   45  Nairobi     Average       NaN
8   E009    Ivy    Finance   88000.0   49   Kisumu        Good       NaN
9   E010   Jack         HR   65000.0   60  Mombasa        Poor       NaN

In [20]:
employees.fillna('No raise applied')

,emp_id,name,department,salary,age,city,performance,raise
0,E001,Alice,IT,93500.0,28,Nairobi,Excellent,93500.0
1,E002,Bob,HR,60000.0,35,Mombasa,Good,No raise applied
2,E003,Carol,Finance,92000.0,42,Nairobi,Excellent,No raise applied
3,E004,David,IT,82500.0,51,Kisumu,Poor,82500.0
4,E005,Eva,HR,No raise applied,29,Nairobi,Good,No raise applied
5,E006,Frank,Finance,105000.0,55,Mombasa,Excellent,No raise applied
6,E007,Grace,IT,104500.0,38,Nakuru,Excellent,104500.0
7,E008,Henry,Marketing,70000.0,45,Nairobi,Average,No raise applied
8,E009,Ivy,Finance,88000.0,49,Kisumu,Good,No raise applied
9,E010,Jack,HR,65000.0,60,Mombasa,Poor,No raise applied

In [21]:
employees['department'] == 'IT'

0     True
1    False
2    False
3     True
4    False
5    False
6     True
7    False
8    False
9    False
Name: department, dtype: bool

In [22]:
employees.loc[employees['department'] == 'IT']

  emp_id   name department    salary  age     city performance     raise
0   E001  Alice         IT   93500.0   28  Nairobi   Excellent   93500.0
3   E004  David         IT   82500.0   51   Kisumu        Poor   82500.0
6   E007  Grace         IT  104500.0   38   Nakuru   Excellent  104500.0

# 2. Change the performance rating to "Outstanding" for employees earning more than 90,000 and currently rated "Excellent".

In [33]:
employees.loc[(employees['salary'] >= 90000) & (employees['performance'] == 'Excellent'), 'performance'] = employees.loc[(employees['salary'] >= 90000) & (employees['performance'] == 'Excellent'), 'performance'] = 'Outstanding'

In [34]:
employees

  emp_id   name department    salary  age     city  performance     raise
0   E001  Alice         IT   93500.0   28  Nairobi  Outstanding   93500.0
1   E002    Bob         HR   60000.0   35  Mombasa         Good       NaN
2   E003  Carol    Finance   92000.0   42  Nairobi  Outstanding       NaN
3   E004  David         IT   82500.0   51   Kisumu         Poor   82500.0
4   E005    Eva         HR       NaN   29  Nairobi         Good       NaN
5   E006  Frank    Finance  105000.0   55  Mombasa  Outstanding       NaN
6   E007  Grace         IT  104500.0   38   Nakuru  Outstanding  104500.0
7   E008  Henry  Marketing   70000.0   45  Nairobi      Average       NaN
8   E009    Ivy    Finance   88000.0   49   Kisumu         Good       NaN
9   E010   Jack         HR   65000.0   60  Mombasa         Poor       NaN

# 3. Select only the name, salary, and department columns for employees older than 40.

In [35]:
employees.loc[employees['age'] > 40,['name','salary','department']]

    name    salary department
2  Carol   92000.0    Finance
3  David   82500.0         IT
5  Frank  105000.0    Finance
7  Henry   70000.0  Marketing
8    Ivy   88000.0    Finance
9   Jack   65000.0         HR

# 4. Find employees from Nairobi whose salary is between 70,000 and 100,000.

In [38]:
employees.loc[(employees['city'] == 'Nairobi') & ((employees['salary'] >= 7000) & (employees['salary'] <= 100000)) ]

  emp_id   name department   salary  age     city  performance    raise
0   E001  Alice         IT  93500.0   28  Nairobi  Outstanding  93500.0
2   E003  Carol    Finance  92000.0   42  Nairobi  Outstanding      NaN
7   E008  Henry  Marketing  70000.0   45  Nairobi      Average      NaN