In [1]:
import pandas as pd

In [2]:

dict1 ={'Name':['Priyang','Aadhya','Krisha','Vedant','Parshv',
                'Mittal','Archana'],
                'Marks':[98,89,99,87,90,83,99],
                'Gender':['Male','Female','Female','Male','Male',
                         'Female','Female']
               }

In [3]:
df = pd.DataFrame(dict1)

In [4]:
df

      Name  Marks  Gender
0  Priyang     98    Male
1   Aadhya     89  Female
2   Krisha     99  Female
3   Vedant     87    Male
4   Parshv     90    Male
5   Mittal     83  Female
6  Archana     99  Female

# 1. Display Top 3 rows of the dataset

In [5]:
df.head(3)

      Name  Marks  Gender
0  Priyang     98    Male
1   Aadhya     89  Female
2   Krisha     99  Female

# 2. Check the last 3 rows

In [6]:
df.tail(3)

      Name  Marks  Gender
4   Parshv     90    Male
5   Mittal     83  Female
6  Archana     99  Female

# 3. Find shape of our dataset

In [9]:
df.shape #rows,columns

(7, 3)

In [11]:
print(f"Number of rows: {df.shape[0]}" )
print(f"Number of columns: {df.shape[1]}" )

Number of rows: 7
Number of columns: 3

# 4. Get information about our dataset like
   Total number of rows
   Total number of columns
   Data types of each column
   Memory requirement

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    7 non-null      str
 1   Marks   7 non-null      int64
 2   Gender  7 non-null      str
dtypes: int64(1), str(2)
memory usage: 300.0 bytes

# 5. Check null values

In [16]:
df.isnull()
df.isnull().sum()
df.isnull().sum(axis=0)
df.isnull().sum(axis=1)

0    0
1    0
2    0
3    0
4    0
5    0
6    0
dtype: int64

# 6. Numeric statistics

In [17]:
df.describe() #in this case we only have one numerical column which is marks

           Marks
count   7.000000
mean   92.142857
std     6.491753
min    83.000000
25%    88.000000
50%    90.000000
75%    98.500000
max    99.000000

In [18]:
#if we want numerical statistics for all columns in the dataset we use the include
# and we say include all
df.describe(include='all')

           Name      Marks  Gender
count         7   7.000000       7
unique        7        NaN       2
top     Priyang        NaN  Female
freq          1        NaN       4
mean        NaN  92.142857     NaN
std         NaN   6.491753     NaN
min         NaN  83.000000     NaN
25%         NaN  88.000000     NaN
50%         NaN  90.000000     NaN
75%         NaN  98.500000     NaN
max         NaN  99.000000     NaN

# 7 Find unique values from the gender column

In [19]:
df['Gender'].unique()

<StringArray>
['Male', 'Female']
Length: 2, dtype: str

# 8 Find number of unique values from the gender column

In [20]:
df['Gender'].nunique()

2

The history saving thread hit an unexpected error (OperationalError('attempt to write a readonly database')).History will not be written to the database.

# 9 Find unique values from the gender column

In [21]:
df['Gender'].value_counts()

Gender
Female    4
Male      3
Name: count, dtype: int64

# 10 Find total nmber of students having marks btw 90 to 100 inclusive using between method

In [34]:
df['Marks'].between(90,100).sum() #using between method they are both inclusive

np.int64(4)

In [23]:
df[df['Marks'] >= 90]

      Name  Marks  Gender
0  Priyang     98    Male
2   Krisha     99  Female
4   Parshv     90    Male
6  Archana     99  Female

In [29]:
df[(df['Marks'] >= 90) & (df['Marks'] <= 100)]

      Name  Marks  Gender
0  Priyang     98    Male
2   Krisha     99  Female
4   Parshv     90    Male
6  Archana     99  Female

In [28]:

len(df[(df['Marks'] >= 90) & (df['Marks'] <= 100)])

4

In [31]:
len((df['Marks'] >= 90) & (df['Marks'] <= 100))

7

# The difference between the len() and .sum() is that: sum will only count the True value in a boolean mask while len will count both True and False values you'll have to us in different scenarios:

for example if we use .sum directly on the boolean mask thats fine but you cant do the same with len

the best case  for len is after filtering so meaning putting the boolean mask inside the dataframe to filter it

like so:

# len(df[(df['Marks'] >= 90) & (df['Marks'] <= 100)])

## NB: sum() and .sum() work the same is that sum() is python built

# 11 Find average marks

In [35]:
df['Marks'].mean()

np.float64(92.14285714285714)

# 12 using user-defined function with apply method

In [42]:
def marks(x):
    return x//2

In [38]:
df['Marks'].apply(marks)

0    49.0
1    44.5
2    49.5
3    43.5
4    45.0
5    41.5
6    49.5
Name: Marks, dtype: float64

In [39]:
#Adding a new colum

In [40]:
df['Half_marks'] = df['Marks'].apply(marks)

In [41]:
df

      Name  Marks  Gender  Half_marks
0  Priyang     98    Male        49.0
1   Aadhya     89  Female        44.5
2   Krisha     99  Female        49.5
3   Vedant     87    Male        43.5
4   Parshv     90    Male        45.0
5   Mittal     83  Female        41.5
6  Archana     99  Female        49.5

# 13 using lambda function with apply method

In [43]:
df['Marks'].apply(lambda x:x/2)

0    49.0
1    44.5
2    49.5
3    43.5
4    45.0
5    41.5
6    49.5
Name: Marks, dtype: float64

# 14 using in-built function with apply method

In [44]:
df['Name'].apply(len)

0    7
1    6
2    6
3    6
4    6
5    6
6    7
Name: Name, dtype: int64

# 15 Map function